std = 'luajit'
read_globals = {'box', '_TARANTOOL', 'tonumber64', 'misc', table = {fields = {'deepcopy', 'copy'}}}
max_line_length = 120

-- Generated by our own plugin or descriptor generator: their preludes
-- localize helpers that a given file may not use.
exclude_files = {
    '.rocks/',
    '.worktrees/',
    'examples/expected/',
    'runtime/pb/gen/',
    'runtime/pb/descriptors_builtin.lua',
}

-- Unused arguments: handler, callback and method signatures are fixed
-- by the interfaces they implement.
ignore = {'212'}

-- LuaLS annotations (a type union, a function type) cannot be wrapped.
files['runtime/pb/_types.lua'] = {max_line_length = false}

-- Allocation probes: they bind results they never read and redefine
-- locals on purpose, to keep values alive while allocations are counted.
files['bench/alloc_probe.lua'] = {ignore = {'211', '241'}}
files['bench/c_accel/ffi_probe.lua'] = {ignore = {'211', '411'}}
