-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: c_grow_proto2.proto
-- syntax: proto2
-- package: c_grow_proto2

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/c_grow_proto2"}

-- Pre-declare message descriptors so cross-references resolve.
M.KV_descriptor = {name = "c_grow_proto2.KV"}
M.Holder_descriptor = {name = "c_grow_proto2.Holder"}
M.Holder_Entry_descriptor = {name = "c_grow_proto2.Holder.Entry"}
M.Holder_Single_descriptor = {name = "c_grow_proto2.Holder.Single"}

-- Message: c_grow_proto2.KV
M.KV_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="bytes", optional=true},
    {name="value", id=2, kind='scalar', proto_type="bytes", optional=true},
}
pb.finalize_message(M.KV_descriptor)
M.KV_fields = pb.field_names({
    key = "key",
    value = "value",
})

-- Message: c_grow_proto2.Holder
M.Holder_descriptor.fields = {
    {name="first", id=1, kind='message', message=M.KV_descriptor, optional=true},
    {name="entry", id=2, kind='group', message=M.Holder_Entry_descriptor, repeated=true},
    {name="single", id=5, kind='group', message=M.Holder_Single_descriptor, optional=true},
    {name="last", id=8, kind='message', message=M.KV_descriptor, optional=true},
}
pb.finalize_message(M.Holder_descriptor)
M.Holder_fields = pb.field_names({
    first = "first",
    entry = "entry",
    single = "single",
    last = "last",
})

-- Message: c_grow_proto2.Holder.Entry
M.Holder_Entry_descriptor.fields = {
    {name="blob", id=3, kind='scalar', proto_type="bytes", optional=true},
    {name="kv", id=4, kind='message', message=M.KV_descriptor, optional=true},
}
pb.finalize_message(M.Holder_Entry_descriptor)
M.Holder_Entry_fields = pb.field_names({
    blob = "blob",
    kv = "kv",
})

-- Message: c_grow_proto2.Holder.Single
M.Holder_Single_descriptor.fields = {
    {name="kv", id=6, kind='message', message=M.KV_descriptor, optional=true},
    {name="kvs", id=7, kind='message', message=M.KV_descriptor, repeated=true},
}
pb.finalize_message(M.Holder_Single_descriptor)
M.Holder_Single_fields = pb.field_names({
    kv = "kv",
    kvs = "kvs",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@class c_grow_proto2.KV
---@field key? string
---@field value? string

---@class c_grow_proto2.Holder
---@field first? c_grow_proto2.KV
---@field entry c_grow_proto2.Holder.Entry[]
---@field single? c_grow_proto2.Holder.Single
---@field last? c_grow_proto2.KV

---@class c_grow_proto2.Holder.Entry
---@field blob? string
---@field kv? c_grow_proto2.KV

---@class c_grow_proto2.Holder.Single
---@field kv? c_grow_proto2.KV
---@field kvs c_grow_proto2.KV[]

---@param t? c_grow_proto2.KV
---@return c_grow_proto2.KV
function M.KV_new(t) return t or {} end

---@param t c_grow_proto2.KV
---@return string
function M.KV_encode(t)
    local encode_varint = wire.encode_varint
    local _d = M.KV_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for c_grow_proto2.KV, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 1: key
    v = t.key
    if v ~= nil then
        n = n + 1; out[n] = "\x0a"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    -- field 2: value
    v = t.value
    if v ~= nil then
        n = n + 1; out[n] = "\x12"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return c_grow_proto2.KV
function M.KV_decode(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local _d = M.KV_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.KV decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.key = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.key = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.key = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.key = val
            end
        elseif id == 2 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.value = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.value = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.value = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.value = val
            end
        else
            local _ebid = M.KV_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return c_grow_proto2.KV
function M.KV_decode_unsafe(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local _d = M.KV_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.KV decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.key = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.key = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.key = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.key = val
            end
        elseif id == 2 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.value = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.value = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.value = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.value = val
            end
        else
            local _ebid = M.KV_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.KV_decode_lazy(b) return pb.decode_lazy(M.KV_descriptor, b) end
---@param t c_grow_proto2.KV
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.KV_text(t, opts) return pb.text.encode(M.KV_descriptor, t, opts) end
---@param t c_grow_proto2.KV
---@return boolean
function M.KV_has_key(t) return t.key ~= nil end
---@param t c_grow_proto2.KV
function M.KV_clear_key(t) t.key = nil end
---@param t c_grow_proto2.KV
---@return boolean
function M.KV_has_value(t) return t.value ~= nil end
---@param t c_grow_proto2.KV
function M.KV_clear_value(t) t.value = nil end

---@param t? c_grow_proto2.Holder
---@return c_grow_proto2.Holder
function M.Holder_new(t) return t or {} end

---@param t c_grow_proto2.Holder
---@return string
function M.Holder_encode(t)
    local encode_varint = wire.encode_varint
    local _d = M.Holder_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for c_grow_proto2.Holder, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 1: first
    v = t.first
    if v ~= nil or type(v) == 'cdata' then
        local _b = M.KV_encode(v)
        n = n + 1; out[n] = "\x0a"
        local _len = #_b
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = _b
    end
    -- field 2: entry
    v = t.entry
    if v ~= nil and #v > 0 then
        local _stag = "\x13"
        local _etag = "\x14"
        for _i = 1, #v do
            n = n + 1; out[n] = _stag
            n = n + 1; out[n] = M.Holder_Entry_encode(v[_i])
            n = n + 1; out[n] = _etag
        end
    end
    -- field 5: single
    v = t.single
    if v ~= nil or type(v) == 'cdata' then
        n = n + 1; out[n] = "\x2b"
        n = n + 1; out[n] = M.Holder_Single_encode(v)
        n = n + 1; out[n] = "\x2c"
    end
    -- field 8: last
    v = t.last
    if v ~= nil or type(v) == 'cdata' then
        local _b = M.KV_encode(v)
        n = n + 1; out[n] = "\x42"
        local _len = #_b
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = _b
    end
    local _exts = t._extensions
    if _exts ~= nil then
        local _ev
        -- extension 100: c_grow_proto2.ext_kv
        _ev = _exts["c_grow_proto2.ext_kv"]
        if _ev ~= nil then
            local _b = M.KV_encode(_ev)
            n = n + 1; out[n] = "\xa2\x06"
            local _len = #_b
            if _len < 128 then
                n = n + 1; out[n] = CHARS[_len]
            else
                n = n + 1; out[n] = encode_varint(_len)
            end
            n = n + 1; out[n] = _b
        end
        -- extension 101: c_grow_proto2.ext_kvs
        _ev = _exts["c_grow_proto2.ext_kvs"]
        if _ev ~= nil and #_ev > 0 then
            local _tag = "\xaa\x06"
            for _i = 1, #_ev do
                local _b = M.KV_encode(_ev[_i])
                n = n + 1; out[n] = _tag
                local _len = #_b
                if _len < 128 then
                    n = n + 1; out[n] = CHARS[_len]
                else
                    n = n + 1; out[n] = encode_varint(_len)
                end
                n = n + 1; out[n] = _b
            end
        end
        -- extension 102: c_grow_proto2.ext_blob
        _ev = _exts["c_grow_proto2.ext_blob"]
        if _ev ~= nil then
            n = n + 1; out[n] = "\xb2\x06"
            local _len = #_ev
            if _len < 128 then
                n = n + 1; out[n] = CHARS[_len]
            else
                n = n + 1; out[n] = encode_varint(_len)
            end
            n = n + 1; out[n] = _ev
        end
    end
    local _elist = M.Holder_descriptor.extensions_list
    if _elist ~= nil and #_elist > 3 then
        local _exts2 = t._extensions
        if _exts2 ~= nil then
            for _i = 4, #_elist do
                local _ext = _elist[_i]
                local _ev = _exts2[_ext.full_name]
                if _ev ~= nil then
                    pb.codec.encode_field(_ext, _ev, out, true)
                end
            end
            n = #out
        end
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return c_grow_proto2.Holder
function M.Holder_decode(buf, depth)
    local decode_len = wire.decode_len
    local decode_tag = wire.decode_tag
    local _d = M.Holder_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    local _n_entry = 0
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.first
            if prev == nil then
                result.first = M.KV_decode(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode(payload, depth + 1))
            end
        elseif id == 2 then
            local list = result.entry
            if list == nil then list = {}; result.entry = list end
            local payload
            payload, pos = pb.codec.decode_group(M.Holder_Entry_descriptor, buf, pos, 2, depth + 1)
            _n_entry = _n_entry + 1; list[_n_entry] = payload
        elseif id == 5 then
            local payload
            payload, pos = pb.codec.decode_group(M.Holder_Single_descriptor, buf, pos, 5, depth + 1)
            local prev = result.single
            if prev == nil then
                result.single = payload
            else
                pb.codec.merge_message(M.Holder_Single_descriptor, prev, payload)
            end
        elseif id == 8 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.last
            if prev == nil then
                result.last = M.KV_decode(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode(payload, depth + 1))
            end
        elseif id == 100 then
            local _payload
            _payload, pos = decode_len(buf, pos)
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            _e["c_grow_proto2.ext_kv"] = M.KV_decode(_payload, depth + 1)
        elseif id == 101 then
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            local _list = _e["c_grow_proto2.ext_kvs"]
            if _list == nil then _list = {}; _e["c_grow_proto2.ext_kvs"] = _list end
            local _payload
            _payload, pos = decode_len(buf, pos)
            _list[#_list + 1] = M.KV_decode(_payload, depth + 1)
        elseif id == 102 then
            local _val
            _val, pos = wire.decode_bytes(buf, pos)
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            _e["c_grow_proto2.ext_blob"] = _val
        else
            local _ebid = M.Holder_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return c_grow_proto2.Holder
function M.Holder_decode_unsafe(buf, depth)
    local decode_len = wire.decode_len
    local decode_tag = wire.decode_tag
    local _d = M.Holder_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    local _n_entry = 0
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.first
            if prev == nil then
                result.first = M.KV_decode_unsafe(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode_unsafe(payload, depth + 1))
            end
        elseif id == 2 then
            local list = result.entry
            if list == nil then list = {}; result.entry = list end
            local payload
            payload, pos = pb.codec.decode_group(M.Holder_Entry_descriptor, buf, pos, 2, depth + 1)
            _n_entry = _n_entry + 1; list[_n_entry] = payload
        elseif id == 5 then
            local payload
            payload, pos = pb.codec.decode_group(M.Holder_Single_descriptor, buf, pos, 5, depth + 1)
            local prev = result.single
            if prev == nil then
                result.single = payload
            else
                pb.codec.merge_message(M.Holder_Single_descriptor, prev, payload)
            end
        elseif id == 8 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.last
            if prev == nil then
                result.last = M.KV_decode_unsafe(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode_unsafe(payload, depth + 1))
            end
        elseif id == 100 then
            local _payload
            _payload, pos = decode_len(buf, pos)
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            _e["c_grow_proto2.ext_kv"] = M.KV_decode_unsafe(_payload, depth + 1)
        elseif id == 101 then
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            local _list = _e["c_grow_proto2.ext_kvs"]
            if _list == nil then _list = {}; _e["c_grow_proto2.ext_kvs"] = _list end
            local _payload
            _payload, pos = decode_len(buf, pos)
            _list[#_list + 1] = M.KV_decode_unsafe(_payload, depth + 1)
        elseif id == 102 then
            local _val
            _val, pos = wire.decode_bytes(buf, pos)
            local _e = result._extensions
            if _e == nil then _e = {}; result._extensions = _e end
            _e["c_grow_proto2.ext_blob"] = _val
        else
            local _ebid = M.Holder_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.Holder_decode_lazy(b) return pb.decode_lazy(M.Holder_descriptor, b) end
---@param t c_grow_proto2.Holder
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_text(t, opts) return pb.text.encode(M.Holder_descriptor, t, opts) end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_first(t) return t.first ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_first(t) t.first = nil end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_single(t) return t.single ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_single(t) t.single = nil end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_last(t) return t.last ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_last(t) t.last = nil end

---@param t? c_grow_proto2.Holder.Entry
---@return c_grow_proto2.Holder.Entry
function M.Holder_Entry_new(t) return t or {} end

---@param t c_grow_proto2.Holder.Entry
---@return string
function M.Holder_Entry_encode(t)
    local encode_varint = wire.encode_varint
    local _d = M.Holder_Entry_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for c_grow_proto2.Holder.Entry, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 3: blob
    v = t.blob
    if v ~= nil then
        n = n + 1; out[n] = "\x1a"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    -- field 4: kv
    v = t.kv
    if v ~= nil or type(v) == 'cdata' then
        local _b = M.KV_encode(v)
        n = n + 1; out[n] = "\x22"
        local _len = #_b
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = _b
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return c_grow_proto2.Holder.Entry
function M.Holder_Entry_decode(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local _d = M.Holder_Entry_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder.Entry decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 3 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.blob = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.blob = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.blob = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.blob = val
            end
        elseif id == 4 then
            local payload
            payload, pos = wire.decode_len(buf, pos)
            local prev = result.kv
            if prev == nil then
                result.kv = M.KV_decode(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode(payload, depth + 1))
            end
        else
            local _ebid = M.Holder_Entry_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return c_grow_proto2.Holder.Entry
function M.Holder_Entry_decode_unsafe(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local _d = M.Holder_Entry_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder.Entry decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 3 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.blob = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.blob = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.blob = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.blob = val
            end
        elseif id == 4 then
            local payload
            payload, pos = wire.decode_len(buf, pos)
            local prev = result.kv
            if prev == nil then
                result.kv = M.KV_decode_unsafe(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode_unsafe(payload, depth + 1))
            end
        else
            local _ebid = M.Holder_Entry_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.Holder_Entry_decode_lazy(b) return pb.decode_lazy(M.Holder_Entry_descriptor, b) end
---@param t c_grow_proto2.Holder.Entry
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_Entry_text(t, opts) return pb.text.encode(M.Holder_Entry_descriptor, t, opts) end
---@param t c_grow_proto2.Holder.Entry
---@return boolean
function M.Holder_Entry_has_blob(t) return t.blob ~= nil end
---@param t c_grow_proto2.Holder.Entry
function M.Holder_Entry_clear_blob(t) t.blob = nil end
---@param t c_grow_proto2.Holder.Entry
---@return boolean
function M.Holder_Entry_has_kv(t) return t.kv ~= nil end
---@param t c_grow_proto2.Holder.Entry
function M.Holder_Entry_clear_kv(t) t.kv = nil end

---@param t? c_grow_proto2.Holder.Single
---@return c_grow_proto2.Holder.Single
function M.Holder_Single_new(t) return t or {} end

---@param t c_grow_proto2.Holder.Single
---@return string
function M.Holder_Single_encode(t)
    local encode_varint = wire.encode_varint
    local _d = M.Holder_Single_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for c_grow_proto2.Holder.Single, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 6: kv
    v = t.kv
    if v ~= nil or type(v) == 'cdata' then
        local _b = M.KV_encode(v)
        n = n + 1; out[n] = "\x32"
        local _len = #_b
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = _b
    end
    -- field 7: kvs
    v = t.kvs
    if v ~= nil and #v > 0 then
        local _tag = "\x3a"
        for _i = 1, #v do
            local _b = M.KV_encode(v[_i])
            n = n + 1; out[n] = _tag
            local _len = #_b
            if _len < 128 then
                n = n + 1; out[n] = CHARS[_len]
            else
                n = n + 1; out[n] = encode_varint(_len)
            end
            n = n + 1; out[n] = _b
        end
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return c_grow_proto2.Holder.Single
function M.Holder_Single_decode(buf, depth)
    local decode_len = wire.decode_len
    local decode_tag = wire.decode_tag
    local _d = M.Holder_Single_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder.Single decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    local _n_kvs = 0
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 6 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.kv
            if prev == nil then
                result.kv = M.KV_decode(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode(payload, depth + 1))
            end
        elseif id == 7 then
            local list = result.kvs
            if list == nil then list = {}; result.kvs = list end
            local payload
            payload, pos = decode_len(buf, pos)
            _n_kvs = _n_kvs + 1; list[_n_kvs] = M.KV_decode(payload, depth + 1)
        else
            local _ebid = M.Holder_Single_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return c_grow_proto2.Holder.Single
function M.Holder_Single_decode_unsafe(buf, depth)
    local decode_len = wire.decode_len
    local decode_tag = wire.decode_tag
    local _d = M.Holder_Single_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for c_grow_proto2.Holder.Single decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    local _n_kvs = 0
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 6 then
            local payload
            payload, pos = decode_len(buf, pos)
            local prev = result.kv
            if prev == nil then
                result.kv = M.KV_decode_unsafe(payload, depth + 1)
            else
                pb.codec.merge_message(M.KV_descriptor, prev, M.KV_decode_unsafe(payload, depth + 1))
            end
        elseif id == 7 then
            local list = result.kvs
            if list == nil then list = {}; result.kvs = list end
            local payload
            payload, pos = decode_len(buf, pos)
            _n_kvs = _n_kvs + 1; list[_n_kvs] = M.KV_decode_unsafe(payload, depth + 1)
        else
            local _ebid = M.Holder_Single_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.Holder_Single_decode_lazy(b) return pb.decode_lazy(M.Holder_Single_descriptor, b) end
---@param t c_grow_proto2.Holder.Single
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_Single_text(t, opts) return pb.text.encode(M.Holder_Single_descriptor, t, opts) end
---@param t c_grow_proto2.Holder.Single
---@return boolean
function M.Holder_Single_has_kv(t) return t.kv ~= nil end
---@param t c_grow_proto2.Holder.Single
function M.Holder_Single_clear_kv(t) t.kv = nil end

-- Extension: c_grow_proto2.ext_kv extends c_grow_proto2.Holder (tag 100)
pb.register_extension(M.Holder_descriptor, {name="ext_kv", full_name="c_grow_proto2.ext_kv", id=100, kind='message', message=M.KV_descriptor, optional=true})
-- Extension: c_grow_proto2.ext_kvs extends c_grow_proto2.Holder (tag 101)
pb.register_extension(M.Holder_descriptor, {name="ext_kvs", full_name="c_grow_proto2.ext_kvs", id=101, kind='message', message=M.KV_descriptor, repeated=true})
-- Extension: c_grow_proto2.ext_blob extends c_grow_proto2.Holder (tag 102)
pb.register_extension(M.Holder_descriptor, {name="ext_blob", full_name="c_grow_proto2.ext_blob", id=102, kind='scalar', proto_type="bytes", optional=true})

return M
