-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: kv.proto
-- syntax: proto3
-- package: kv

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/kv"}

-- Enum: kv.Kind
M.Kind_descriptor = pb.enum("kv.Kind", {
    KIND_UNSPECIFIED = 0,
    KIND_PERSON = 1,
    KIND_COMPANY = 2,
})
M.Kind = M.Kind_descriptor.by_name

-- Pre-declare message descriptors so cross-references resolve.
M.KeyValue_descriptor = {name = "kv.KeyValue"}
M.Address_descriptor = {name = "kv.Address"}
M.Phone_descriptor = {name = "kv.Phone"}
M.Label_descriptor = {name = "kv.Label"}
M.Record_descriptor = {name = "kv.Record"}
M.Mixed_descriptor = {name = "kv.Mixed"}

-- Message: kv.KeyValue
M.KeyValue_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="bytes"},
    {name="create_revision", id=2, kind='scalar', proto_type="int64"},
    {name="mod_revision", id=3, kind='scalar', proto_type="int64"},
    {name="version", id=4, kind='scalar', proto_type="int64"},
    {name="value", id=5, kind='scalar', proto_type="bytes"},
    {name="lease", id=6, kind='scalar', proto_type="int64"},
}
pb.finalize_message(M.KeyValue_descriptor)
M.KeyValue_fields = pb.field_names({
    key = "key",
    create_revision = "create_revision",
    mod_revision = "mod_revision",
    version = "version",
    value = "value",
    lease = "lease",
})

-- Message: kv.Address
M.Address_descriptor.fields = {
    {name="street", id=1, kind='scalar', proto_type="string"},
    {name="city", id=2, kind='scalar', proto_type="string"},
    {name="zip", id=4, kind='scalar', proto_type="uint32"},
}
pb.finalize_message(M.Address_descriptor)
M.Address_fields = pb.field_names({
    street = "street",
    city = "city",
    zip = "zip",
})

-- Message: kv.Phone
M.Phone_descriptor.fields = {
    {name="number", id=1, kind='scalar', proto_type="string"},
    {name="kind", id=2, kind='enum', enum=M.Kind_descriptor},
}
pb.finalize_message(M.Phone_descriptor)
M.Phone_fields = pb.field_names({
    number = "number",
    kind = "kind",
})

-- Message: kv.Label
M.Label_descriptor.fields = {
    {name="text", id=1, kind='scalar', proto_type="string"},
    {name="weight", id=9, kind='scalar', proto_type="int32"},
}
pb.finalize_message(M.Label_descriptor)
M.Label_fields = pb.field_names({
    text = "text",
    weight = "weight",
})

-- Message: kv.Record
M.Record_descriptor.fields = {
    {name="id", id=1, kind='scalar', proto_type="uint64"},
    {name="name", id=2, kind='scalar', proto_type="string"},
    {name="address", id=3, kind='message', message=M.Address_descriptor},
    {name="phones", id=4, kind='message', message=M.Phone_descriptor, repeated=true},
    {name="scores", id=5, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="int32"}},
    {name="nickname", id=6, kind='scalar', proto_type="string", optional=true},
    {name="kind", id=7, kind='enum', enum=M.Kind_descriptor},
    {name="created_at", id=8, kind='message', message=pb.wkt.Timestamp_descriptor},
    {name="owner", id=9, kind='scalar', proto_type="string"},
    {name="token", id=10, kind='scalar', proto_type="bytes"},
    {name="payload", id=11, kind='scalar', proto_type="bytes"},
    {name="weight", id=12, kind='scalar', proto_type="double"},
    {name="active", id=13, kind='scalar', proto_type="bool"},
    {name="label", id=20, kind='message', message=M.Label_descriptor},
    {name="balance", id=100, kind='scalar', proto_type="sint64"},
}
pb.finalize_message(M.Record_descriptor)
M.Record_fields = pb.field_names({
    id = "id",
    name = "name",
    address = "address",
    phones = "phones",
    scores = "scores",
    nickname = "nickname",
    kind = "kind",
    created_at = "created_at",
    owner = "owner",
    token = "token",
    payload = "payload",
    weight = "weight",
    active = "active",
    label = "label",
    balance = "balance",
})

-- Message: kv.Mixed
M.Mixed_descriptor.fields = {
    {name="rank", id=5, kind='scalar', proto_type="int32"},
    {name="counts", id=3, kind='scalar', proto_type="sint32", repeated=true, packed=true},
    {name="id", id=1, kind='scalar', proto_type="string"},
    {name="contacts", id=4, kind='map', key={kind='scalar', proto_type="int64"}, value={kind='message', message=M.Phone_descriptor}},
    {name="tags", id=2, kind='scalar', proto_type="string", repeated=true},
    {name="seen", id=6, kind='message', message=pb.wkt.Timestamp_descriptor, repeated=true},
    {name="child", id=8, kind='message', message=M.Mixed_descriptor},
    {name="kinds", id=7, kind='enum', enum=M.Kind_descriptor, repeated=true, packed=true},
    {name="text", id=10, kind='scalar', proto_type="string", oneof="pick"},
    {name="code", id=9, kind='scalar', proto_type="int64", oneof="pick"},
}
M.Mixed_descriptor.oneofs = {
    pick = {"text", "code"},
}
pb.finalize_message(M.Mixed_descriptor)
M.Mixed_fields = pb.field_names({
    rank = "rank",
    counts = "counts",
    id = "id",
    contacts = "contacts",
    tags = "tags",
    seen = "seen",
    child = "child",
    kinds = "kinds",
    text = "text",
    code = "code",
})
M.Mixed_oneofs = pb.field_names({
    pick = "pick",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@alias kv.Kind integer

--- The key/value record of an etcd-compatible store — field for field the
--- shape of etcd's mvccpb.KeyValue.
---@class kv.KeyValue
---@field key string
---@field create_revision integer
---@field mod_revision integer
---@field version integer
---@field value string
---@field lease integer

--- Dense enough for the array representation; field 3 is a hole.
---@class kv.Address
---@field street string
---@field city string
---@field zip integer

---@class kv.Phone
---@field number string
---@field kind kv.Kind

--- Too sparse for the array representation: field number 9 over two
--- fields would leave the array mostly holes.
---@class kv.Label
---@field text string
---@field weight integer

--- One field per tuple representation: nested message (map, array or raw
--- bytes, per the column type), repeated message, map, explicit-optional
--- scalar, enum, Timestamp, uuid carried as string and as bytes, and
--- sparse field numbers.
---@class kv.Record
---@field id integer
---@field name string
---@field address kv.Address
---@field phones kv.Phone[]
---@field scores table<string, integer>
---@field nickname? string
---@field kind kv.Kind
---@field created_at google.protobuf.Timestamp
---@field owner string
---@field token string
---@field payload string
---@field weight number
---@field active boolean
---@field label kv.Label
---@field balance integer

--- Declared out of field-number order, with the repeated and map shapes
--- Record lacks: packed and unpacked scalars, a map with message values,
--- repeated Timestamps, a oneof and a recursive field. The descriptor
--- codec writes fields in declaration order; the tuple bridge writes them
--- in field-number order at every level.
---@class kv.Mixed
---@field rank integer
---@field counts integer[]
---@field id string
---@field contacts table<integer, kv.Phone>
---@field tags string[]
---@field seen google.protobuf.Timestamp[]
---@field child kv.Mixed
---@field kinds kv.Kind[]
---@field text? string
---@field code? integer

---@param t? kv.KeyValue
---@return kv.KeyValue
function M.KeyValue_new(t) return t or {} end
---@param t kv.KeyValue
---@return string
function M.KeyValue_encode(t) return pb.encode(M.KeyValue_descriptor, t) end
---@param b string
---@return kv.KeyValue
function M.KeyValue_decode(b) return pb.decode(M.KeyValue_descriptor, b) end
function M.KeyValue_decode_unsafe(b) return pb.decode_unsafe(M.KeyValue_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.KeyValue_decode_lazy(b) return pb.decode_lazy(M.KeyValue_descriptor, b) end
---@param t kv.KeyValue
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.KeyValue_text(t, opts) return pb.text.encode(M.KeyValue_descriptor, t, opts) end

---@param t? kv.Address
---@return kv.Address
function M.Address_new(t) return t or {} end
---@param t kv.Address
---@return string
function M.Address_encode(t) return pb.encode(M.Address_descriptor, t) end
---@param b string
---@return kv.Address
function M.Address_decode(b) return pb.decode(M.Address_descriptor, b) end
function M.Address_decode_unsafe(b) return pb.decode_unsafe(M.Address_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Address_decode_lazy(b) return pb.decode_lazy(M.Address_descriptor, b) end
---@param t kv.Address
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Address_text(t, opts) return pb.text.encode(M.Address_descriptor, t, opts) end

---@param t? kv.Phone
---@return kv.Phone
function M.Phone_new(t) return t or {} end
---@param t kv.Phone
---@return string
function M.Phone_encode(t) return pb.encode(M.Phone_descriptor, t) end
---@param b string
---@return kv.Phone
function M.Phone_decode(b) return pb.decode(M.Phone_descriptor, b) end
function M.Phone_decode_unsafe(b) return pb.decode_unsafe(M.Phone_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Phone_decode_lazy(b) return pb.decode_lazy(M.Phone_descriptor, b) end
---@param t kv.Phone
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Phone_text(t, opts) return pb.text.encode(M.Phone_descriptor, t, opts) end

---@param t? kv.Label
---@return kv.Label
function M.Label_new(t) return t or {} end
---@param t kv.Label
---@return string
function M.Label_encode(t) return pb.encode(M.Label_descriptor, t) end
---@param b string
---@return kv.Label
function M.Label_decode(b) return pb.decode(M.Label_descriptor, b) end
function M.Label_decode_unsafe(b) return pb.decode_unsafe(M.Label_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Label_decode_lazy(b) return pb.decode_lazy(M.Label_descriptor, b) end
---@param t kv.Label
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Label_text(t, opts) return pb.text.encode(M.Label_descriptor, t, opts) end

---@param t? kv.Record
---@return kv.Record
function M.Record_new(t) return t or {} end
---@param t kv.Record
---@return string
function M.Record_encode(t) return pb.encode(M.Record_descriptor, t) end
---@param b string
---@return kv.Record
function M.Record_decode(b) return pb.decode(M.Record_descriptor, b) end
function M.Record_decode_unsafe(b) return pb.decode_unsafe(M.Record_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Record_decode_lazy(b) return pb.decode_lazy(M.Record_descriptor, b) end
---@param t kv.Record
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Record_text(t, opts) return pb.text.encode(M.Record_descriptor, t, opts) end
---@param t kv.Record
---@return boolean
function M.Record_has_nickname(t) return t.nickname ~= nil end
---@param t kv.Record
function M.Record_clear_nickname(t) t.nickname = nil end

---@param t? kv.Mixed
---@return kv.Mixed
function M.Mixed_new(t) return t or {} end
---@param t kv.Mixed
---@return string
function M.Mixed_encode(t) return pb.encode(M.Mixed_descriptor, t) end
---@param b string
---@return kv.Mixed
function M.Mixed_decode(b) return pb.decode(M.Mixed_descriptor, b) end
function M.Mixed_decode_unsafe(b) return pb.decode_unsafe(M.Mixed_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Mixed_decode_lazy(b) return pb.decode_lazy(M.Mixed_descriptor, b) end
---@param t kv.Mixed
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Mixed_text(t, opts) return pb.text.encode(M.Mixed_descriptor, t, opts) end

-- Serialized FileDescriptorProto of kv.proto (source_code_info
-- stripped), registered with pb.descriptors for server reflection.
M._file_descriptor = table.concat({
    "\x0a\x08kv.proto\x12\x02kv\x1a\x1fgoogle/protobuf/timestamp.proto\"",
    "\xae\x01\x0a\x08KeyValue\x12\x10\x0a\x03key\x18\x01 \x01(\x0cR\x03key\x12'\x0a\x0fcreate_revisio",
    "n\x18\x02 \x01(\x03R\x0ecreateRevision\x12!\x0a\x0cmod_revision\x18\x03 \x01(\x03R\x0bm",
    "odRevision\x12\x18\x0a\x07version\x18\x04 \x01(\x03R\x07version\x12\x14\x0a\x05value\x18\x05 ",
    "\x01(\x0cR\x05value\x12\x14\x0a\x05lease\x18\x06 \x01(\x03R\x05lease\"G\x0a\x07Address\x12\x16\x0a\x06s",
    "treet\x18\x01 \x01(\x09R\x06street\x12\x12\x0a\x04city\x18\x02 \x01(\x09R\x04city\x12\x10\x0a\x03zip\x18\x04",
    " \x01(\x0dR\x03zip\"=\x0a\x05Phone\x12\x16\x0a\x06number\x18\x01 \x01(\x09R\x06number\x12\x1c\x0a\x04ki",
    "nd\x18\x02 \x01(\x0e2\x08.kv.KindR\x04kind\"3\x0a\x05Label\x12\x12\x0a\x04text\x18\x01 \x01(\x09R",
    "\x04text\x12\x16\x0a\x06weight\x18\x09 \x01(\x05R\x06weight\"\x99\x04\x0a\x06Record\x12\x0e\x0a\x02id\x18\x01",
    " \x01(\x04R\x02id\x12\x12\x0a\x04name\x18\x02 \x01(\x09R\x04name\x12%\x0a\x07address\x18\x03 \x01(\x0b2\x0b.",
    "kv.AddressR\x07address\x12!\x0a\x06phones\x18\x04 \x03(\x0b2\x09.kv.PhoneR\x06",
    "phones\x12.\x0a\x06scores\x18\x05 \x03(\x0b2\x16.kv.Record.ScoresEntryR\x06",
    "scores\x12\x1f\x0a\x08nickname\x18\x06 \x01(\x09H\x00R\x08nickname\x88\x01\x01\x12\x1c\x0a\x04kind\x18",
    "\x07 \x01(\x0e2\x08.kv.KindR\x04kind\x129\x0a\x0acreated_at\x18\x08 \x01(\x0b2\x1a.goog",
    "le.protobuf.TimestampR\x09createdAt\x12\x14\x0a\x05owner\x18\x09 \x01(\x09R",
    "\x05owner\x12\x14\x0a\x05token\x18\x0a \x01(\x0cR\x05token\x12\x18\x0a\x07payload\x18\x0b \x01(\x0cR\x07p",
    "ayload\x12\x16\x0a\x06weight\x18\x0c \x01(\x01R\x06weight\x12\x16\x0a\x06active\x18\x0d \x01(\x08R\x06",
    "active\x12\x1f\x0a\x05label\x18\x14 \x01(\x0b2\x09.kv.LabelR\x05label\x12\x18\x0a\x07balan",
    "ce\x18d \x01(\x12R\x07balance\x1a9\x0a\x0bScoresEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03k",
    "ey\x12\x14\x0a\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x0b\x0a\x09_nickname\"\xf9\x02\x0a\x05Mi",
    "xed\x12\x12\x0a\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x16\x0a\x06counts\x18\x03 \x03(\x11R\x06counts\x12",
    "\x0e\x0a\x02id\x18\x01 \x01(\x09R\x02id\x123\x0a\x08contacts\x18\x04 \x03(\x0b2\x17.kv.Mixed.Con",
    "tactsEntryR\x08contacts\x12\x12\x0a\x04tags\x18\x02 \x03(\x09R\x04tags\x12.\x0a\x04seen",
    "\x18\x06 \x03(\x0b2\x1a.google.protobuf.TimestampR\x04seen\x12\x1f\x0a\x05chil",
    "d\x18\x08 \x01(\x0b2\x09.kv.MixedR\x05child\x12\x1e\x0a\x05kinds\x18\x07 \x03(\x0e2\x08.kv.Ki",
    "ndR\x05kinds\x12\x14\x0a\x04text\x18\x0a \x01(\x09H\x00R\x04text\x12\x14\x0a\x04code\x18\x09 \x01(\x03H\x00R",
    "\x04code\x1aF\x0a\x0dContactsEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x03R\x03key\x12\x1f\x0a\x05valu",
    "e\x18\x02 \x01(\x0b2\x09.kv.PhoneR\x05value:\x028\x01B\x06\x0a\x04pick*?\x0a\x04Kind\x12\x14\x0a",
    "\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\x0a\x0bKIND_PERSON\x10\x01\x12\x10\x0a\x0cKIND_COM",
    "PANY\x10\x02b\x06proto3",
})
pb.descriptors.register(M._file_descriptor)

return M
