-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: kv.proto
-- syntax: proto3
-- package: kv

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/kv"}

-- Enum: kv.Kind
M.Kind_descriptor = pb.enum("kv.Kind", {
    KIND_UNSPECIFIED = 0,
    KIND_PERSON = 1,
    KIND_COMPANY = 2,
})
M.Kind = M.Kind_descriptor.by_name

-- Pre-declare message descriptors so cross-references resolve.
M.KeyValue_descriptor = {name = "kv.KeyValue"}
M.Address_descriptor = {name = "kv.Address"}
M.Phone_descriptor = {name = "kv.Phone"}
M.Label_descriptor = {name = "kv.Label"}
M.Record_descriptor = {name = "kv.Record"}

-- Message: kv.KeyValue
M.KeyValue_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="bytes"},
    {name="create_revision", id=2, kind='scalar', proto_type="int64"},
    {name="mod_revision", id=3, kind='scalar', proto_type="int64"},
    {name="version", id=4, kind='scalar', proto_type="int64"},
    {name="value", id=5, kind='scalar', proto_type="bytes"},
    {name="lease", id=6, kind='scalar', proto_type="int64"},
}
pb.finalize_message(M.KeyValue_descriptor)
M.KeyValue_fields = pb.field_names({
    key = "key",
    create_revision = "create_revision",
    mod_revision = "mod_revision",
    version = "version",
    value = "value",
    lease = "lease",
})

-- Message: kv.Address
M.Address_descriptor.fields = {
    {name="street", id=1, kind='scalar', proto_type="string"},
    {name="city", id=2, kind='scalar', proto_type="string"},
    {name="zip", id=4, kind='scalar', proto_type="uint32"},
}
pb.finalize_message(M.Address_descriptor)
M.Address_fields = pb.field_names({
    street = "street",
    city = "city",
    zip = "zip",
})

-- Message: kv.Phone
M.Phone_descriptor.fields = {
    {name="number", id=1, kind='scalar', proto_type="string"},
    {name="kind", id=2, kind='enum', enum=M.Kind_descriptor},
}
pb.finalize_message(M.Phone_descriptor)
M.Phone_fields = pb.field_names({
    number = "number",
    kind = "kind",
})

-- Message: kv.Label
M.Label_descriptor.fields = {
    {name="text", id=1, kind='scalar', proto_type="string"},
    {name="weight", id=9, kind='scalar', proto_type="int32"},
}
pb.finalize_message(M.Label_descriptor)
M.Label_fields = pb.field_names({
    text = "text",
    weight = "weight",
})

-- Message: kv.Record
M.Record_descriptor.fields = {
    {name="id", id=1, kind='scalar', proto_type="uint64"},
    {name="name", id=2, kind='scalar', proto_type="string"},
    {name="address", id=3, kind='message', message=M.Address_descriptor},
    {name="phones", id=4, kind='message', message=M.Phone_descriptor, repeated=true},
    {name="scores", id=5, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="int32"}},
    {name="nickname", id=6, kind='scalar', proto_type="string", optional=true},
    {name="kind", id=7, kind='enum', enum=M.Kind_descriptor},
    {name="created_at", id=8, kind='message', message=pb.wkt.Timestamp_descriptor},
    {name="owner", id=9, kind='scalar', proto_type="string"},
    {name="token", id=10, kind='scalar', proto_type="bytes"},
    {name="payload", id=11, kind='scalar', proto_type="bytes"},
    {name="weight", id=12, kind='scalar', proto_type="double"},
    {name="active", id=13, kind='scalar', proto_type="bool"},
    {name="label", id=20, kind='message', message=M.Label_descriptor},
    {name="balance", id=100, kind='scalar', proto_type="sint64"},
}
pb.finalize_message(M.Record_descriptor)
M.Record_fields = pb.field_names({
    id = "id",
    name = "name",
    address = "address",
    phones = "phones",
    scores = "scores",
    nickname = "nickname",
    kind = "kind",
    created_at = "created_at",
    owner = "owner",
    token = "token",
    payload = "payload",
    weight = "weight",
    active = "active",
    label = "label",
    balance = "balance",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@alias kv.Kind integer

--- The key/value record of an etcd-compatible store — field for field the
--- shape of etcd's mvccpb.KeyValue.
---@class kv.KeyValue
---@field key string
---@field create_revision integer
---@field mod_revision integer
---@field version integer
---@field value string
---@field lease integer

--- Dense enough for the array representation; field 3 is a hole.
---@class kv.Address
---@field street string
---@field city string
---@field zip integer

---@class kv.Phone
---@field number string
---@field kind kv.Kind

--- Too sparse for the array representation: field number 9 over two
--- fields would leave the array mostly holes.
---@class kv.Label
---@field text string
---@field weight integer

--- One field per tuple representation: nested message (map, array or raw
--- bytes, per the column type), repeated message, map, explicit-optional
--- scalar, enum, Timestamp, uuid carried as string and as bytes, and
--- sparse field numbers.
---@class kv.Record
---@field id integer
---@field name string
---@field address kv.Address
---@field phones kv.Phone[]
---@field scores table<string, integer>
---@field nickname? string
---@field kind kv.Kind
---@field created_at google.protobuf.Timestamp
---@field owner string
---@field token string
---@field payload string
---@field weight number
---@field active boolean
---@field label kv.Label
---@field balance integer

---@param t? kv.KeyValue
---@return kv.KeyValue
function M.KeyValue_new(t) return t or {} end
---@param t kv.KeyValue
---@return string
function M.KeyValue_encode(t) return pb.encode(M.KeyValue_descriptor, t) end
---@param b string
---@return kv.KeyValue
function M.KeyValue_decode(b) return pb.decode(M.KeyValue_descriptor, b) end
function M.KeyValue_decode_unsafe(b) return pb.decode_unsafe(M.KeyValue_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.KeyValue_decode_lazy(b) return pb.decode_lazy(M.KeyValue_descriptor, b) end
---@param t kv.KeyValue
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.KeyValue_text(t, opts) return pb.text.encode(M.KeyValue_descriptor, t, opts) end

---@param t? kv.Address
---@return kv.Address
function M.Address_new(t) return t or {} end
---@param t kv.Address
---@return string
function M.Address_encode(t) return pb.encode(M.Address_descriptor, t) end
---@param b string
---@return kv.Address
function M.Address_decode(b) return pb.decode(M.Address_descriptor, b) end
function M.Address_decode_unsafe(b) return pb.decode_unsafe(M.Address_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Address_decode_lazy(b) return pb.decode_lazy(M.Address_descriptor, b) end
---@param t kv.Address
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Address_text(t, opts) return pb.text.encode(M.Address_descriptor, t, opts) end

---@param t? kv.Phone
---@return kv.Phone
function M.Phone_new(t) return t or {} end
---@param t kv.Phone
---@return string
function M.Phone_encode(t) return pb.encode(M.Phone_descriptor, t) end
---@param b string
---@return kv.Phone
function M.Phone_decode(b) return pb.decode(M.Phone_descriptor, b) end
function M.Phone_decode_unsafe(b) return pb.decode_unsafe(M.Phone_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Phone_decode_lazy(b) return pb.decode_lazy(M.Phone_descriptor, b) end
---@param t kv.Phone
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Phone_text(t, opts) return pb.text.encode(M.Phone_descriptor, t, opts) end

---@param t? kv.Label
---@return kv.Label
function M.Label_new(t) return t or {} end
---@param t kv.Label
---@return string
function M.Label_encode(t) return pb.encode(M.Label_descriptor, t) end
---@param b string
---@return kv.Label
function M.Label_decode(b) return pb.decode(M.Label_descriptor, b) end
function M.Label_decode_unsafe(b) return pb.decode_unsafe(M.Label_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Label_decode_lazy(b) return pb.decode_lazy(M.Label_descriptor, b) end
---@param t kv.Label
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Label_text(t, opts) return pb.text.encode(M.Label_descriptor, t, opts) end

---@param t? kv.Record
---@return kv.Record
function M.Record_new(t) return t or {} end
---@param t kv.Record
---@return string
function M.Record_encode(t) return pb.encode(M.Record_descriptor, t) end
---@param b string
---@return kv.Record
function M.Record_decode(b) return pb.decode(M.Record_descriptor, b) end
function M.Record_decode_unsafe(b) return pb.decode_unsafe(M.Record_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Record_decode_lazy(b) return pb.decode_lazy(M.Record_descriptor, b) end
---@param t kv.Record
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Record_text(t, opts) return pb.text.encode(M.Record_descriptor, t, opts) end
---@param t kv.Record
---@return boolean
function M.Record_has_nickname(t) return t.nickname ~= nil end
---@param t kv.Record
function M.Record_clear_nickname(t) t.nickname = nil end

return M
