-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: connectrpc/conformance/v1/server_compat.proto
-- syntax: proto3
-- package: connectrpc.conformance.v1

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')
local _imp_full_connectrpc_conformance_v1_config_pb = require("full.connectrpc.conformance.v1.config_pb")

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/connectrpc/conformance/v1/server_compat"}

-- Pre-declare message descriptors so cross-references resolve.
M.ServerCompatRequest_descriptor = {name = "connectrpc.conformance.v1.ServerCompatRequest"}
M.ServerCompatResponse_descriptor = {name = "connectrpc.conformance.v1.ServerCompatResponse"}

-- Message: connectrpc.conformance.v1.ServerCompatRequest
M.ServerCompatRequest_descriptor.fields = {
    {name="protocol", id=1, kind='enum', enum=_imp_full_connectrpc_conformance_v1_config_pb.Protocol_descriptor},
    {name="http_version", id=2, kind='enum', enum=_imp_full_connectrpc_conformance_v1_config_pb.HTTPVersion_descriptor},
    {name="use_tls", id=4, kind='scalar', proto_type="bool"},
    {name="client_tls_cert", id=5, kind='scalar', proto_type="bytes"},
    {name="message_receive_limit", id=6, kind='scalar', proto_type="uint32"},
    {name="server_creds", id=7, kind='message', message=_imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_descriptor},
}
pb.finalize_message(M.ServerCompatRequest_descriptor)
M.ServerCompatRequest_fields = pb.field_names({
    protocol = "protocol",
    http_version = "http_version",
    use_tls = "use_tls",
    client_tls_cert = "client_tls_cert",
    message_receive_limit = "message_receive_limit",
    server_creds = "server_creds",
})

-- Message: connectrpc.conformance.v1.ServerCompatResponse
M.ServerCompatResponse_descriptor.fields = {
    {name="host", id=1, kind='scalar', proto_type="string"},
    {name="port", id=2, kind='scalar', proto_type="uint32"},
    {name="pem_cert", id=3, kind='scalar', proto_type="bytes"},
}
pb.finalize_message(M.ServerCompatResponse_descriptor)
M.ServerCompatResponse_fields = pb.field_names({
    host = "host",
    port = "port",
    pem_cert = "pem_cert",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
--- Describes one configuration for an RPC server. The server is
--- expected to expose the connectrpc.conformance.v1.ConformanceService
--- RPC service. The configuration does not include a port. The
--- process should pick an available port, which is typically
--- done by using port zero (0) when creating a network listener
--- so that the OS selects an available ephemeral port.
---
--- These properties are read from stdin. Once the server is
--- listening, details about the server, in the form of a
--- ServerCompatResponse, are written to stdout.
---
--- Each test process is expected to start only one RPC server.
--- When testing multiple configurations, multiple test processes
--- will be started, each with different properties.
---@class connectrpc.conformance.v1.ServerCompatRequest
---@field protocol connectrpc.conformance.v1.Protocol @ Signals to the server that it must support at least this protocol. Note that it is fine to support others. For example if `PROTOCOL_CONNECT` is specified, the server _must_ support at least Connect, but _may_ also support gRPC or gRPC-web.
---@field http_version connectrpc.conformance.v1.HTTPVersion @ Signals to the server the minimum HTTP version to support. As with `protocol`, it is fine to support other versions. For example, if `HTTP_VERSION_2` is specified, the server _must_ support HTTP/2, but _may_ also support HTTP/1.1 or HTTP/3.
---@field use_tls boolean @ If true, generate a certificate that clients will be configured to trust when connecting and return it in the `pem_cert` field of the `ServerCompatResponse`. The certificate can be any TLS certificate where the subject matches the value sent back in the `host` field of the `ServerCompatResponse`. Self-signed certificates (and `localhost` as the subject) are allowed. If false, the server should not use TLS and instead use a plain-text/unencrypted socket.
---@field client_tls_cert string @ If non-empty, the clients will use certificates to authenticate themselves. This value is a PEM-encoded cert that should be trusted by the server. When non-empty, the server should require that clients provide certificates and they should validate that the certificate presented is valid.  This will always be empty if use_tls is false.
---@field message_receive_limit integer @ If non-zero, indicates the maximum size in bytes for a message. If the client sends anything larger, the server should reject it.
---@field server_creds connectrpc.conformance.v1.TLSCreds @ If use_tls is true, this provides details for a self-signed TLS cert that the server may use.  The provided certificate is only good for loopback communication: it uses "localhost" and "127.0.0.1" as the IP and DNS names in the certificate's subject. If the server needs a different subject or the client is in an environment where configuring trust of a self-signed certificate is difficult or infeasible.  If the server implementation chooses to use these credentials, it must echo back the certificate in the ServerCompatResponse and should also leave the host field empty or explicitly set to "127.0.0.1".  If it chooses to use a different certificate and key, it must send back the corresponding certificate in the ServerCompatResponse.

--- The outcome of one ServerCompatRequest.
---@class connectrpc.conformance.v1.ServerCompatResponse
---@field host string @ The host where the server is running. This should usually be `127.0.0.1`, unless your program actually starts a remote server to which the client should connect.
---@field port integer @ The port where the server is listening.
---@field pem_cert string @ The TLS certificate, in PEM format, if `use_tls` was set to `true`. Clients will verify this certificate when connecting via TLS. If `use_tls` was set to `false`, this should always be empty.

---@param t? connectrpc.conformance.v1.ServerCompatRequest
---@return connectrpc.conformance.v1.ServerCompatRequest
function M.ServerCompatRequest_new(t) return t or {} end

---@param t connectrpc.conformance.v1.ServerCompatRequest
---@return string
function M.ServerCompatRequest_encode(t)
    local encode_int32 = wire.encode_int32
    local encode_varint = wire.encode_varint
    local _d = M.ServerCompatRequest_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for connectrpc.conformance.v1.ServerCompatRequest, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 1: protocol
    v = t.protocol
    if v ~= nil then
        local nv = v
        if type(v) == 'string' then
            nv = _imp_full_connectrpc_conformance_v1_config_pb.Protocol[v]
            if nv == nil then error("unknown enum value '" .. v .. "' for connectrpc.conformance.v1.Protocol", 0) end
        end
        if nv ~= 0 then
            n = n + 1; out[n] = "\x08"
            n = n + 1; out[n] = encode_int32(nv)
        end
    end
    -- field 2: http_version
    v = t.http_version
    if v ~= nil then
        local nv = v
        if type(v) == 'string' then
            nv = _imp_full_connectrpc_conformance_v1_config_pb.HTTPVersion[v]
            if nv == nil then error("unknown enum value '" .. v .. "' for connectrpc.conformance.v1.HTTPVersion", 0) end
        end
        if nv ~= 0 then
            n = n + 1; out[n] = "\x10"
            n = n + 1; out[n] = encode_int32(nv)
        end
    end
    -- field 4: use_tls
    v = t.use_tls
    if v ~= nil and v ~= false then
        n = n + 1; out[n] = "\x20"
        n = n + 1; out[n] = wire.encode_bool(v)
    end
    -- field 5: client_tls_cert
    v = t.client_tls_cert
    if v ~= nil and v ~= '' then
        n = n + 1; out[n] = "\x2a"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    -- field 6: message_receive_limit
    v = t.message_receive_limit
    if v ~= nil and v ~= 0 then
        n = n + 1; out[n] = "\x30"
        n = n + 1; out[n] = wire.encode_uint32(v)
    end
    -- field 7: server_creds
    v = t.server_creds
    if v ~= nil or type(v) == 'cdata' then
        local _b = _imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_encode(v)
        n = n + 1; out[n] = "\x3a"
        local _len = #_b
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = _b
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return connectrpc.conformance.v1.ServerCompatRequest
function M.ServerCompatRequest_decode(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local decode_varint = wire.decode_varint
    local varint_to_int32 = wire.varint_to_int32
    local _d = M.ServerCompatRequest_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for connectrpc.conformance.v1.ServerCompatRequest decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local u
            u, pos = decode_varint(buf, pos)
            result.protocol = varint_to_int32(u)
        elseif id == 2 then
            local u
            u, pos = decode_varint(buf, pos)
            result.http_version = varint_to_int32(u)
        elseif id == 4 then
            local val
            val, pos = wire.decode_bool(buf, pos)
            result.use_tls = val
        elseif id == 5 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.client_tls_cert = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.client_tls_cert = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.client_tls_cert = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.client_tls_cert = val
            end
        elseif id == 6 then
            local val
            val, pos = wire.decode_uint32(buf, pos)
            result.message_receive_limit = val
        elseif id == 7 then
            local payload
            payload, pos = wire.decode_len(buf, pos)
            local prev = result.server_creds
            if prev == nil then
                result.server_creds = _imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_decode(payload, depth + 1)
            else
                pb.codec.merge_message(_imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_descriptor, prev, _imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_decode(payload, depth + 1))
            end
        else
            local _ebid = M.ServerCompatRequest_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return connectrpc.conformance.v1.ServerCompatRequest
function M.ServerCompatRequest_decode_unsafe(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local decode_varint = wire.decode_varint
    local varint_to_int32 = wire.varint_to_int32
    local _d = M.ServerCompatRequest_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for connectrpc.conformance.v1.ServerCompatRequest decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local u
            u, pos = decode_varint(buf, pos)
            result.protocol = varint_to_int32(u)
        elseif id == 2 then
            local u
            u, pos = decode_varint(buf, pos)
            result.http_version = varint_to_int32(u)
        elseif id == 4 then
            local val
            val, pos = wire.decode_bool(buf, pos)
            result.use_tls = val
        elseif id == 5 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.client_tls_cert = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.client_tls_cert = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.client_tls_cert = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.client_tls_cert = val
            end
        elseif id == 6 then
            local val
            val, pos = wire.decode_uint32(buf, pos)
            result.message_receive_limit = val
        elseif id == 7 then
            local payload
            payload, pos = wire.decode_len(buf, pos)
            local prev = result.server_creds
            if prev == nil then
                result.server_creds = _imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_decode_unsafe(payload, depth + 1)
            else
                pb.codec.merge_message(_imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_descriptor, prev, _imp_full_connectrpc_conformance_v1_config_pb.TLSCreds_decode_unsafe(payload, depth + 1))
            end
        else
            local _ebid = M.ServerCompatRequest_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.ServerCompatRequest_decode_lazy(b) return pb.decode_lazy(M.ServerCompatRequest_descriptor, b) end
---@param t connectrpc.conformance.v1.ServerCompatRequest
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.ServerCompatRequest_text(t, opts) return pb.text.encode(M.ServerCompatRequest_descriptor, t, opts) end

---@param t? connectrpc.conformance.v1.ServerCompatResponse
---@return connectrpc.conformance.v1.ServerCompatResponse
function M.ServerCompatResponse_new(t) return t or {} end

---@param t connectrpc.conformance.v1.ServerCompatResponse
---@return string
function M.ServerCompatResponse_encode(t)
    local encode_varint = wire.encode_varint
    local _d = M.ServerCompatResponse_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.encode(_p, t)
    end
    if type(t) ~= 'table' then
        error("expected table for connectrpc.conformance.v1.ServerCompatResponse, got " .. type(t), 0)
    end
    local out, n = {}, 0
    local v
    -- field 1: host
    v = t.host
    if v ~= nil and v ~= '' then
        n = n + 1; out[n] = "\x0a"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    -- field 2: port
    v = t.port
    if v ~= nil and v ~= 0 then
        n = n + 1; out[n] = "\x10"
        n = n + 1; out[n] = wire.encode_uint32(v)
    end
    -- field 3: pem_cert
    v = t.pem_cert
    if v ~= nil and v ~= '' then
        n = n + 1; out[n] = "\x1a"
        local _len = #v
        if _len < 128 then
            n = n + 1; out[n] = CHARS[_len]
        else
            n = n + 1; out[n] = encode_varint(_len)
        end
        n = n + 1; out[n] = v
    end
    local _uf = t._unknown_fields
    if _uf ~= nil and _uf ~= '' then n = n + 1; out[n] = _uf end
    return table.concat(out)
end

---@param b string
---@return connectrpc.conformance.v1.ServerCompatResponse
function M.ServerCompatResponse_decode(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_string = wire.decode_string
    local decode_tag = wire.decode_tag
    local _d = M.ServerCompatResponse_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for connectrpc.conformance.v1.ServerCompatResponse decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                if utf8_len(_s) == nil then error("invalid UTF-8 in string field at offset " .. pos, 0) end
                result.host = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    if utf8_len(_s) == nil then error("invalid UTF-8 in string field at offset " .. pos, 0) end
                    result.host = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_string(buf, pos)
                    result.host = val
                end
            else
                local val
                val, pos = decode_string(buf, pos)
                result.host = val
            end
        elseif id == 2 then
            local val
            val, pos = wire.decode_uint32(buf, pos)
            result.port = val
        elseif id == 3 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.pem_cert = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.pem_cert = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.pem_cert = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.pem_cert = val
            end
        else
            local _ebid = M.ServerCompatResponse_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return connectrpc.conformance.v1.ServerCompatResponse
function M.ServerCompatResponse_decode_unsafe(buf, depth)
    local decode_bytes = wire.decode_bytes
    local decode_tag = wire.decode_tag
    local _d = M.ServerCompatResponse_descriptor
    if pb.c_runtime ~= nil then
        local _p = _d.c_plan or pb.c_runtime.compile_plan(_d)
        return pb.c_runtime.decode_unsafe(_p, buf)
    end
    if type(buf) ~= 'string' then
        error("expected string for connectrpc.conformance.v1.ServerCompatResponse decode, got " .. type(buf), 0)
    end
    depth = depth or 0
    if depth > wire.RECURSION_LIMIT then wire.recursion_limit_error() end
    local result = {}
    local pos, len = 1, #buf
    local _uf
    while pos <= len do
        local _tag_start = pos
        local id, wt
        local _b = string_byte(buf, pos)
        if _b ~= nil and _b < 0x80 then
            wt = band(_b, 7)
            if wt >= 6 then error("illegal wire type " .. wt, 0) end
            id = rshift(_b, 3)
            if id == 0 then error("illegal field number 0", 0) end
            pos = pos + 1
        elseif _b ~= nil and pos < len then
            local _b2 = string_byte(buf, pos + 1)
            if _b2 < 0x80 then
                if _b2 == 0 then error("overlong tag varint at offset " .. pos, 0) end
                local _v = _b - 128 + _b2 * 128
                wt = band(_v, 7)
                if wt >= 6 then error("illegal wire type " .. wt, 0) end
                id = rshift(_v, 3)
                pos = pos + 2
            else
                id, wt, pos = decode_tag(buf, pos)
            end
        else
            id, wt, pos = decode_tag(buf, pos)
        end
        if id == 1 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.host = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.host = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.host = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.host = val
            end
        elseif id == 2 then
            local val
            val, pos = wire.decode_uint32(buf, pos)
            result.port = val
        elseif id == 3 then
            local _lb = string_byte(buf, pos)
            if _lb ~= nil and _lb < 0x80 then
                local _np = pos + 1
                local _epos = _np + _lb
                if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                local _s = buf:sub(_np, _epos - 1)
                result.pem_cert = _s
                pos = _epos
            elseif _lb ~= nil and pos < len then
                local _lb2 = string_byte(buf, pos + 1)
                if _lb2 ~= nil and _lb2 < 0x80 then
                    if _lb2 == 0 then error("overlong LEN varint at offset " .. pos, 0) end
                    local _ln = _lb - 128 + _lb2 * 128
                    local _np = pos + 2
                    local _epos = _np + _ln
                    if _epos - 1 > len then error("truncated LEN at offset " .. pos, 0) end
                    local _s = buf:sub(_np, _epos - 1)
                    result.pem_cert = _s
                    pos = _epos
                else
                    local val
                    val, pos = decode_bytes(buf, pos)
                    result.pem_cert = val
                end
            else
                local val
                val, pos = decode_bytes(buf, pos)
                result.pem_cert = val
            end
        else
            local _ebid = M.ServerCompatResponse_descriptor.extensions_by_id
            local _ext = _ebid and _ebid[id] or nil
            if _ext ~= nil then
                pos = pb.codec.decode_extension(_ext, buf, pos, wt, result, depth)
            else
                pos = wire.skip_field(buf, pos, wt, id)
                if _uf == nil then _uf = {} end
                _uf[#_uf + 1] = buf:sub(_tag_start, pos - 1)
            end
        end
    end
    if _uf ~= nil then result._unknown_fields = table.concat(_uf) end
    return result
end

---@param b string
---@return pb.MessageView
function M.ServerCompatResponse_decode_lazy(b) return pb.decode_lazy(M.ServerCompatResponse_descriptor, b) end
---@param t connectrpc.conformance.v1.ServerCompatResponse
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.ServerCompatResponse_text(t, opts) return pb.text.encode(M.ServerCompatResponse_descriptor, t, opts) end

-- Serialized FileDescriptorProto of connectrpc/conformance/v1/server_compat.proto (source_code_info
-- stripped), registered with pb.descriptors for server reflection.
M._file_descriptor = table.concat({
    "\x0a-connectrpc/conformance/v1/server_compat.proto\x12",
    "\x19connectrpc.conformance.v1\x1a&connectrpc/conforman",
    "ce/v1/config.proto\"\xde\x02\x0a\x13ServerCompatRequest\x12?\x0a\x08pr",
    "otocol\x18\x01 \x01(\x0e2#.connectrpc.conformance.v1.Protoco",
    "lR\x08protocol\x12I\x0a\x0chttp_version\x18\x02 \x01(\x0e2&.connectrpc.c",
    "onformance.v1.HTTPVersionR\x0bhttpVersion\x12\x17\x0a\x07use_tl",
    "s\x18\x04 \x01(\x08R\x06useTls\x12&\x0a\x0fclient_tls_cert\x18\x05 \x01(\x0cR\x0dclient",
    "TlsCert\x122\x0a\x15message_receive_limit\x18\x06 \x01(\x0dR\x13messageR",
    "eceiveLimit\x12F\x0a\x0cserver_creds\x18\x07 \x01(\x0b2#.connectrpc.c",
    "onformance.v1.TLSCredsR\x0bserverCreds\"Y\x0a\x14ServerCom",
    "patResponse\x12\x12\x0a\x04host\x18\x01 \x01(\x09R\x04host\x12\x12\x0a\x04port\x18\x02 \x01(\x0dR\x04p",
    "ort\x12\x19\x0a\x08pem_cert\x18\x03 \x01(\x0cR\x07pemCertb\x06proto3",
})
pb.descriptors.register(M._file_descriptor)
-- Snapshots of the imports the runtime does not ship, so the import
-- graph of this file is registered. A snapshot never replaces the
-- descriptor an imported file's own module registers.
-- connectrpc/conformance/v1/config.proto
pb.descriptors.register(table.concat({
    "\x0a&connectrpc/conformance/v1/config.proto\x12\x19connec",
    "trpc.conformance.v1\"\xe1\x01\x0a\x06Config\x12?\x0a\x08features\x18\x01 \x01(\x0b",
    "2#.connectrpc.conformance.v1.FeaturesR\x08features\x12",
    "J\x0a\x0dinclude_cases\x18\x02 \x03(\x0b2%.connectrpc.conformance.",
    "v1.ConfigCaseR\x0cincludeCases\x12J\x0a\x0dexclude_cases\x18\x03 \x03",
    "(\x0b2%.connectrpc.conformance.v1.ConfigCaseR\x0cexclu",
    "deCases\"\xb3\x07\x0a\x08Features\x12B\x0a\x08versions\x18\x01 \x03(\x0e2&.connect",
    "rpc.conformance.v1.HTTPVersionR\x08versions\x12A\x0a\x09prot",
    "ocols\x18\x02 \x03(\x0e2#.connectrpc.conformance.v1.Protocol",
    "R\x09protocols\x128\x0a\x06codecs\x18\x03 \x03(\x0e2 .connectrpc.conform",
    "ance.v1.CodecR\x06codecs\x12J\x0a\x0ccompressions\x18\x04 \x03(\x0e2&.co",
    "nnectrpc.conformance.v1.CompressionR\x0ccompression",
    "s\x12H\x0a\x0cstream_types\x18\x05 \x03(\x0e2%.connectrpc.conformance",
    ".v1.StreamTypeR\x0bstreamTypes\x12&\x0a\x0csupports_h2c\x18\x06 \x01(",
    "\x08H\x00R\x0bsupportsH2c\x88\x01\x01\x12&\x0a\x0csupports_tls\x18\x07 \x01(\x08H\x01R\x0bsup",
    "portsTls\x88\x01\x01\x12>\x0a\x19supports_tls_client_certs\x18\x08 \x01(\x08H\x02",
    "R\x16supportsTlsClientCerts\x88\x01\x01\x120\x0a\x11supports_trailers",
    "\x18\x09 \x01(\x08H\x03R\x10supportsTrailers\x88\x01\x01\x12R\x0a$supports_half_d",
    "uplex_bidi_over_http1\x18\x0a \x01(\x08H\x04R\x1fsupportsHalfDuple",
    "xBidiOverHttp1\x88\x01\x01\x125\x0a\x14supports_connect_get\x18\x0b \x01(\x08H",
    "\x05R\x12supportsConnectGet\x88\x01\x01\x12H\x0a\x1esupports_message_rec",
    "eive_limit\x18\x0c \x01(\x08H\x06R\x1bsupportsMessageReceiveLimit\x88",
    "\x01\x01B\x0f\x0a\x0d_supports_h2cB\x0f\x0a\x0d_supports_tlsB\x1c\x0a\x1a_support",
    "s_tls_client_certsB\x14\x0a\x12_supports_trailersB'\x0a%_sup",
    "ports_half_duplex_bidi_over_http1B\x17\x0a\x15_supports_c",
    "onnect_getB!\x0a\x1f_supports_message_receive_limit\"\xb0\x04",
    "\x0a\x0aConfigCase\x12@\x0a\x07version\x18\x01 \x01(\x0e2&.connectrpc.confo",
    "rmance.v1.HTTPVersionR\x07version\x12?\x0a\x08protocol\x18\x02 \x01(\x0e",
    "2#.connectrpc.conformance.v1.ProtocolR\x08protocol\x12",
    "6\x0a\x05codec\x18\x03 \x01(\x0e2 .connectrpc.conformance.v1.Codec",
    "R\x05codec\x12H\x0a\x0bcompression\x18\x04 \x01(\x0e2&.connectrpc.confor",
    "mance.v1.CompressionR\x0bcompression\x12F\x0a\x0bstream_type",
    "\x18\x05 \x01(\x0e2%.connectrpc.conformance.v1.StreamTypeR\x0as",
    "treamType\x12\x1c\x0a\x07use_tls\x18\x06 \x01(\x08H\x00R\x06useTls\x88\x01\x01\x124\x0a\x14use_t",
    "ls_client_certs\x18\x07 \x01(\x08H\x01R\x11useTlsClientCerts\x88\x01\x01\x12>\x0a",
    "\x19use_message_receive_limit\x18\x08 \x01(\x08H\x02R\x16useMessageRe",
    "ceiveLimit\x88\x01\x01B\x0a\x0a\x08_use_tlsB\x17\x0a\x15_use_tls_client_cer",
    "tsB\x1c\x0a\x1a_use_message_receive_limit\"0\x0a\x08TLSCreds\x12\x12\x0a\x04",
    "cert\x18\x01 \x01(\x0cR\x04cert\x12\x10\x0a\x03key\x18\x02 \x01(\x0cR\x03key*g\x0a\x0bHTTPVersio",
    "n\x12\x1c\x0a\x18HTTP_VERSION_UNSPECIFIED\x10\x00\x12\x12\x0a\x0eHTTP_VERSION_",
    "1\x10\x01\x12\x12\x0a\x0eHTTP_VERSION_2\x10\x02\x12\x12\x0a\x0eHTTP_VERSION_3\x10\x03*d\x0a\x08P",
    "rotocol\x12\x18\x0a\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x14\x0a\x10PROTOCOL_CO",
    "NNECT\x10\x01\x12\x11\x0a\x0dPROTOCOL_GRPC\x10\x02\x12\x15\x0a\x11PROTOCOL_GRPC_WEB\x10",
    "\x03*S\x0a\x05Codec\x12\x15\x0a\x11CODEC_UNSPECIFIED\x10\x00\x12\x0f\x0a\x0bCODEC_PROTO",
    "\x10\x01\x12\x0e\x0a\x0aCODEC_JSON\x10\x02\x12\x12\x0a\x0aCODEC_TEXT\x10\x03\x1a\x02\x08\x01*\xb5\x01\x0a\x0bCompr",
    "ession\x12\x1b\x0a\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x18\x0a\x14COMPRESSI",
    "ON_IDENTITY\x10\x01\x12\x14\x0a\x10COMPRESSION_GZIP\x10\x02\x12\x12\x0a\x0eCOMPRESSI",
    "ON_BR\x10\x03\x12\x14\x0a\x10COMPRESSION_ZSTD\x10\x04\x12\x17\x0a\x13COMPRESSION_DEF",
    "LATE\x10\x05\x12\x16\x0a\x12COMPRESSION_SNAPPY\x10\x06*\xd0\x01\x0a\x0aStreamType\x12\x1b\x0a",
    "\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x15\x0a\x11STREAM_TYPE_UNARY\x10",
    "\x01\x12\x1d\x0a\x19STREAM_TYPE_CLIENT_STREAM\x10\x02\x12\x1d\x0a\x19STREAM_TYPE_",
    "SERVER_STREAM\x10\x03\x12'\x0a#STREAM_TYPE_HALF_DUPLEX_BIDI_",
    "STREAM\x10\x04\x12'\x0a#STREAM_TYPE_FULL_DUPLEX_BIDI_STREAM\x10",
    "\x05*\x94\x03\x0a\x04Code\x12\x14\x0a\x10CODE_UNSPECIFIED\x10\x00\x12\x11\x0a\x0dCODE_CANCELE",
    "D\x10\x01\x12\x10\x0a\x0cCODE_UNKNOWN\x10\x02\x12\x19\x0a\x15CODE_INVALID_ARGUMENT\x10\x03",
    "\x12\x1a\x0a\x16CODE_DEADLINE_EXCEEDED\x10\x04\x12\x12\x0a\x0eCODE_NOT_FOUND\x10\x05",
    "\x12\x17\x0a\x13CODE_ALREADY_EXISTS\x10\x06\x12\x1a\x0a\x16CODE_PERMISSION_DEN",
    "IED\x10\x07\x12\x1b\x0a\x17CODE_RESOURCE_EXHAUSTED\x10\x08\x12\x1c\x0a\x18CODE_FAILE",
    "D_PRECONDITION\x10\x09\x12\x10\x0a\x0cCODE_ABORTED\x10\x0a\x12\x15\x0a\x11CODE_OUT_O",
    "F_RANGE\x10\x0b\x12\x16\x0a\x12CODE_UNIMPLEMENTED\x10\x0c\x12\x11\x0a\x0dCODE_INTERN",
    "AL\x10\x0d\x12\x14\x0a\x10CODE_UNAVAILABLE\x10\x0e\x12\x12\x0a\x0eCODE_DATA_LOSS\x10\x0f\x12\x18",
    "\x0a\x14CODE_UNAUTHENTICATED\x10\x10b\x06proto3",
}), {snapshot = true})

return M
