// gen-builtin-descriptors writes runtime/pb/descriptors_builtin.lua: the
// serialized FileDescriptorProto of every file the runtime ships a
// descriptor for (well-known types, descriptor.proto, plugin.proto and
// google/api/{annotations,http}.proto). pb.descriptors loads the table
// on first use, so server reflection can hand these files to clients
// like any generated one.
//
// The bytes come from the host protoc (`protoc --include_imports
// --descriptor_set_out`), read off the FileDescriptorSet wire, so they
// match what that protoc hands the plugin for the same files. The WKT
// sources are protoc's own bundled copies; google/api comes from the
// vendored options/ directory. The protoc version is recorded in the
// generated header: keep it at the same release as the conformance
// image (and the protoc that runs `just gen`).
//
// Usage:
//
//	go run ./cmd/gen-builtin-descriptors -I options > runtime/pb/descriptors_builtin.lua
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tarantool-contrib/tarantool-protobuf/internal/builtindesc"
	"github.com/tarantool-contrib/tarantool-protobuf/internal/luastr"
	"github.com/tarantool-contrib/tarantool-protobuf/internal/rawdesc"
)

func main() {
	include := flag.String("I", "options", "include directory holding google/api/*.proto")
	protoc := flag.String("protoc", "protoc", "protoc binary")
	flag.Parse()

	w := bufio.NewWriter(os.Stdout)
	if err := run(w, *protoc, *include); err != nil {
		fmt.Fprintf(os.Stderr, "gen-builtin-descriptors: %v\n", err)
		os.Exit(1)
	}
	if err := w.Flush(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-builtin-descriptors: %v\n", err)
		os.Exit(1)
	}
}

func run(w *bufio.Writer, protoc, include string) error {
	version, err := exec.Command(protoc, "--version").Output()
	if err != nil {
		return fmt.Errorf("%s --version: %w", protoc, err)
	}

	dir, err := os.MkdirTemp("", "gen-builtin-descriptors")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)
	setPath := filepath.Join(dir, "builtin.pb")

	args := []string{"--include_imports", "--descriptor_set_out=" + setPath, "-I", include}
	args = append(args, builtindesc.Paths()...)
	cmd := exec.Command(protoc, args...)
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("protoc %s: %w", strings.Join(args, " "), err)
	}
	set, err := os.ReadFile(setPath)
	if err != nil {
		return err
	}
	files, err := rawdesc.FromSet(set)
	if err != nil {
		return fmt.Errorf("read descriptor set: %w", err)
	}
	byName := map[string][]byte{}
	for _, f := range files {
		byName[f.Name] = f.Bytes
	}

	p := func(format string, args ...any) { fmt.Fprintf(w, format+"\n", args...) }
	p("-- Code generated by gen-builtin-descriptors. DO NOT EDIT.")
	p("-- protoc: %s", strings.TrimSpace(string(version)))
	p("--")
	p("-- Serialized FileDescriptorProto (source_code_info stripped) of every")
	p("-- file whose descriptor the runtime ships: the well-known types,")
	p("-- descriptor.proto, plugin.proto and google/api/{annotations,http}.proto,")
	p("-- as the protoc above serializes them. Dependencies come before the")
	p("-- files that import them. Loaded lazily by pb.descriptors; regenerate")
	p("-- with `just gen-builtin-descriptors`.")
	p("return {")
	for _, path := range builtindesc.Paths() {
		b, ok := byName[path]
		if !ok {
			return fmt.Errorf("%s: missing from protoc's descriptor set", path)
		}
		p("    {")
		p("        name = %s,", luastr.Literal(path))
		p("        bytes = table.concat({")
		for _, chunk := range luastr.Chunks(b) {
			p("            %s,", chunk)
		}
		p("        }),")
		p("    },")
	}
	p("}")
	return nil
}
