#!/usr/bin/env tarantool
--
-- The server under test for the Connect conformance suite
-- (https://github.com/connectrpc/conformance, `connectconformance --mode
-- server`): pb.server with connectrpc.conformance.v1.ConformanceService,
-- generated by protoc-gen-tarantool from third_party/connect-conformance.
--
-- The runner writes one size-delimited ServerCompatRequest (a 4-byte
-- big-endian length, then the message) to stdin. The server starts on
-- 127.0.0.1 on a free port and answers with a size-delimited
-- ServerCompatResponse{host, port} on stdout, then serves until the
-- runner sends SIGTERM. One process serves every protocol and HTTP
-- version pb.server speaks (gRPC and Connect, HTTP/1.1 and h2c), so the
-- request's protocol and HTTP version only need checking, not choosing.
--
-- `just connect-conformance` runs it; LUA_PATH is derived from this
-- script's location plus TARANTOOL_HTTP2_RUNTIME (the runner passes the
-- environment through).

local function script_dir()
    local src = debug.getinfo(1, 'S').source
    if src:sub(1, 1) == '@' then src = src:sub(2) end
    return src:match('^(.*/)[^/]+$') or './'
end
local ROOT = script_dir() .. '../..'
local paths = {
    ROOT .. '/runtime/?/init.lua',
    ROOT .. '/runtime/?.lua',
    ROOT .. '/examples/expected/?.lua',
    ROOT .. '/examples/expected/?/init.lua',
}
local http2_runtime = os.getenv('TARANTOOL_HTTP2_RUNTIME')
if http2_runtime ~= nil and http2_runtime ~= '' then
    paths[#paths + 1] = http2_runtime .. '/?.lua'
    paths[#paths + 1] = http2_runtime .. '/?/init.lua'
end
paths[#paths + 1] = package.path
package.path = table.concat(paths, ';')
-- Our `pb`, not a lua-protobuf pb.so a rocks tree may carry.
package.loaded.pb = dofile(ROOT .. '/runtime/pb/init.lua')

local fiber = require('fiber')
local log   = require('log')
local pb    = require('pb')
local svc   = require('full.connectrpc.conformance.v1.service_pb')
local compat = require('full.connectrpc.conformance.v1.server_compat_pb')

-- Every conformance message goes into the Any registry: requests are
-- echoed back as Any, and a JSON response renders them by type URL.
for k, v in pairs(svc) do
    if type(k) == 'string' and k:match('_descriptor$') and type(v) == 'table' and v.name then
        pb.register(v)
    end
end

-- ---------------------------------------------------------------------------
-- The handshake
-- ---------------------------------------------------------------------------

io.stdin:setvbuf('no')
io.stdout:setvbuf('no')

local function read_n(n)
    local got = io.stdin:read(n)
    if got == nil or #got < n then error('short read on stdin', 0) end
    return got
end

local hdr = read_n(4)
local b1, b2, b3, b4 = hdr:byte(1, 4)
local compat_req = compat.ServerCompatRequest_decode(read_n(((b1 * 256 + b2) * 256 + b3) * 256 + b4))

if compat_req.use_tls then
    error('TLS is not supported (the conformance config says supports_tls: false)', 0)
end

-- ---------------------------------------------------------------------------
-- ConformanceService
-- ---------------------------------------------------------------------------

local function headers_list(md)
    local out = {}
    for k, v in pairs(md or {}) do
        out[#out + 1] = {name = k, value = type(v) == 'table' and v or {tostring(v)}}
    end
    table.sort(out, function(a, b) return a.name < b.name end)
    return out
end

local function set_metadata(dst, list)
    for _, h in ipairs(list or {}) do
        local key = h.name:lower()
        local values = dst[key] or {}
        for _, v in ipairs(h.value or {}) do values[#values + 1] = v end
        dst[key] = values
    end
end

local function request_info(ctx, reqs)
    local info = {
        request_headers = headers_list(ctx.metadata),
        requests = reqs,
    }
    if ctx.deadline ~= nil then
        local left = ctx.deadline - require('clock').monotonic()
        info.timeout_ms = math.max(0, math.floor(left * 1000))
    end
    if ctx.connect ~= nil and ctx.connect.get then
        info.connect_get_info = {query_params = headers_list(ctx.connect.query)}
    end
    return info
end

local function pack(desc, msg)
    return pb.any.pack(desc, msg)
end

-- A status from a conformance Error, with the request info appended to
-- its details. Its codes are numbered as gRPC's.
local function status_of(err, info)
    local details = {}
    for i, d in ipairs(err.details or {}) do details[i] = d end
    if info ~= nil then
        details[#details + 1] = pack(svc.ConformancePayload_RequestInfo_descriptor, info)
    end
    return pb.grpc.status(err.code or 0, err.message or '', details)
end

local function sleep_ms(ms)
    if ms ~= nil and ms > 0 then fiber.sleep(ms / 1000) end
end

local function unary(desc)
    return function(req, ctx)
        local def = req.response_definition
        local info = request_info(ctx, {pack(desc, req)})
        if def == nil then return {payload = {request_info = info}} end
        set_metadata(ctx.response_metadata, def.response_headers)
        set_metadata(ctx.trailing_metadata, def.response_trailers)
        if def.error ~= nil then error(status_of(def.error, info)) end
        sleep_ms(def.response_delay_ms)
        return {payload = {request_info = info, data = def.response_data}}
    end
end

local impl = {
    Unary = unary(svc.UnaryRequest_descriptor),
    IdempotentUnary = unary(svc.IdempotentUnaryRequest_descriptor),

    ServerStream = function(req, stream, ctx)
        local def = req.response_definition
        if def == nil then return end
        set_metadata(ctx.response_metadata, def.response_headers)
        set_metadata(ctx.trailing_metadata, def.response_trailers)
        local reqs = {pack(svc.ServerStreamRequest_descriptor, req)}
        local sent = 0
        for _, data in ipairs(def.response_data or {}) do
            local payload = {data = data}
            if sent == 0 then payload.request_info = request_info(ctx, reqs) end
            sleep_ms(def.response_delay_ms)
            if not stream:send({payload = payload}) then return end
            sent = sent + 1
        end
        if def.error ~= nil then
            error(status_of(def.error, sent == 0 and request_info(ctx, reqs) or nil))
        end
    end,

    ClientStream = function(stream, ctx)
        local def, reqs, first = nil, {}, true
        while true do
            local req, err = stream:recv()
            if req == nil then
                if err ~= nil then error(err, 0) end
                break
            end
            if first then
                def = req.response_definition
                first = false
            end
            reqs[#reqs + 1] = pack(svc.ClientStreamRequest_descriptor, req)
        end
        local info = request_info(ctx, reqs)
        if def == nil then return {payload = {request_info = info}} end
        set_metadata(ctx.response_metadata, def.response_headers)
        set_metadata(ctx.trailing_metadata, def.response_trailers)
        if def.error ~= nil then error(status_of(def.error, info)) end
        sleep_ms(def.response_delay_ms)
        return {payload = {request_info = info, data = def.response_data}}
    end,

    BidiStream = function(stream, ctx)
        local def, full_duplex, first = nil, false, true
        local reqs, sent = {}, 0
        local data = {}
        while true do
            local req, err = stream:recv()
            if req == nil then
                if err ~= nil then error(err, 0) end
                break
            end
            reqs[#reqs + 1] = pack(svc.BidiStreamRequest_descriptor, req)
            if first then
                first = false
                def = req.response_definition
                full_duplex = req.full_duplex or false
                if def ~= nil then
                    set_metadata(ctx.response_metadata, def.response_headers)
                    set_metadata(ctx.trailing_metadata, def.response_trailers)
                    data = def.response_data or {}
                end
            end
            if full_duplex then
                if sent >= #data then break end
                local info
                if sent == 0 then
                    info = request_info(ctx, reqs)
                else
                    info = {requests = reqs}
                end
                sleep_ms(def.response_delay_ms)
                if not stream:send({payload = {data = data[sent + 1], request_info = info}}) then
                    return
                end
                sent = sent + 1
                reqs = {}
            end
        end
        if def == nil then return end
        while sent < #data do
            local payload = {data = data[sent + 1]}
            if sent == 0 then payload.request_info = request_info(ctx, reqs) end
            sleep_ms(def.response_delay_ms)
            if not stream:send({payload = payload}) then return end
            sent = sent + 1
        end
        if def.error ~= nil then
            error(status_of(def.error, sent == 0 and request_info(ctx, reqs) or nil))
        end
    end,
    -- Unimplemented is left out: the generated server answers
    -- UNIMPLEMENTED for it.
}

-- tarantool-http2 gives every HTTP/2 connection its own set of LuaJIT
-- FFI callbacks, and LuaJIT has a few hundred callback slots per
-- process: past about 60 open HTTP/2 connections, new ones fail with
-- "too many callbacks". The grpc-go client of the suite opens a
-- connection per test case and leaves it open, so idle connections are
-- closed after a second (GOAWAY; grpc-go reconnects) instead of the
-- default 300 s. The limit itself is a tarantool-http2 defect.
local limits = {idle_timeout = 1}
if (compat_req.message_receive_limit or 0) > 0 then
    limits.max_recv_message_size = compat_req.message_receive_limit
end

local server = pb.server.new({
    listen = '127.0.0.1:0',
    services = {svc.ConformanceService_server(impl)},
    reflection = false,
    health = false,
    transcoding = false,
    limits = limits,
}):start()

local resp = compat.ServerCompatResponse_encode({host = '127.0.0.1', port = server:address().port})
local n = #resp
io.stdout:write(string.char(bit.band(bit.rshift(n, 24), 0xff), bit.band(bit.rshift(n, 16), 0xff),
                            bit.band(bit.rshift(n, 8), 0xff), bit.band(n, 0xff)) .. resp)
io.stdout:flush()
log.info('connect conformance server on 127.0.0.1:%d (protocol %s, HTTP version %s)',
         server:address().port, tostring(compat_req.protocol), tostring(compat_req.http_version))
