-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: c_grow_proto2.proto
-- syntax: proto2
-- package: c_grow_proto2

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/c_grow_proto2"}

-- Pre-declare message descriptors so cross-references resolve.
M.KV_descriptor = {name = "c_grow_proto2.KV"}
M.Holder_descriptor = {name = "c_grow_proto2.Holder"}
M.Holder_Entry_descriptor = {name = "c_grow_proto2.Holder.Entry"}
M.Holder_Single_descriptor = {name = "c_grow_proto2.Holder.Single"}

-- Message: c_grow_proto2.KV
M.KV_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="bytes", optional=true},
    {name="value", id=2, kind='scalar', proto_type="bytes", optional=true},
}
pb.finalize_message(M.KV_descriptor)
M.KV_fields = pb.field_names({
    key = "key",
    value = "value",
})

-- Message: c_grow_proto2.Holder
M.Holder_descriptor.fields = {
    {name="first", id=1, kind='message', message=M.KV_descriptor, optional=true},
    {name="entry", id=2, kind='group', message=M.Holder_Entry_descriptor, repeated=true},
    {name="single", id=5, kind='group', message=M.Holder_Single_descriptor, optional=true},
    {name="last", id=8, kind='message', message=M.KV_descriptor, optional=true},
}
pb.finalize_message(M.Holder_descriptor)
M.Holder_fields = pb.field_names({
    first = "first",
    entry = "entry",
    single = "single",
    last = "last",
})

-- Message: c_grow_proto2.Holder.Entry
M.Holder_Entry_descriptor.fields = {
    {name="blob", id=3, kind='scalar', proto_type="bytes", optional=true},
    {name="kv", id=4, kind='message', message=M.KV_descriptor, optional=true},
}
pb.finalize_message(M.Holder_Entry_descriptor)
M.Holder_Entry_fields = pb.field_names({
    blob = "blob",
    kv = "kv",
})

-- Message: c_grow_proto2.Holder.Single
M.Holder_Single_descriptor.fields = {
    {name="kv", id=6, kind='message', message=M.KV_descriptor, optional=true},
    {name="kvs", id=7, kind='message', message=M.KV_descriptor, repeated=true},
}
pb.finalize_message(M.Holder_Single_descriptor)
M.Holder_Single_fields = pb.field_names({
    kv = "kv",
    kvs = "kvs",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@class c_grow_proto2.KV
---@field key? string
---@field value? string

---@class c_grow_proto2.Holder
---@field first? c_grow_proto2.KV
---@field entry c_grow_proto2.Holder.Entry[]
---@field single? c_grow_proto2.Holder.Single
---@field last? c_grow_proto2.KV

---@class c_grow_proto2.Holder.Entry
---@field blob? string
---@field kv? c_grow_proto2.KV

---@class c_grow_proto2.Holder.Single
---@field kv? c_grow_proto2.KV
---@field kvs c_grow_proto2.KV[]

---@param t? c_grow_proto2.KV
---@return c_grow_proto2.KV
function M.KV_new(t) return t or {} end
---@param t c_grow_proto2.KV
---@return string
function M.KV_encode(t) return pb.encode(M.KV_descriptor, t) end
---@param b string
---@return c_grow_proto2.KV
function M.KV_decode(b) return pb.decode(M.KV_descriptor, b) end
function M.KV_decode_unsafe(b) return pb.decode_unsafe(M.KV_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.KV_decode_lazy(b) return pb.decode_lazy(M.KV_descriptor, b) end
---@param t c_grow_proto2.KV
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.KV_text(t, opts) return pb.text.encode(M.KV_descriptor, t, opts) end
---@param t c_grow_proto2.KV
---@return boolean
function M.KV_has_key(t) return t.key ~= nil end
---@param t c_grow_proto2.KV
function M.KV_clear_key(t) t.key = nil end
---@param t c_grow_proto2.KV
---@return boolean
function M.KV_has_value(t) return t.value ~= nil end
---@param t c_grow_proto2.KV
function M.KV_clear_value(t) t.value = nil end

---@param t? c_grow_proto2.Holder
---@return c_grow_proto2.Holder
function M.Holder_new(t) return t or {} end
---@param t c_grow_proto2.Holder
---@return string
function M.Holder_encode(t) return pb.encode(M.Holder_descriptor, t) end
---@param b string
---@return c_grow_proto2.Holder
function M.Holder_decode(b) return pb.decode(M.Holder_descriptor, b) end
function M.Holder_decode_unsafe(b) return pb.decode_unsafe(M.Holder_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Holder_decode_lazy(b) return pb.decode_lazy(M.Holder_descriptor, b) end
---@param t c_grow_proto2.Holder
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_text(t, opts) return pb.text.encode(M.Holder_descriptor, t, opts) end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_first(t) return t.first ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_first(t) t.first = nil end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_single(t) return t.single ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_single(t) t.single = nil end
---@param t c_grow_proto2.Holder
---@return boolean
function M.Holder_has_last(t) return t.last ~= nil end
---@param t c_grow_proto2.Holder
function M.Holder_clear_last(t) t.last = nil end

---@param t? c_grow_proto2.Holder.Entry
---@return c_grow_proto2.Holder.Entry
function M.Holder_Entry_new(t) return t or {} end
---@param t c_grow_proto2.Holder.Entry
---@return string
function M.Holder_Entry_encode(t) return pb.encode(M.Holder_Entry_descriptor, t) end
---@param b string
---@return c_grow_proto2.Holder.Entry
function M.Holder_Entry_decode(b) return pb.decode(M.Holder_Entry_descriptor, b) end
function M.Holder_Entry_decode_unsafe(b) return pb.decode_unsafe(M.Holder_Entry_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Holder_Entry_decode_lazy(b) return pb.decode_lazy(M.Holder_Entry_descriptor, b) end
---@param t c_grow_proto2.Holder.Entry
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_Entry_text(t, opts) return pb.text.encode(M.Holder_Entry_descriptor, t, opts) end
---@param t c_grow_proto2.Holder.Entry
---@return boolean
function M.Holder_Entry_has_blob(t) return t.blob ~= nil end
---@param t c_grow_proto2.Holder.Entry
function M.Holder_Entry_clear_blob(t) t.blob = nil end
---@param t c_grow_proto2.Holder.Entry
---@return boolean
function M.Holder_Entry_has_kv(t) return t.kv ~= nil end
---@param t c_grow_proto2.Holder.Entry
function M.Holder_Entry_clear_kv(t) t.kv = nil end

---@param t? c_grow_proto2.Holder.Single
---@return c_grow_proto2.Holder.Single
function M.Holder_Single_new(t) return t or {} end
---@param t c_grow_proto2.Holder.Single
---@return string
function M.Holder_Single_encode(t) return pb.encode(M.Holder_Single_descriptor, t) end
---@param b string
---@return c_grow_proto2.Holder.Single
function M.Holder_Single_decode(b) return pb.decode(M.Holder_Single_descriptor, b) end
function M.Holder_Single_decode_unsafe(b) return pb.decode_unsafe(M.Holder_Single_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Holder_Single_decode_lazy(b) return pb.decode_lazy(M.Holder_Single_descriptor, b) end
---@param t c_grow_proto2.Holder.Single
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Holder_Single_text(t, opts) return pb.text.encode(M.Holder_Single_descriptor, t, opts) end
---@param t c_grow_proto2.Holder.Single
---@return boolean
function M.Holder_Single_has_kv(t) return t.kv ~= nil end
---@param t c_grow_proto2.Holder.Single
function M.Holder_Single_clear_kv(t) t.kv = nil end

-- Extension: c_grow_proto2.ext_kv extends c_grow_proto2.Holder (tag 100)
pb.register_extension(M.Holder_descriptor, {name="ext_kv", full_name="c_grow_proto2.ext_kv", id=100, kind='message', message=M.KV_descriptor, optional=true})
-- Extension: c_grow_proto2.ext_kvs extends c_grow_proto2.Holder (tag 101)
pb.register_extension(M.Holder_descriptor, {name="ext_kvs", full_name="c_grow_proto2.ext_kvs", id=101, kind='message', message=M.KV_descriptor, repeated=true})
-- Extension: c_grow_proto2.ext_blob extends c_grow_proto2.Holder (tag 102)
pb.register_extension(M.Holder_descriptor, {name="ext_blob", full_name="c_grow_proto2.ext_blob", id=102, kind='scalar', proto_type="bytes", optional=true})

return M
