-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: proto2_basic.proto
-- syntax: proto2
-- package: proto2_basic

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/proto2_basic"}

-- Enum: proto2_basic.Defaults.Color
M.Defaults_Color_descriptor = pb.enum("proto2_basic.Defaults.Color", {
    RED = 0,
    GREEN = 1,
    BLUE = 2,
})
M.Defaults_Color_descriptor.closed = true
M.Defaults_Color = M.Defaults_Color_descriptor.by_name

-- Pre-declare message descriptors so cross-references resolve.
M.Defaults_descriptor = {name = "proto2_basic.Defaults"}
M.Cardinality_descriptor = {name = "proto2_basic.Cardinality"}
M.Nested_descriptor = {name = "proto2_basic.Nested"}
M.Nested_Inner_descriptor = {name = "proto2_basic.Nested.Inner"}
M.WithGroup_descriptor = {name = "proto2_basic.WithGroup"}
M.WithGroup_SingleGroup_descriptor = {name = "proto2_basic.WithGroup.SingleGroup"}
M.WithGroup_RepGroup_descriptor = {name = "proto2_basic.WithGroup.RepGroup"}
M.BenchPayload_descriptor = {name = "proto2_basic.BenchPayload"}
M.BenchPayload_Stats_descriptor = {name = "proto2_basic.BenchPayload.Stats"}
M.BenchPayload_Inner_descriptor = {name = "proto2_basic.BenchPayload.Inner"}

-- Message: proto2_basic.Defaults
M.Defaults_descriptor.fields = {
    {name="i", id=1, kind='scalar', proto_type="int32", optional=true, default_value=17},
    {name="s", id=2, kind='scalar', proto_type="string", optional=true, default_value="hello"},
    {name="b", id=3, kind='scalar', proto_type="bool", optional=true, default_value=true},
    {name="f", id=4, kind='scalar', proto_type="float", optional=true, default_value=3.5},
    {name="d", id=5, kind='scalar', proto_type="double", optional=true, default_value=1.5},
    {name="i64", id=6, kind='scalar', proto_type="int64", optional=true, default_value=1234567890123LL},
    {name="u64", id=7, kind='scalar', proto_type="uint64", optional=true, default_value=17ULL},
    {name="by", id=8, kind='scalar', proto_type="bytes", optional=true, default_value="\x00\xff"},
    {name="color", id=9, kind='enum', enum=M.Defaults_Color_descriptor, optional=true, default_value="GREEN"},
}
pb.finalize_message(M.Defaults_descriptor)
M.Defaults_fields = pb.field_names({
    i = "i",
    s = "s",
    b = "b",
    f = "f",
    d = "d",
    i64 = "i64",
    u64 = "u64",
    by = "by",
    color = "color",
})

-- Message: proto2_basic.Cardinality
M.Cardinality_descriptor.fields = {
    {name="r", id=1, kind='scalar', proto_type="int32", required=true},
    {name="o", id=2, kind='scalar', proto_type="int32", optional=true},
    {name="packed_default", id=3, kind='scalar', proto_type="int32", repeated=true, packed=false},
    {name="explicitly_packed", id=4, kind='scalar', proto_type="int32", repeated=true, packed=true, options={packed = true}},
    {name="explicitly_unpacked", id=5, kind='scalar', proto_type="int32", repeated=true, packed=false, options={packed = false}},
}
pb.finalize_message(M.Cardinality_descriptor)
M.Cardinality_fields = pb.field_names({
    r = "r",
    o = "o",
    packed_default = "packed_default",
    explicitly_packed = "explicitly_packed",
    explicitly_unpacked = "explicitly_unpacked",
})

-- Message: proto2_basic.Nested
M.Nested_descriptor.fields = {
    {name="inner", id=1, kind='message', message=M.Nested_Inner_descriptor, required=true},
    {name="inner_opt", id=2, kind='message', message=M.Nested_Inner_descriptor, optional=true},
}
pb.finalize_message(M.Nested_descriptor)
M.Nested_fields = pb.field_names({
    inner = "inner",
    inner_opt = "inner_opt",
})

-- Message: proto2_basic.Nested.Inner
M.Nested_Inner_descriptor.fields = {
    {name="x", id=1, kind='scalar', proto_type="int32", required=true},
}
pb.finalize_message(M.Nested_Inner_descriptor)
M.Nested_Inner_fields = pb.field_names({
    x = "x",
})

-- Message: proto2_basic.WithGroup
M.WithGroup_descriptor.fields = {
    {name="singlegroup", id=1, kind='group', message=M.WithGroup_SingleGroup_descriptor, optional=true},
    {name="repgroup", id=4, kind='group', message=M.WithGroup_RepGroup_descriptor, repeated=true},
}
pb.finalize_message(M.WithGroup_descriptor)
M.WithGroup_fields = pb.field_names({
    singlegroup = "singlegroup",
    repgroup = "repgroup",
})

-- Message: proto2_basic.WithGroup.SingleGroup
M.WithGroup_SingleGroup_descriptor.fields = {
    {name="a", id=2, kind='scalar', proto_type="int32", optional=true},
    {name="s", id=3, kind='scalar', proto_type="string", optional=true},
}
pb.finalize_message(M.WithGroup_SingleGroup_descriptor)
M.WithGroup_SingleGroup_fields = pb.field_names({
    a = "a",
    s = "s",
})

-- Message: proto2_basic.WithGroup.RepGroup
M.WithGroup_RepGroup_descriptor.fields = {
    {name="n", id=5, kind='scalar', proto_type="int32", optional=true},
}
pb.finalize_message(M.WithGroup_RepGroup_descriptor)
M.WithGroup_RepGroup_fields = pb.field_names({
    n = "n",
})

-- Message: proto2_basic.BenchPayload
M.BenchPayload_descriptor.fields = {
    {name="id", id=1, kind='scalar', proto_type="int32", required=true},
    {name="name", id=2, kind='scalar', proto_type="string", optional=true, default_value="anonymous"},
    {name="retries", id=3, kind='scalar', proto_type="int32", optional=true, default_value=3},
    {name="lucky_numbers", id=4, kind='scalar', proto_type="int32", repeated=true, packed=true, options={packed = true}},
    {name="tags", id=5, kind='scalar', proto_type="string", repeated=true},
    {name="inner", id=6, kind='message', message=M.BenchPayload_Inner_descriptor, optional=true},
    {name="stats", id=7, kind='group', message=M.BenchPayload_Stats_descriptor, optional=true},
}
pb.finalize_message(M.BenchPayload_descriptor)
M.BenchPayload_fields = pb.field_names({
    id = "id",
    name = "name",
    retries = "retries",
    lucky_numbers = "lucky_numbers",
    tags = "tags",
    inner = "inner",
    stats = "stats",
})

-- Message: proto2_basic.BenchPayload.Stats
M.BenchPayload_Stats_descriptor.fields = {
    {name="latency_ns", id=8, kind='scalar', proto_type="int32", optional=true},
    {name="attempts", id=9, kind='scalar', proto_type="int32", optional=true},
}
pb.finalize_message(M.BenchPayload_Stats_descriptor)
M.BenchPayload_Stats_fields = pb.field_names({
    latency_ns = "latency_ns",
    attempts = "attempts",
})

-- Message: proto2_basic.BenchPayload.Inner
M.BenchPayload_Inner_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="string", required=true},
    {name="weight", id=2, kind='scalar', proto_type="int32", optional=true},
}
pb.finalize_message(M.BenchPayload_Inner_descriptor)
M.BenchPayload_Inner_fields = pb.field_names({
    key = "key",
    weight = "weight",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@alias proto2_basic.Defaults.Color integer

---@class proto2_basic.Defaults
---@field i? integer
---@field s? string
---@field b? boolean
---@field f? number
---@field d? number
---@field i64? integer
---@field u64? integer
---@field by? string
---@field color? proto2_basic.Defaults.Color

---@class proto2_basic.Cardinality
---@field r integer
---@field o? integer
---@field packed_default integer[]
---@field explicitly_packed integer[]
---@field explicitly_unpacked integer[]

---@class proto2_basic.Nested
---@field inner proto2_basic.Nested.Inner
---@field inner_opt? proto2_basic.Nested.Inner

---@class proto2_basic.Nested.Inner
---@field x integer

--- Proto2 legacy groups. Wire format uses SGROUP (3) / EGROUP (4) tag
--- pairs instead of a length-prefixed message body.
---@class proto2_basic.WithGroup
---@field singlegroup? proto2_basic.WithGroup.SingleGroup
---@field repgroup proto2_basic.WithGroup.RepGroup[]

---@class proto2_basic.WithGroup.SingleGroup
---@field a? integer
---@field s? string

---@class proto2_basic.WithGroup.RepGroup
---@field n? integer

--- Bench fixture exercising the proto2-only shapes: required scalar,
--- optional repeated, custom default, a `group` field, and a nested
--- message. Used by bench/bench.lua against both modes.
---@class proto2_basic.BenchPayload
---@field id integer
---@field name? string
---@field retries? integer
---@field lucky_numbers integer[]
---@field tags string[]
---@field inner? proto2_basic.BenchPayload.Inner
---@field stats? proto2_basic.BenchPayload.Stats

---@class proto2_basic.BenchPayload.Stats
---@field latency_ns? integer
---@field attempts? integer

---@class proto2_basic.BenchPayload.Inner
---@field key string
---@field weight? integer

---@param t? proto2_basic.Defaults
---@return proto2_basic.Defaults
function M.Defaults_new(t) return t or {} end
---@param t proto2_basic.Defaults
---@return string
function M.Defaults_encode(t) return pb.encode(M.Defaults_descriptor, t) end
---@param b string
---@return proto2_basic.Defaults
function M.Defaults_decode(b) return pb.decode(M.Defaults_descriptor, b) end
function M.Defaults_decode_unsafe(b) return pb.decode_unsafe(M.Defaults_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Defaults_decode_lazy(b) return pb.decode_lazy(M.Defaults_descriptor, b) end
---@param t proto2_basic.Defaults
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Defaults_text(t, opts) return pb.text.encode(M.Defaults_descriptor, t, opts) end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_i(t) return t.i ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_i(t) t.i = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_s(t) return t.s ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_s(t) t.s = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_b(t) return t.b ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_b(t) t.b = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_f(t) return t.f ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_f(t) t.f = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_d(t) return t.d ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_d(t) t.d = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_i64(t) return t.i64 ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_i64(t) t.i64 = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_u64(t) return t.u64 ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_u64(t) t.u64 = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_by(t) return t.by ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_by(t) t.by = nil end
---@param t proto2_basic.Defaults
---@return boolean
function M.Defaults_has_color(t) return t.color ~= nil end
---@param t proto2_basic.Defaults
function M.Defaults_clear_color(t) t.color = nil end

---@param t? proto2_basic.Cardinality
---@return proto2_basic.Cardinality
function M.Cardinality_new(t) return t or {} end
---@param t proto2_basic.Cardinality
---@return string
function M.Cardinality_encode(t) return pb.encode(M.Cardinality_descriptor, t) end
---@param b string
---@return proto2_basic.Cardinality
function M.Cardinality_decode(b) return pb.decode(M.Cardinality_descriptor, b) end
function M.Cardinality_decode_unsafe(b) return pb.decode_unsafe(M.Cardinality_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Cardinality_decode_lazy(b) return pb.decode_lazy(M.Cardinality_descriptor, b) end
---@param t proto2_basic.Cardinality
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Cardinality_text(t, opts) return pb.text.encode(M.Cardinality_descriptor, t, opts) end
---@param t proto2_basic.Cardinality
---@return boolean
function M.Cardinality_has_o(t) return t.o ~= nil end
---@param t proto2_basic.Cardinality
function M.Cardinality_clear_o(t) t.o = nil end

---@param t? proto2_basic.Nested
---@return proto2_basic.Nested
function M.Nested_new(t) return t or {} end
---@param t proto2_basic.Nested
---@return string
function M.Nested_encode(t) return pb.encode(M.Nested_descriptor, t) end
---@param b string
---@return proto2_basic.Nested
function M.Nested_decode(b) return pb.decode(M.Nested_descriptor, b) end
function M.Nested_decode_unsafe(b) return pb.decode_unsafe(M.Nested_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Nested_decode_lazy(b) return pb.decode_lazy(M.Nested_descriptor, b) end
---@param t proto2_basic.Nested
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Nested_text(t, opts) return pb.text.encode(M.Nested_descriptor, t, opts) end
---@param t proto2_basic.Nested
---@return boolean
function M.Nested_has_inner_opt(t) return t.inner_opt ~= nil end
---@param t proto2_basic.Nested
function M.Nested_clear_inner_opt(t) t.inner_opt = nil end

---@param t? proto2_basic.Nested.Inner
---@return proto2_basic.Nested.Inner
function M.Nested_Inner_new(t) return t or {} end
---@param t proto2_basic.Nested.Inner
---@return string
function M.Nested_Inner_encode(t) return pb.encode(M.Nested_Inner_descriptor, t) end
---@param b string
---@return proto2_basic.Nested.Inner
function M.Nested_Inner_decode(b) return pb.decode(M.Nested_Inner_descriptor, b) end
function M.Nested_Inner_decode_unsafe(b) return pb.decode_unsafe(M.Nested_Inner_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Nested_Inner_decode_lazy(b) return pb.decode_lazy(M.Nested_Inner_descriptor, b) end
---@param t proto2_basic.Nested.Inner
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Nested_Inner_text(t, opts) return pb.text.encode(M.Nested_Inner_descriptor, t, opts) end

---@param t? proto2_basic.WithGroup
---@return proto2_basic.WithGroup
function M.WithGroup_new(t) return t or {} end
---@param t proto2_basic.WithGroup
---@return string
function M.WithGroup_encode(t) return pb.encode(M.WithGroup_descriptor, t) end
---@param b string
---@return proto2_basic.WithGroup
function M.WithGroup_decode(b) return pb.decode(M.WithGroup_descriptor, b) end
function M.WithGroup_decode_unsafe(b) return pb.decode_unsafe(M.WithGroup_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.WithGroup_decode_lazy(b) return pb.decode_lazy(M.WithGroup_descriptor, b) end
---@param t proto2_basic.WithGroup
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.WithGroup_text(t, opts) return pb.text.encode(M.WithGroup_descriptor, t, opts) end
---@param t proto2_basic.WithGroup
---@return boolean
function M.WithGroup_has_singlegroup(t) return t.singlegroup ~= nil end
---@param t proto2_basic.WithGroup
function M.WithGroup_clear_singlegroup(t) t.singlegroup = nil end

---@param t? proto2_basic.WithGroup.SingleGroup
---@return proto2_basic.WithGroup.SingleGroup
function M.WithGroup_SingleGroup_new(t) return t or {} end
---@param t proto2_basic.WithGroup.SingleGroup
---@return string
function M.WithGroup_SingleGroup_encode(t) return pb.encode(M.WithGroup_SingleGroup_descriptor, t) end
---@param b string
---@return proto2_basic.WithGroup.SingleGroup
function M.WithGroup_SingleGroup_decode(b) return pb.decode(M.WithGroup_SingleGroup_descriptor, b) end
function M.WithGroup_SingleGroup_decode_unsafe(b) return pb.decode_unsafe(M.WithGroup_SingleGroup_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.WithGroup_SingleGroup_decode_lazy(b) return pb.decode_lazy(M.WithGroup_SingleGroup_descriptor, b) end
---@param t proto2_basic.WithGroup.SingleGroup
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.WithGroup_SingleGroup_text(t, opts) return pb.text.encode(M.WithGroup_SingleGroup_descriptor, t, opts) end
---@param t proto2_basic.WithGroup.SingleGroup
---@return boolean
function M.WithGroup_SingleGroup_has_a(t) return t.a ~= nil end
---@param t proto2_basic.WithGroup.SingleGroup
function M.WithGroup_SingleGroup_clear_a(t) t.a = nil end
---@param t proto2_basic.WithGroup.SingleGroup
---@return boolean
function M.WithGroup_SingleGroup_has_s(t) return t.s ~= nil end
---@param t proto2_basic.WithGroup.SingleGroup
function M.WithGroup_SingleGroup_clear_s(t) t.s = nil end

---@param t? proto2_basic.WithGroup.RepGroup
---@return proto2_basic.WithGroup.RepGroup
function M.WithGroup_RepGroup_new(t) return t or {} end
---@param t proto2_basic.WithGroup.RepGroup
---@return string
function M.WithGroup_RepGroup_encode(t) return pb.encode(M.WithGroup_RepGroup_descriptor, t) end
---@param b string
---@return proto2_basic.WithGroup.RepGroup
function M.WithGroup_RepGroup_decode(b) return pb.decode(M.WithGroup_RepGroup_descriptor, b) end
function M.WithGroup_RepGroup_decode_unsafe(b) return pb.decode_unsafe(M.WithGroup_RepGroup_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.WithGroup_RepGroup_decode_lazy(b) return pb.decode_lazy(M.WithGroup_RepGroup_descriptor, b) end
---@param t proto2_basic.WithGroup.RepGroup
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.WithGroup_RepGroup_text(t, opts) return pb.text.encode(M.WithGroup_RepGroup_descriptor, t, opts) end
---@param t proto2_basic.WithGroup.RepGroup
---@return boolean
function M.WithGroup_RepGroup_has_n(t) return t.n ~= nil end
---@param t proto2_basic.WithGroup.RepGroup
function M.WithGroup_RepGroup_clear_n(t) t.n = nil end

---@param t? proto2_basic.BenchPayload
---@return proto2_basic.BenchPayload
function M.BenchPayload_new(t) return t or {} end
---@param t proto2_basic.BenchPayload
---@return string
function M.BenchPayload_encode(t) return pb.encode(M.BenchPayload_descriptor, t) end
---@param b string
---@return proto2_basic.BenchPayload
function M.BenchPayload_decode(b) return pb.decode(M.BenchPayload_descriptor, b) end
function M.BenchPayload_decode_unsafe(b) return pb.decode_unsafe(M.BenchPayload_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.BenchPayload_decode_lazy(b) return pb.decode_lazy(M.BenchPayload_descriptor, b) end
---@param t proto2_basic.BenchPayload
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.BenchPayload_text(t, opts) return pb.text.encode(M.BenchPayload_descriptor, t, opts) end
---@param t proto2_basic.BenchPayload
---@return boolean
function M.BenchPayload_has_name(t) return t.name ~= nil end
---@param t proto2_basic.BenchPayload
function M.BenchPayload_clear_name(t) t.name = nil end
---@param t proto2_basic.BenchPayload
---@return boolean
function M.BenchPayload_has_retries(t) return t.retries ~= nil end
---@param t proto2_basic.BenchPayload
function M.BenchPayload_clear_retries(t) t.retries = nil end
---@param t proto2_basic.BenchPayload
---@return boolean
function M.BenchPayload_has_inner(t) return t.inner ~= nil end
---@param t proto2_basic.BenchPayload
function M.BenchPayload_clear_inner(t) t.inner = nil end
---@param t proto2_basic.BenchPayload
---@return boolean
function M.BenchPayload_has_stats(t) return t.stats ~= nil end
---@param t proto2_basic.BenchPayload
function M.BenchPayload_clear_stats(t) t.stats = nil end

---@param t? proto2_basic.BenchPayload.Stats
---@return proto2_basic.BenchPayload.Stats
function M.BenchPayload_Stats_new(t) return t or {} end
---@param t proto2_basic.BenchPayload.Stats
---@return string
function M.BenchPayload_Stats_encode(t) return pb.encode(M.BenchPayload_Stats_descriptor, t) end
---@param b string
---@return proto2_basic.BenchPayload.Stats
function M.BenchPayload_Stats_decode(b) return pb.decode(M.BenchPayload_Stats_descriptor, b) end
function M.BenchPayload_Stats_decode_unsafe(b) return pb.decode_unsafe(M.BenchPayload_Stats_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.BenchPayload_Stats_decode_lazy(b) return pb.decode_lazy(M.BenchPayload_Stats_descriptor, b) end
---@param t proto2_basic.BenchPayload.Stats
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.BenchPayload_Stats_text(t, opts) return pb.text.encode(M.BenchPayload_Stats_descriptor, t, opts) end
---@param t proto2_basic.BenchPayload.Stats
---@return boolean
function M.BenchPayload_Stats_has_latency_ns(t) return t.latency_ns ~= nil end
---@param t proto2_basic.BenchPayload.Stats
function M.BenchPayload_Stats_clear_latency_ns(t) t.latency_ns = nil end
---@param t proto2_basic.BenchPayload.Stats
---@return boolean
function M.BenchPayload_Stats_has_attempts(t) return t.attempts ~= nil end
---@param t proto2_basic.BenchPayload.Stats
function M.BenchPayload_Stats_clear_attempts(t) t.attempts = nil end

---@param t? proto2_basic.BenchPayload.Inner
---@return proto2_basic.BenchPayload.Inner
function M.BenchPayload_Inner_new(t) return t or {} end
---@param t proto2_basic.BenchPayload.Inner
---@return string
function M.BenchPayload_Inner_encode(t) return pb.encode(M.BenchPayload_Inner_descriptor, t) end
---@param b string
---@return proto2_basic.BenchPayload.Inner
function M.BenchPayload_Inner_decode(b) return pb.decode(M.BenchPayload_Inner_descriptor, b) end
function M.BenchPayload_Inner_decode_unsafe(b) return pb.decode_unsafe(M.BenchPayload_Inner_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.BenchPayload_Inner_decode_lazy(b) return pb.decode_lazy(M.BenchPayload_Inner_descriptor, b) end
---@param t proto2_basic.BenchPayload.Inner
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.BenchPayload_Inner_text(t, opts) return pb.text.encode(M.BenchPayload_Inner_descriptor, t, opts) end
---@param t proto2_basic.BenchPayload.Inner
---@return boolean
function M.BenchPayload_Inner_has_weight(t) return t.weight ~= nil end
---@param t proto2_basic.BenchPayload.Inner
function M.BenchPayload_Inner_clear_weight(t) t.weight = nil end

-- Extension: proto2_basic.ext_count extends proto2_basic.BenchPayload (tag 100)
pb.register_extension(M.BenchPayload_descriptor, {name="ext_count", full_name="proto2_basic.ext_count", id=100, kind='scalar', proto_type="int32", optional=true})
-- Extension: proto2_basic.ext_label extends proto2_basic.BenchPayload (tag 101)
pb.register_extension(M.BenchPayload_descriptor, {name="ext_label", full_name="proto2_basic.ext_label", id=101, kind='scalar', proto_type="string", optional=true})

-- Serialized FileDescriptorProto of proto2_basic.proto (source_code_info
-- stripped), registered with pb.descriptors for server reflection.
M._file_descriptor = table.concat({
    "\x0a\x12proto2_basic.proto\x12\x0cproto2_basic\"\x9e\x02\x0a\x08Defaults\x12",
    "\x10\x0a\x01i\x18\x01 \x01(\x05:\x0217R\x01i\x12\x13\x0a\x01s\x18\x02 \x01(\x09:\x05helloR\x01s\x12\x12\x0a\x01b\x18\x03 \x01(",
    "\x08:\x04trueR\x01b\x12\x11\x0a\x01f\x18\x04 \x01(\x02:\x033.5R\x01f\x12\x11\x0a\x01d\x18\x05 \x01(\x01:\x031.5R\x01d",
    "\x12\x1f\x0a\x03i64\x18\x06 \x01(\x03:\x0d1234567890123R\x03i64\x12\x14\x0a\x03u64\x18\x07 \x01(\x04:\x02",
    "17R\x03u64\x12\x18\x0a\x02by\x18\x08 \x01(\x0c:\x08\\000\\377R\x02by\x129\x0a\x05color\x18\x09 \x01(\x0e",
    "2\x1c.proto2_basic.Defaults.Color:\x05GREENR\x05color\"%\x0a\x05",
    "Color\x12\x07\x0a\x03RED\x10\x00\x12\x09\x0a\x05GREEN\x10\x01\x12\x08\x0a\x04BLUE\x10\x02\"\xb6\x01\x0a\x0bCardinal",
    "ity\x12\x0c\x0a\x01r\x18\x01 \x02(\x05R\x01r\x12\x0c\x0a\x01o\x18\x02 \x01(\x05R\x01o\x12%\x0a\x0epacked_defaul",
    "t\x18\x03 \x03(\x05R\x0dpackedDefault\x12/\x0a\x11explicitly_packed\x18\x04 \x03(",
    "\x05B\x02\x10\x01R\x10explicitlyPacked\x123\x0a\x13explicitly_unpacked\x18\x05",
    " \x03(\x05B\x02\x10\x00R\x12explicitlyUnpacked\"\x8a\x01\x0a\x06Nested\x120\x0a\x05inner",
    "\x18\x01 \x02(\x0b2\x1a.proto2_basic.Nested.InnerR\x05inner\x127\x0a\x09inn",
    "er_opt\x18\x02 \x01(\x0b2\x1a.proto2_basic.Nested.InnerR\x08innerO",
    "pt\x1a\x15\x0a\x05Inner\x12\x0c\x0a\x01x\x18\x01 \x02(\x05R\x01x\"\xd5\x01\x0a\x09WithGroup\x12E\x0a\x0bsingl",
    "egroup\x18\x01 \x01(\x0a2#.proto2_basic.WithGroup.SingleGrou",
    "pR\x0bsinglegroup\x12<\x0a\x08repgroup\x18\x04 \x03(\x0a2 .proto2_basic.",
    "WithGroup.RepGroupR\x08repgroup\x1a)\x0a\x0bSingleGroup\x12\x0c\x0a\x01a",
    "\x18\x02 \x01(\x05R\x01a\x12\x0c\x0a\x01s\x18\x03 \x01(\x09R\x01s\x1a\x18\x0a\x08RepGroup\x12\x0c\x0a\x01n\x18\x05 \x01(\x05R\x01",
    "n\"\x85\x03\x0a\x0cBenchPayload\x12\x0e\x0a\x02id\x18\x01 \x02(\x05R\x02id\x12\x1d\x0a\x04name\x18\x02 \x01(\x09",
    ":\x09anonymousR\x04name\x12\x1b\x0a\x07retries\x18\x03 \x01(\x05:\x013R\x07retries\x12'",
    "\x0a\x0dlucky_numbers\x18\x04 \x03(\x05B\x02\x10\x01R\x0cluckyNumbers\x12\x12\x0a\x04tags\x18",
    "\x05 \x03(\x09R\x04tags\x126\x0a\x05inner\x18\x06 \x01(\x0b2 .proto2_basic.BenchP",
    "ayload.InnerR\x05inner\x126\x0a\x05stats\x18\x07 \x01(\x0a2 .proto2_basi",
    "c.BenchPayload.StatsR\x05stats\x1aB\x0a\x05Stats\x12\x1d\x0a\x0alatency_",
    "ns\x18\x08 \x01(\x05R\x09latencyNs\x12\x1a\x0a\x08attempts\x18\x09 \x01(\x05R\x08attempts\x1a",
    "1\x0a\x05Inner\x12\x10\x0a\x03key\x18\x01 \x02(\x09R\x03key\x12\x16\x0a\x06weight\x18\x02 \x01(\x05R\x06weig",
    "ht*\x05\x08d\x10\xc8\x01:7\x0a\x09ext_count\x12\x1a.proto2_basic.BenchPaylo",
    "ad\x18d \x01(\x05R\x08extCount:7\x0a\x09ext_label\x12\x1a.proto2_basic.B",
    "enchPayload\x18e \x01(\x09R\x08extLabel",
})
pb.descriptors.register(M._file_descriptor)

return M
