-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: test_messages_proto3.proto
-- syntax: proto3
-- package: protobuf_test_messages.proto3

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {cc_enable_arenas = true, go_package = "tarantoolpb_synthetic/test_messages_proto3", java_package = "com.google.protobuf_test_messages.proto3", objc_class_prefix = "Proto3", optimize_for = "SPEED"}

-- Enum: protobuf_test_messages.proto3.ForeignEnum
M.ForeignEnum_descriptor = pb.enum("protobuf_test_messages.proto3.ForeignEnum", {
    FOREIGN_FOO = 0,
    FOREIGN_BAR = 1,
    FOREIGN_BAZ = 2,
})
M.ForeignEnum = M.ForeignEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
M.TestAllTypesProto3_NestedEnum_descriptor = pb.enum("protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum", {
    FOO = 0,
    BAR = 1,
    BAZ = 2,
    NEG = -1,
})
M.TestAllTypesProto3_NestedEnum = M.TestAllTypesProto3_NestedEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum
M.TestAllTypesProto3_AliasedEnum_descriptor = pb.enum("protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum", {
    ALIAS_FOO = 0,
    ALIAS_BAR = 1,
    ALIAS_BAZ = 2,
    MOO = 2,
    moo = 2,
    bAz = 2,
})
M.TestAllTypesProto3_AliasedEnum_descriptor.options = {allow_alias = true}
M.TestAllTypesProto3_AliasedEnum = M.TestAllTypesProto3_AliasedEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.EnumOnlyProto3.Bool
M.EnumOnlyProto3_Bool_descriptor = pb.enum("protobuf_test_messages.proto3.EnumOnlyProto3.Bool", {
    kFalse = 0,
    kTrue = 1,
})
M.EnumOnlyProto3_Bool = M.EnumOnlyProto3_Bool_descriptor.by_name

-- Pre-declare message descriptors so cross-references resolve.
M.TestAllTypesProto3_descriptor = {name = "protobuf_test_messages.proto3.TestAllTypesProto3"}
M.TestAllTypesProto3_NestedMessage_descriptor = {name = "protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage"}
M.ForeignMessage_descriptor = {name = "protobuf_test_messages.proto3.ForeignMessage"}
M.NullHypothesisProto3_descriptor = {name = "protobuf_test_messages.proto3.NullHypothesisProto3"}
M.EnumOnlyProto3_descriptor = {name = "protobuf_test_messages.proto3.EnumOnlyProto3"}

-- Message: protobuf_test_messages.proto3.TestAllTypesProto3
M.TestAllTypesProto3_descriptor.fields = {
    {name="optional_int32", id=1, kind='scalar', proto_type="int32"},
    {name="optional_int64", id=2, kind='scalar', proto_type="int64"},
    {name="optional_uint32", id=3, kind='scalar', proto_type="uint32"},
    {name="optional_uint64", id=4, kind='scalar', proto_type="uint64"},
    {name="optional_sint32", id=5, kind='scalar', proto_type="sint32"},
    {name="optional_sint64", id=6, kind='scalar', proto_type="sint64"},
    {name="optional_fixed32", id=7, kind='scalar', proto_type="fixed32"},
    {name="optional_fixed64", id=8, kind='scalar', proto_type="fixed64"},
    {name="optional_sfixed32", id=9, kind='scalar', proto_type="sfixed32"},
    {name="optional_sfixed64", id=10, kind='scalar', proto_type="sfixed64"},
    {name="optional_float", id=11, kind='scalar', proto_type="float"},
    {name="optional_double", id=12, kind='scalar', proto_type="double"},
    {name="optional_bool", id=13, kind='scalar', proto_type="bool"},
    {name="optional_string", id=14, kind='scalar', proto_type="string"},
    {name="optional_bytes", id=15, kind='scalar', proto_type="bytes"},
    {name="optional_nested_message", id=18, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor},
    {name="optional_foreign_message", id=19, kind='message', message=M.ForeignMessage_descriptor},
    {name="optional_nested_enum", id=21, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor},
    {name="optional_foreign_enum", id=22, kind='enum', enum=M.ForeignEnum_descriptor},
    {name="optional_aliased_enum", id=23, kind='enum', enum=M.TestAllTypesProto3_AliasedEnum_descriptor},
    {name="optional_string_piece", id=24, kind='scalar', proto_type="string", options={ctype = "STRING_PIECE"}},
    {name="optional_cord", id=25, kind='scalar', proto_type="string", options={ctype = "CORD"}},
    {name="recursive_message", id=27, kind='message', message=M.TestAllTypesProto3_descriptor},
    {name="repeated_int32", id=31, kind='scalar', proto_type="int32", repeated=true, packed=true},
    {name="repeated_int64", id=32, kind='scalar', proto_type="int64", repeated=true, packed=true},
    {name="repeated_uint32", id=33, kind='scalar', proto_type="uint32", repeated=true, packed=true},
    {name="repeated_uint64", id=34, kind='scalar', proto_type="uint64", repeated=true, packed=true},
    {name="repeated_sint32", id=35, kind='scalar', proto_type="sint32", repeated=true, packed=true},
    {name="repeated_sint64", id=36, kind='scalar', proto_type="sint64", repeated=true, packed=true},
    {name="repeated_fixed32", id=37, kind='scalar', proto_type="fixed32", repeated=true, packed=true},
    {name="repeated_fixed64", id=38, kind='scalar', proto_type="fixed64", repeated=true, packed=true},
    {name="repeated_sfixed32", id=39, kind='scalar', proto_type="sfixed32", repeated=true, packed=true},
    {name="repeated_sfixed64", id=40, kind='scalar', proto_type="sfixed64", repeated=true, packed=true},
    {name="repeated_float", id=41, kind='scalar', proto_type="float", repeated=true, packed=true},
    {name="repeated_double", id=42, kind='scalar', proto_type="double", repeated=true, packed=true},
    {name="repeated_bool", id=43, kind='scalar', proto_type="bool", repeated=true, packed=true},
    {name="repeated_string", id=44, kind='scalar', proto_type="string", repeated=true},
    {name="repeated_bytes", id=45, kind='scalar', proto_type="bytes", repeated=true},
    {name="repeated_nested_message", id=48, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor, repeated=true},
    {name="repeated_foreign_message", id=49, kind='message', message=M.ForeignMessage_descriptor, repeated=true},
    {name="repeated_nested_enum", id=51, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=true},
    {name="repeated_foreign_enum", id=52, kind='enum', enum=M.ForeignEnum_descriptor, repeated=true, packed=true},
    {name="repeated_string_piece", id=54, kind='scalar', proto_type="string", repeated=true, options={ctype = "STRING_PIECE"}},
    {name="repeated_cord", id=55, kind='scalar', proto_type="string", repeated=true, options={ctype = "CORD"}},
    {name="packed_int32", id=75, kind='scalar', proto_type="int32", repeated=true, packed=true, options={packed = true}},
    {name="packed_int64", id=76, kind='scalar', proto_type="int64", repeated=true, packed=true, options={packed = true}},
    {name="packed_uint32", id=77, kind='scalar', proto_type="uint32", repeated=true, packed=true, options={packed = true}},
    {name="packed_uint64", id=78, kind='scalar', proto_type="uint64", repeated=true, packed=true, options={packed = true}},
    {name="packed_sint32", id=79, kind='scalar', proto_type="sint32", repeated=true, packed=true, options={packed = true}},
    {name="packed_sint64", id=80, kind='scalar', proto_type="sint64", repeated=true, packed=true, options={packed = true}},
    {name="packed_fixed32", id=81, kind='scalar', proto_type="fixed32", repeated=true, packed=true, options={packed = true}},
    {name="packed_fixed64", id=82, kind='scalar', proto_type="fixed64", repeated=true, packed=true, options={packed = true}},
    {name="packed_sfixed32", id=83, kind='scalar', proto_type="sfixed32", repeated=true, packed=true, options={packed = true}},
    {name="packed_sfixed64", id=84, kind='scalar', proto_type="sfixed64", repeated=true, packed=true, options={packed = true}},
    {name="packed_float", id=85, kind='scalar', proto_type="float", repeated=true, packed=true, options={packed = true}},
    {name="packed_double", id=86, kind='scalar', proto_type="double", repeated=true, packed=true, options={packed = true}},
    {name="packed_bool", id=87, kind='scalar', proto_type="bool", repeated=true, packed=true, options={packed = true}},
    {name="packed_nested_enum", id=88, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=true, options={packed = true}},
    {name="unpacked_int32", id=89, kind='scalar', proto_type="int32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_int64", id=90, kind='scalar', proto_type="int64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_uint32", id=91, kind='scalar', proto_type="uint32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_uint64", id=92, kind='scalar', proto_type="uint64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sint32", id=93, kind='scalar', proto_type="sint32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sint64", id=94, kind='scalar', proto_type="sint64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_fixed32", id=95, kind='scalar', proto_type="fixed32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_fixed64", id=96, kind='scalar', proto_type="fixed64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sfixed32", id=97, kind='scalar', proto_type="sfixed32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sfixed64", id=98, kind='scalar', proto_type="sfixed64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_float", id=99, kind='scalar', proto_type="float", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_double", id=100, kind='scalar', proto_type="double", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_bool", id=101, kind='scalar', proto_type="bool", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_nested_enum", id=102, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=false, options={packed = false}},
    {name="map_int32_int32", id=56, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="int32"}},
    {name="map_int64_int64", id=57, kind='map', key={kind='scalar', proto_type="int64"}, value={kind='scalar', proto_type="int64"}},
    {name="map_uint32_uint32", id=58, kind='map', key={kind='scalar', proto_type="uint32"}, value={kind='scalar', proto_type="uint32"}},
    {name="map_uint64_uint64", id=59, kind='map', key={kind='scalar', proto_type="uint64"}, value={kind='scalar', proto_type="uint64"}},
    {name="map_sint32_sint32", id=60, kind='map', key={kind='scalar', proto_type="sint32"}, value={kind='scalar', proto_type="sint32"}},
    {name="map_sint64_sint64", id=61, kind='map', key={kind='scalar', proto_type="sint64"}, value={kind='scalar', proto_type="sint64"}},
    {name="map_fixed32_fixed32", id=62, kind='map', key={kind='scalar', proto_type="fixed32"}, value={kind='scalar', proto_type="fixed32"}},
    {name="map_fixed64_fixed64", id=63, kind='map', key={kind='scalar', proto_type="fixed64"}, value={kind='scalar', proto_type="fixed64"}},
    {name="map_sfixed32_sfixed32", id=64, kind='map', key={kind='scalar', proto_type="sfixed32"}, value={kind='scalar', proto_type="sfixed32"}},
    {name="map_sfixed64_sfixed64", id=65, kind='map', key={kind='scalar', proto_type="sfixed64"}, value={kind='scalar', proto_type="sfixed64"}},
    {name="map_int32_float", id=66, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="float"}},
    {name="map_int32_double", id=67, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="double"}},
    {name="map_bool_bool", id=68, kind='map', key={kind='scalar', proto_type="bool"}, value={kind='scalar', proto_type="bool"}},
    {name="map_string_string", id=69, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="string"}},
    {name="map_string_bytes", id=70, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="bytes"}},
    {name="map_string_nested_message", id=71, kind='map', key={kind='scalar', proto_type="string"}, value={kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor}},
    {name="map_string_foreign_message", id=72, kind='map', key={kind='scalar', proto_type="string"}, value={kind='message', message=M.ForeignMessage_descriptor}},
    {name="map_string_nested_enum", id=73, kind='map', key={kind='scalar', proto_type="string"}, value={kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor}},
    {name="map_string_foreign_enum", id=74, kind='map', key={kind='scalar', proto_type="string"}, value={kind='enum', enum=M.ForeignEnum_descriptor}},
    {name="oneof_uint32", id=111, kind='scalar', proto_type="uint32", oneof="oneof_field"},
    {name="oneof_nested_message", id=112, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor, oneof="oneof_field"},
    {name="oneof_string", id=113, kind='scalar', proto_type="string", oneof="oneof_field"},
    {name="oneof_bytes", id=114, kind='scalar', proto_type="bytes", oneof="oneof_field"},
    {name="oneof_bool", id=115, kind='scalar', proto_type="bool", oneof="oneof_field"},
    {name="oneof_uint64", id=116, kind='scalar', proto_type="uint64", oneof="oneof_field"},
    {name="oneof_float", id=117, kind='scalar', proto_type="float", oneof="oneof_field"},
    {name="oneof_double", id=118, kind='scalar', proto_type="double", oneof="oneof_field"},
    {name="oneof_enum", id=119, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, oneof="oneof_field"},
    {name="oneof_null_value", id=120, kind='enum', enum=pb.wkt.NullValue_descriptor, oneof="oneof_field"},
    {name="optional_bool_wrapper", id=201, kind='message', message=pb.wkt.BoolValue_descriptor},
    {name="optional_int32_wrapper", id=202, kind='message', message=pb.wkt.Int32Value_descriptor},
    {name="optional_int64_wrapper", id=203, kind='message', message=pb.wkt.Int64Value_descriptor},
    {name="optional_uint32_wrapper", id=204, kind='message', message=pb.wkt.UInt32Value_descriptor},
    {name="optional_uint64_wrapper", id=205, kind='message', message=pb.wkt.UInt64Value_descriptor},
    {name="optional_float_wrapper", id=206, kind='message', message=pb.wkt.FloatValue_descriptor},
    {name="optional_double_wrapper", id=207, kind='message', message=pb.wkt.DoubleValue_descriptor},
    {name="optional_string_wrapper", id=208, kind='message', message=pb.wkt.StringValue_descriptor},
    {name="optional_bytes_wrapper", id=209, kind='message', message=pb.wkt.BytesValue_descriptor},
    {name="repeated_bool_wrapper", id=211, kind='message', message=pb.wkt.BoolValue_descriptor, repeated=true},
    {name="repeated_int32_wrapper", id=212, kind='message', message=pb.wkt.Int32Value_descriptor, repeated=true},
    {name="repeated_int64_wrapper", id=213, kind='message', message=pb.wkt.Int64Value_descriptor, repeated=true},
    {name="repeated_uint32_wrapper", id=214, kind='message', message=pb.wkt.UInt32Value_descriptor, repeated=true},
    {name="repeated_uint64_wrapper", id=215, kind='message', message=pb.wkt.UInt64Value_descriptor, repeated=true},
    {name="repeated_float_wrapper", id=216, kind='message', message=pb.wkt.FloatValue_descriptor, repeated=true},
    {name="repeated_double_wrapper", id=217, kind='message', message=pb.wkt.DoubleValue_descriptor, repeated=true},
    {name="repeated_string_wrapper", id=218, kind='message', message=pb.wkt.StringValue_descriptor, repeated=true},
    {name="repeated_bytes_wrapper", id=219, kind='message', message=pb.wkt.BytesValue_descriptor, repeated=true},
    {name="optional_duration", id=301, kind='message', message=pb.wkt.Duration_descriptor},
    {name="optional_timestamp", id=302, kind='message', message=pb.wkt.Timestamp_descriptor},
    {name="optional_field_mask", id=303, kind='message', message=pb.wkt.FieldMask_descriptor},
    {name="optional_struct", id=304, kind='message', message=pb.wkt.Struct_descriptor},
    {name="optional_any", id=305, kind='message', message=pb.wkt.Any_descriptor},
    {name="optional_value", id=306, kind='message', message=pb.wkt.Value_descriptor},
    {name="optional_null_value", id=307, kind='enum', enum=pb.wkt.NullValue_descriptor},
    {name="optional_empty", id=308, kind='message', message=pb.wkt.Empty_descriptor},
    {name="repeated_duration", id=311, kind='message', message=pb.wkt.Duration_descriptor, repeated=true},
    {name="repeated_timestamp", id=312, kind='message', message=pb.wkt.Timestamp_descriptor, repeated=true},
    {name="repeated_fieldmask", id=313, kind='message', message=pb.wkt.FieldMask_descriptor, repeated=true},
    {name="repeated_struct", id=324, kind='message', message=pb.wkt.Struct_descriptor, repeated=true},
    {name="repeated_any", id=315, kind='message', message=pb.wkt.Any_descriptor, repeated=true},
    {name="repeated_value", id=316, kind='message', message=pb.wkt.Value_descriptor, repeated=true},
    {name="repeated_list_value", id=317, kind='message', message=pb.wkt.ListValue_descriptor, repeated=true},
    {name="repeated_empty", id=318, kind='message', message=pb.wkt.Empty_descriptor, repeated=true},
    {name="fieldname1", id=401, kind='scalar', proto_type="int32"},
    {name="field_name2", id=402, kind='scalar', proto_type="int32"},
    {name="_field_name3", id=403, kind='scalar', proto_type="int32"},
    {name="field__name4_", id=404, kind='scalar', proto_type="int32"},
    {name="field0name5", id=405, kind='scalar', proto_type="int32"},
    {name="field_0_name6", id=406, kind='scalar', proto_type="int32"},
    {name="fieldName7", id=407, kind='scalar', proto_type="int32"},
    {name="FieldName8", id=408, kind='scalar', proto_type="int32"},
    {name="field_Name9", id=409, kind='scalar', proto_type="int32"},
    {name="Field_Name10", id=410, kind='scalar', proto_type="int32"},
    {name="FIELD_NAME11", id=411, kind='scalar', proto_type="int32"},
    {name="FIELD_name12", id=412, kind='scalar', proto_type="int32"},
    {name="__field_name13", id=413, kind='scalar', proto_type="int32"},
    {name="__Field_name14", id=414, kind='scalar', proto_type="int32"},
    {name="field__name15", id=415, kind='scalar', proto_type="int32"},
    {name="field__Name16", id=416, kind='scalar', proto_type="int32"},
    {name="field_name17__", id=417, kind='scalar', proto_type="int32"},
    {name="Field_name18__", id=418, kind='scalar', proto_type="int32"},
}
M.TestAllTypesProto3_descriptor.oneofs = {
    oneof_field = {"oneof_uint32", "oneof_nested_message", "oneof_string", "oneof_bytes", "oneof_bool", "oneof_uint64", "oneof_float", "oneof_double", "oneof_enum", "oneof_null_value"},
}
M.TestAllTypesProto3_descriptor.reserved_names = {
    ["reserved_field"] = true,
}
pb.finalize_message(M.TestAllTypesProto3_descriptor)
M.TestAllTypesProto3_fields = pb.field_names({
    optional_int32 = "optional_int32",
    optional_int64 = "optional_int64",
    optional_uint32 = "optional_uint32",
    optional_uint64 = "optional_uint64",
    optional_sint32 = "optional_sint32",
    optional_sint64 = "optional_sint64",
    optional_fixed32 = "optional_fixed32",
    optional_fixed64 = "optional_fixed64",
    optional_sfixed32 = "optional_sfixed32",
    optional_sfixed64 = "optional_sfixed64",
    optional_float = "optional_float",
    optional_double = "optional_double",
    optional_bool = "optional_bool",
    optional_string = "optional_string",
    optional_bytes = "optional_bytes",
    optional_nested_message = "optional_nested_message",
    optional_foreign_message = "optional_foreign_message",
    optional_nested_enum = "optional_nested_enum",
    optional_foreign_enum = "optional_foreign_enum",
    optional_aliased_enum = "optional_aliased_enum",
    optional_string_piece = "optional_string_piece",
    optional_cord = "optional_cord",
    recursive_message = "recursive_message",
    repeated_int32 = "repeated_int32",
    repeated_int64 = "repeated_int64",
    repeated_uint32 = "repeated_uint32",
    repeated_uint64 = "repeated_uint64",
    repeated_sint32 = "repeated_sint32",
    repeated_sint64 = "repeated_sint64",
    repeated_fixed32 = "repeated_fixed32",
    repeated_fixed64 = "repeated_fixed64",
    repeated_sfixed32 = "repeated_sfixed32",
    repeated_sfixed64 = "repeated_sfixed64",
    repeated_float = "repeated_float",
    repeated_double = "repeated_double",
    repeated_bool = "repeated_bool",
    repeated_string = "repeated_string",
    repeated_bytes = "repeated_bytes",
    repeated_nested_message = "repeated_nested_message",
    repeated_foreign_message = "repeated_foreign_message",
    repeated_nested_enum = "repeated_nested_enum",
    repeated_foreign_enum = "repeated_foreign_enum",
    repeated_string_piece = "repeated_string_piece",
    repeated_cord = "repeated_cord",
    packed_int32 = "packed_int32",
    packed_int64 = "packed_int64",
    packed_uint32 = "packed_uint32",
    packed_uint64 = "packed_uint64",
    packed_sint32 = "packed_sint32",
    packed_sint64 = "packed_sint64",
    packed_fixed32 = "packed_fixed32",
    packed_fixed64 = "packed_fixed64",
    packed_sfixed32 = "packed_sfixed32",
    packed_sfixed64 = "packed_sfixed64",
    packed_float = "packed_float",
    packed_double = "packed_double",
    packed_bool = "packed_bool",
    packed_nested_enum = "packed_nested_enum",
    unpacked_int32 = "unpacked_int32",
    unpacked_int64 = "unpacked_int64",
    unpacked_uint32 = "unpacked_uint32",
    unpacked_uint64 = "unpacked_uint64",
    unpacked_sint32 = "unpacked_sint32",
    unpacked_sint64 = "unpacked_sint64",
    unpacked_fixed32 = "unpacked_fixed32",
    unpacked_fixed64 = "unpacked_fixed64",
    unpacked_sfixed32 = "unpacked_sfixed32",
    unpacked_sfixed64 = "unpacked_sfixed64",
    unpacked_float = "unpacked_float",
    unpacked_double = "unpacked_double",
    unpacked_bool = "unpacked_bool",
    unpacked_nested_enum = "unpacked_nested_enum",
    map_int32_int32 = "map_int32_int32",
    map_int64_int64 = "map_int64_int64",
    map_uint32_uint32 = "map_uint32_uint32",
    map_uint64_uint64 = "map_uint64_uint64",
    map_sint32_sint32 = "map_sint32_sint32",
    map_sint64_sint64 = "map_sint64_sint64",
    map_fixed32_fixed32 = "map_fixed32_fixed32",
    map_fixed64_fixed64 = "map_fixed64_fixed64",
    map_sfixed32_sfixed32 = "map_sfixed32_sfixed32",
    map_sfixed64_sfixed64 = "map_sfixed64_sfixed64",
    map_int32_float = "map_int32_float",
    map_int32_double = "map_int32_double",
    map_bool_bool = "map_bool_bool",
    map_string_string = "map_string_string",
    map_string_bytes = "map_string_bytes",
    map_string_nested_message = "map_string_nested_message",
    map_string_foreign_message = "map_string_foreign_message",
    map_string_nested_enum = "map_string_nested_enum",
    map_string_foreign_enum = "map_string_foreign_enum",
    oneof_uint32 = "oneof_uint32",
    oneof_nested_message = "oneof_nested_message",
    oneof_string = "oneof_string",
    oneof_bytes = "oneof_bytes",
    oneof_bool = "oneof_bool",
    oneof_uint64 = "oneof_uint64",
    oneof_float = "oneof_float",
    oneof_double = "oneof_double",
    oneof_enum = "oneof_enum",
    oneof_null_value = "oneof_null_value",
    optional_bool_wrapper = "optional_bool_wrapper",
    optional_int32_wrapper = "optional_int32_wrapper",
    optional_int64_wrapper = "optional_int64_wrapper",
    optional_uint32_wrapper = "optional_uint32_wrapper",
    optional_uint64_wrapper = "optional_uint64_wrapper",
    optional_float_wrapper = "optional_float_wrapper",
    optional_double_wrapper = "optional_double_wrapper",
    optional_string_wrapper = "optional_string_wrapper",
    optional_bytes_wrapper = "optional_bytes_wrapper",
    repeated_bool_wrapper = "repeated_bool_wrapper",
    repeated_int32_wrapper = "repeated_int32_wrapper",
    repeated_int64_wrapper = "repeated_int64_wrapper",
    repeated_uint32_wrapper = "repeated_uint32_wrapper",
    repeated_uint64_wrapper = "repeated_uint64_wrapper",
    repeated_float_wrapper = "repeated_float_wrapper",
    repeated_double_wrapper = "repeated_double_wrapper",
    repeated_string_wrapper = "repeated_string_wrapper",
    repeated_bytes_wrapper = "repeated_bytes_wrapper",
    optional_duration = "optional_duration",
    optional_timestamp = "optional_timestamp",
    optional_field_mask = "optional_field_mask",
    optional_struct = "optional_struct",
    optional_any = "optional_any",
    optional_value = "optional_value",
    optional_null_value = "optional_null_value",
    optional_empty = "optional_empty",
    repeated_duration = "repeated_duration",
    repeated_timestamp = "repeated_timestamp",
    repeated_fieldmask = "repeated_fieldmask",
    repeated_struct = "repeated_struct",
    repeated_any = "repeated_any",
    repeated_value = "repeated_value",
    repeated_list_value = "repeated_list_value",
    repeated_empty = "repeated_empty",
    fieldname1 = "fieldname1",
    field_name2 = "field_name2",
    _field_name3 = "_field_name3",
    field__name4_ = "field__name4_",
    field0name5 = "field0name5",
    field_0_name6 = "field_0_name6",
    fieldName7 = "fieldName7",
    FieldName8 = "FieldName8",
    field_Name9 = "field_Name9",
    Field_Name10 = "Field_Name10",
    FIELD_NAME11 = "FIELD_NAME11",
    FIELD_name12 = "FIELD_name12",
    __field_name13 = "__field_name13",
    __Field_name14 = "__Field_name14",
    field__name15 = "field__name15",
    field__Name16 = "field__Name16",
    field_name17__ = "field_name17__",
    Field_name18__ = "Field_name18__",
})
M.TestAllTypesProto3_oneofs = pb.field_names({
    oneof_field = "oneof_field",
})

-- Message: protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
M.TestAllTypesProto3_NestedMessage_descriptor.fields = {
    {name="a", id=1, kind='scalar', proto_type="int32"},
    {name="corecursive", id=2, kind='message', message=M.TestAllTypesProto3_descriptor},
}
pb.finalize_message(M.TestAllTypesProto3_NestedMessage_descriptor)
M.TestAllTypesProto3_NestedMessage_fields = pb.field_names({
    a = "a",
    corecursive = "corecursive",
})

-- Message: protobuf_test_messages.proto3.ForeignMessage
M.ForeignMessage_descriptor.fields = {
    {name="c", id=1, kind='scalar', proto_type="int32"},
}
pb.finalize_message(M.ForeignMessage_descriptor)
M.ForeignMessage_fields = pb.field_names({
    c = "c",
})

-- Message: protobuf_test_messages.proto3.NullHypothesisProto3
M.NullHypothesisProto3_descriptor.fields = {
}
pb.finalize_message(M.NullHypothesisProto3_descriptor)

-- Message: protobuf_test_messages.proto3.EnumOnlyProto3
M.EnumOnlyProto3_descriptor.fields = {
}
pb.finalize_message(M.EnumOnlyProto3_descriptor)

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@alias protobuf_test_messages.proto3.ForeignEnum integer
---@alias protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum integer
---@alias protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum integer
---@alias protobuf_test_messages.proto3.EnumOnlyProto3.Bool integer

--- This proto includes every type of field in both singular and repeated
--- forms.
---
--- Also, crucially, all messages and enums in this file are eventually
--- submessages of this message.  So for example, a fuzz test of TestAllTypes
--- could trigger bugs that occur in any message type in this file.  We verify
--- this stays true in a unit test.
---@class protobuf_test_messages.proto3.TestAllTypesProto3
---@field optional_int32 integer @ Singular test [kotlin] comment
---@field optional_int64 integer
---@field optional_uint32 integer
---@field optional_uint64 integer
---@field optional_sint32 integer
---@field optional_sint64 integer
---@field optional_fixed32 integer
---@field optional_fixed64 integer
---@field optional_sfixed32 integer
---@field optional_sfixed64 integer
---@field optional_float number
---@field optional_double number
---@field optional_bool boolean
---@field optional_string string
---@field optional_bytes string
---@field optional_nested_message protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field optional_foreign_message protobuf_test_messages.proto3.ForeignMessage
---@field optional_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
---@field optional_foreign_enum protobuf_test_messages.proto3.ForeignEnum
---@field optional_aliased_enum protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum
---@field optional_string_piece string
---@field optional_cord string
---@field recursive_message protobuf_test_messages.proto3.TestAllTypesProto3
---@field repeated_int32 integer[] @ Repeated
---@field repeated_int64 integer[]
---@field repeated_uint32 integer[]
---@field repeated_uint64 integer[]
---@field repeated_sint32 integer[]
---@field repeated_sint64 integer[]
---@field repeated_fixed32 integer[]
---@field repeated_fixed64 integer[]
---@field repeated_sfixed32 integer[]
---@field repeated_sfixed64 integer[]
---@field repeated_float number[]
---@field repeated_double number[]
---@field repeated_bool boolean[]
---@field repeated_string string[]
---@field repeated_bytes string[]
---@field repeated_nested_message protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage[]
---@field repeated_foreign_message protobuf_test_messages.proto3.ForeignMessage[]
---@field repeated_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field repeated_foreign_enum protobuf_test_messages.proto3.ForeignEnum[]
---@field repeated_string_piece string[]
---@field repeated_cord string[]
---@field packed_int32 integer[] @ Packed
---@field packed_int64 integer[]
---@field packed_uint32 integer[]
---@field packed_uint64 integer[]
---@field packed_sint32 integer[]
---@field packed_sint64 integer[]
---@field packed_fixed32 integer[]
---@field packed_fixed64 integer[]
---@field packed_sfixed32 integer[]
---@field packed_sfixed64 integer[]
---@field packed_float number[]
---@field packed_double number[]
---@field packed_bool boolean[]
---@field packed_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field unpacked_int32 integer[] @ Unpacked
---@field unpacked_int64 integer[]
---@field unpacked_uint32 integer[]
---@field unpacked_uint64 integer[]
---@field unpacked_sint32 integer[]
---@field unpacked_sint64 integer[]
---@field unpacked_fixed32 integer[]
---@field unpacked_fixed64 integer[]
---@field unpacked_sfixed32 integer[]
---@field unpacked_sfixed64 integer[]
---@field unpacked_float number[]
---@field unpacked_double number[]
---@field unpacked_bool boolean[]
---@field unpacked_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field map_int32_int32 table<integer, integer> @ Map
---@field map_int64_int64 table<integer, integer>
---@field map_uint32_uint32 table<integer, integer>
---@field map_uint64_uint64 table<integer, integer>
---@field map_sint32_sint32 table<integer, integer>
---@field map_sint64_sint64 table<integer, integer>
---@field map_fixed32_fixed32 table<integer, integer>
---@field map_fixed64_fixed64 table<integer, integer>
---@field map_sfixed32_sfixed32 table<integer, integer>
---@field map_sfixed64_sfixed64 table<integer, integer>
---@field map_int32_float table<integer, number>
---@field map_int32_double table<integer, number>
---@field map_bool_bool table<boolean, boolean>
---@field map_string_string table<string, string>
---@field map_string_bytes table<string, string>
---@field map_string_nested_message table<string, protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage>
---@field map_string_foreign_message table<string, protobuf_test_messages.proto3.ForeignMessage>
---@field map_string_nested_enum table<string, protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum>
---@field map_string_foreign_enum table<string, protobuf_test_messages.proto3.ForeignEnum>
---@field oneof_uint32? integer
---@field oneof_nested_message? protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field oneof_string? string
---@field oneof_bytes? string
---@field oneof_bool? boolean
---@field oneof_uint64? integer
---@field oneof_float? number
---@field oneof_double? number
---@field oneof_enum? protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
---@field oneof_null_value? google.protobuf.NullValue
---@field optional_bool_wrapper google.protobuf.BoolValue @ Well-known types
---@field optional_int32_wrapper google.protobuf.Int32Value
---@field optional_int64_wrapper google.protobuf.Int64Value
---@field optional_uint32_wrapper google.protobuf.UInt32Value
---@field optional_uint64_wrapper google.protobuf.UInt64Value
---@field optional_float_wrapper google.protobuf.FloatValue
---@field optional_double_wrapper google.protobuf.DoubleValue
---@field optional_string_wrapper google.protobuf.StringValue
---@field optional_bytes_wrapper google.protobuf.BytesValue
---@field repeated_bool_wrapper google.protobuf.BoolValue[]
---@field repeated_int32_wrapper google.protobuf.Int32Value[]
---@field repeated_int64_wrapper google.protobuf.Int64Value[]
---@field repeated_uint32_wrapper google.protobuf.UInt32Value[]
---@field repeated_uint64_wrapper google.protobuf.UInt64Value[]
---@field repeated_float_wrapper google.protobuf.FloatValue[]
---@field repeated_double_wrapper google.protobuf.DoubleValue[]
---@field repeated_string_wrapper google.protobuf.StringValue[]
---@field repeated_bytes_wrapper google.protobuf.BytesValue[]
---@field optional_duration google.protobuf.Duration
---@field optional_timestamp google.protobuf.Timestamp
---@field optional_field_mask google.protobuf.FieldMask
---@field optional_struct google.protobuf.Struct
---@field optional_any google.protobuf.Any
---@field optional_value google.protobuf.Value
---@field optional_null_value google.protobuf.NullValue
---@field optional_empty google.protobuf.Empty
---@field repeated_duration google.protobuf.Duration[]
---@field repeated_timestamp google.protobuf.Timestamp[]
---@field repeated_fieldmask google.protobuf.FieldMask[]
---@field repeated_struct google.protobuf.Struct[]
---@field repeated_any google.protobuf.Any[]
---@field repeated_value google.protobuf.Value[]
---@field repeated_list_value google.protobuf.ListValue[]
---@field repeated_empty google.protobuf.Empty[]
---@field fieldname1 integer @ Test field-name-to-JSON-name convention. (protobuf says names can be any valid C/C++ identifier.)
---@field field_name2 integer
---@field _field_name3 integer
---@field field__name4_ integer
---@field field0name5 integer
---@field field_0_name6 integer
---@field fieldName7 integer
---@field FieldName8 integer
---@field field_Name9 integer
---@field Field_Name10 integer
---@field FIELD_NAME11 integer
---@field FIELD_name12 integer
---@field __field_name13 integer
---@field __Field_name14 integer
---@field field__name15 integer
---@field field__Name16 integer
---@field field_name17__ integer
---@field Field_name18__ integer

---@class protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field a integer
---@field corecursive protobuf_test_messages.proto3.TestAllTypesProto3

---@class protobuf_test_messages.proto3.ForeignMessage
---@field c integer

---@class protobuf_test_messages.proto3.NullHypothesisProto3

---@class protobuf_test_messages.proto3.EnumOnlyProto3

---@param t? protobuf_test_messages.proto3.TestAllTypesProto3
---@return protobuf_test_messages.proto3.TestAllTypesProto3
function M.TestAllTypesProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3
---@return string
function M.TestAllTypesProto3_encode(t) return pb.encode(M.TestAllTypesProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.TestAllTypesProto3
function M.TestAllTypesProto3_decode(b) return pb.decode(M.TestAllTypesProto3_descriptor, b) end
function M.TestAllTypesProto3_decode_unsafe(b) return pb.decode_unsafe(M.TestAllTypesProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.TestAllTypesProto3_decode_lazy(b) return pb.decode_lazy(M.TestAllTypesProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.TestAllTypesProto3_text(t, opts) return pb.text.encode(M.TestAllTypesProto3_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@return protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
function M.TestAllTypesProto3_NestedMessage_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@return string
function M.TestAllTypesProto3_NestedMessage_encode(t) return pb.encode(M.TestAllTypesProto3_NestedMessage_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
function M.TestAllTypesProto3_NestedMessage_decode(b) return pb.decode(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
function M.TestAllTypesProto3_NestedMessage_decode_unsafe(b) return pb.decode_unsafe(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.TestAllTypesProto3_NestedMessage_decode_lazy(b) return pb.decode_lazy(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.TestAllTypesProto3_NestedMessage_text(t, opts) return pb.text.encode(M.TestAllTypesProto3_NestedMessage_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.ForeignMessage
---@return protobuf_test_messages.proto3.ForeignMessage
function M.ForeignMessage_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.ForeignMessage
---@return string
function M.ForeignMessage_encode(t) return pb.encode(M.ForeignMessage_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.ForeignMessage
function M.ForeignMessage_decode(b) return pb.decode(M.ForeignMessage_descriptor, b) end
function M.ForeignMessage_decode_unsafe(b) return pb.decode_unsafe(M.ForeignMessage_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.ForeignMessage_decode_lazy(b) return pb.decode_lazy(M.ForeignMessage_descriptor, b) end
---@param t protobuf_test_messages.proto3.ForeignMessage
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.ForeignMessage_text(t, opts) return pb.text.encode(M.ForeignMessage_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.NullHypothesisProto3
---@return protobuf_test_messages.proto3.NullHypothesisProto3
function M.NullHypothesisProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.NullHypothesisProto3
---@return string
function M.NullHypothesisProto3_encode(t) return pb.encode(M.NullHypothesisProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.NullHypothesisProto3
function M.NullHypothesisProto3_decode(b) return pb.decode(M.NullHypothesisProto3_descriptor, b) end
function M.NullHypothesisProto3_decode_unsafe(b) return pb.decode_unsafe(M.NullHypothesisProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.NullHypothesisProto3_decode_lazy(b) return pb.decode_lazy(M.NullHypothesisProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.NullHypothesisProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.NullHypothesisProto3_text(t, opts) return pb.text.encode(M.NullHypothesisProto3_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.EnumOnlyProto3
---@return protobuf_test_messages.proto3.EnumOnlyProto3
function M.EnumOnlyProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.EnumOnlyProto3
---@return string
function M.EnumOnlyProto3_encode(t) return pb.encode(M.EnumOnlyProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.EnumOnlyProto3
function M.EnumOnlyProto3_decode(b) return pb.decode(M.EnumOnlyProto3_descriptor, b) end
function M.EnumOnlyProto3_decode_unsafe(b) return pb.decode_unsafe(M.EnumOnlyProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.EnumOnlyProto3_decode_lazy(b) return pb.decode_lazy(M.EnumOnlyProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.EnumOnlyProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.EnumOnlyProto3_text(t, opts) return pb.text.encode(M.EnumOnlyProto3_descriptor, t, opts) end

-- Serialized FileDescriptorProto of test_messages_proto3.proto (source_code_info
-- stripped), registered with pb.descriptors for server reflection.
M._file_descriptor = table.concat({
    "\x0a\x1atest_messages_proto3.proto\x12\x1dprotobuf_test_mess",
    "ages.proto3\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/p",
    "rotobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.pr",
    "oto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/pr",
    "otobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.p",
    "roto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb3\\\x0a\x12TestAll",
    "TypesProto3\x12%\x0a\x0eoptional_int32\x18\x01 \x01(\x05R\x0doptionalInt",
    "32\x12%\x0a\x0eoptional_int64\x18\x02 \x01(\x03R\x0doptionalInt64\x12'\x0a\x0fopt",
    "ional_uint32\x18\x03 \x01(\x0dR\x0eoptionalUint32\x12'\x0a\x0foptional_u",
    "int64\x18\x04 \x01(\x04R\x0eoptionalUint64\x12'\x0a\x0foptional_sint32\x18\x05",
    " \x01(\x11R\x0eoptionalSint32\x12'\x0a\x0foptional_sint64\x18\x06 \x01(\x12R\x0eo",
    "ptionalSint64\x12)\x0a\x10optional_fixed32\x18\x07 \x01(\x07R\x0foptiona",
    "lFixed32\x12)\x0a\x10optional_fixed64\x18\x08 \x01(\x06R\x0foptionalFixe",
    "d64\x12+\x0a\x11optional_sfixed32\x18\x09 \x01(\x0fR\x10optionalSfixed32",
    "\x12+\x0a\x11optional_sfixed64\x18\x0a \x01(\x10R\x10optionalSfixed64\x12%\x0a",
    "\x0eoptional_float\x18\x0b \x01(\x02R\x0doptionalFloat\x12'\x0a\x0foptional",
    "_double\x18\x0c \x01(\x01R\x0eoptionalDouble\x12#\x0a\x0doptional_bool\x18\x0d",
    " \x01(\x08R\x0coptionalBool\x12'\x0a\x0foptional_string\x18\x0e \x01(\x09R\x0eopt",
    "ionalString\x12%\x0a\x0eoptional_bytes\x18\x0f \x01(\x0cR\x0doptionalByt",
    "es\x12w\x0a\x17optional_nested_message\x18\x12 \x01(\x0b2?.protobuf_t",
    "est_messages.proto3.TestAllTypesProto3.NestedMes",
    "sageR\x15optionalNestedMessage\x12g\x0a\x18optional_foreign_",
    "message\x18\x13 \x01(\x0b2-.protobuf_test_messages.proto3.Fo",
    "reignMessageR\x16optionalForeignMessage\x12n\x0a\x14optional",
    "_nested_enum\x18\x15 \x01(\x0e2<.protobuf_test_messages.prot",
    "o3.TestAllTypesProto3.NestedEnumR\x12optionalNested",
    "Enum\x12^\x0a\x15optional_foreign_enum\x18\x16 \x01(\x0e2*.protobuf_t",
    "est_messages.proto3.ForeignEnumR\x13optionalForeign",
    "Enum\x12q\x0a\x15optional_aliased_enum\x18\x17 \x01(\x0e2=.protobuf_t",
    "est_messages.proto3.TestAllTypesProto3.AliasedEn",
    "umR\x13optionalAliasedEnum\x126\x0a\x15optional_string_piece",
    "\x18\x18 \x01(\x09B\x02\x08\x02R\x13optionalStringPiece\x12'\x0a\x0doptional_cord",
    "\x18\x19 \x01(\x09B\x02\x08\x01R\x0coptionalCord\x12^\x0a\x11recursive_message\x18\x1b ",
    "\x01(\x0b21.protobuf_test_messages.proto3.TestAllTypes",
    "Proto3R\x10recursiveMessage\x12%\x0a\x0erepeated_int32\x18\x1f \x03(\x05",
    "R\x0drepeatedInt32\x12%\x0a\x0erepeated_int64\x18  \x03(\x03R\x0drepeate",
    "dInt64\x12'\x0a\x0frepeated_uint32\x18! \x03(\x0dR\x0erepeatedUint32\x12",
    "'\x0a\x0frepeated_uint64\x18\" \x03(\x04R\x0erepeatedUint64\x12'\x0a\x0frepe",
    "ated_sint32\x18# \x03(\x11R\x0erepeatedSint32\x12'\x0a\x0frepeated_si",
    "nt64\x18$ \x03(\x12R\x0erepeatedSint64\x12)\x0a\x10repeated_fixed32\x18%",
    " \x03(\x07R\x0frepeatedFixed32\x12)\x0a\x10repeated_fixed64\x18& \x03(\x06R",
    "\x0frepeatedFixed64\x12+\x0a\x11repeated_sfixed32\x18' \x03(\x0fR\x10rep",
    "eatedSfixed32\x12+\x0a\x11repeated_sfixed64\x18( \x03(\x10R\x10repeat",
    "edSfixed64\x12%\x0a\x0erepeated_float\x18) \x03(\x02R\x0drepeatedFloa",
    "t\x12'\x0a\x0frepeated_double\x18* \x03(\x01R\x0erepeatedDouble\x12#\x0a\x0dre",
    "peated_bool\x18+ \x03(\x08R\x0crepeatedBool\x12'\x0a\x0frepeated_stri",
    "ng\x18, \x03(\x09R\x0erepeatedString\x12%\x0a\x0erepeated_bytes\x18- \x03(\x0c",
    "R\x0drepeatedBytes\x12w\x0a\x17repeated_nested_message\x180 \x03(\x0b",
    "2?.protobuf_test_messages.proto3.TestAllTypesPro",
    "to3.NestedMessageR\x15repeatedNestedMessage\x12g\x0a\x18repe",
    "ated_foreign_message\x181 \x03(\x0b2-.protobuf_test_messa",
    "ges.proto3.ForeignMessageR\x16repeatedForeignMessag",
    "e\x12n\x0a\x14repeated_nested_enum\x183 \x03(\x0e2<.protobuf_test_",
    "messages.proto3.TestAllTypesProto3.NestedEnumR\x12r",
    "epeatedNestedEnum\x12^\x0a\x15repeated_foreign_enum\x184 \x03(\x0e",
    "2*.protobuf_test_messages.proto3.ForeignEnumR\x13re",
    "peatedForeignEnum\x126\x0a\x15repeated_string_piece\x186 \x03(\x09",
    "B\x02\x08\x02R\x13repeatedStringPiece\x12'\x0a\x0drepeated_cord\x187 \x03(\x09",
    "B\x02\x08\x01R\x0crepeatedCord\x12%\x0a\x0cpacked_int32\x18K \x03(\x05B\x02\x10\x01R\x0bpa",
    "ckedInt32\x12%\x0a\x0cpacked_int64\x18L \x03(\x03B\x02\x10\x01R\x0bpackedInt64",
    "\x12'\x0a\x0dpacked_uint32\x18M \x03(\x0dB\x02\x10\x01R\x0cpackedUint32\x12'\x0a\x0dpac",
    "ked_uint64\x18N \x03(\x04B\x02\x10\x01R\x0cpackedUint64\x12'\x0a\x0dpacked_sin",
    "t32\x18O \x03(\x11B\x02\x10\x01R\x0cpackedSint32\x12'\x0a\x0dpacked_sint64\x18P \x03",
    "(\x12B\x02\x10\x01R\x0cpackedSint64\x12)\x0a\x0epacked_fixed32\x18Q \x03(\x07B\x02\x10\x01",
    "R\x0dpackedFixed32\x12)\x0a\x0epacked_fixed64\x18R \x03(\x06B\x02\x10\x01R\x0dpac",
    "kedFixed64\x12+\x0a\x0fpacked_sfixed32\x18S \x03(\x0fB\x02\x10\x01R\x0epackedS",
    "fixed32\x12+\x0a\x0fpacked_sfixed64\x18T \x03(\x10B\x02\x10\x01R\x0epackedSfix",
    "ed64\x12%\x0a\x0cpacked_float\x18U \x03(\x02B\x02\x10\x01R\x0bpackedFloat\x12'\x0a\x0dp",
    "acked_double\x18V \x03(\x01B\x02\x10\x01R\x0cpackedDouble\x12#\x0a\x0bpacked_b",
    "ool\x18W \x03(\x08B\x02\x10\x01R\x0apackedBool\x12n\x0a\x12packed_nested_enum\x18",
    "X \x03(\x0e2<.protobuf_test_messages.proto3.TestAllTyp",
    "esProto3.NestedEnumB\x02\x10\x01R\x10packedNestedEnum\x12)\x0a\x0eunp",
    "acked_int32\x18Y \x03(\x05B\x02\x10\x00R\x0dunpackedInt32\x12)\x0a\x0eunpacked",
    "_int64\x18Z \x03(\x03B\x02\x10\x00R\x0dunpackedInt64\x12+\x0a\x0funpacked_uint",
    "32\x18[ \x03(\x0dB\x02\x10\x00R\x0eunpackedUint32\x12+\x0a\x0funpacked_uint64\x18",
    "\\ \x03(\x04B\x02\x10\x00R\x0eunpackedUint64\x12+\x0a\x0funpacked_sint32\x18] \x03",
    "(\x11B\x02\x10\x00R\x0eunpackedSint32\x12+\x0a\x0funpacked_sint64\x18^ \x03(\x12B",
    "\x02\x10\x00R\x0eunpackedSint64\x12-\x0a\x10unpacked_fixed32\x18_ \x03(\x07B\x02\x10",
    "\x00R\x0funpackedFixed32\x12-\x0a\x10unpacked_fixed64\x18` \x03(\x06B\x02\x10\x00",
    "R\x0funpackedFixed64\x12/\x0a\x11unpacked_sfixed32\x18a \x03(\x0fB\x02\x10\x00",
    "R\x10unpackedSfixed32\x12/\x0a\x11unpacked_sfixed64\x18b \x03(\x10B\x02\x10",
    "\x00R\x10unpackedSfixed64\x12)\x0a\x0eunpacked_float\x18c \x03(\x02B\x02\x10\x00R",
    "\x0dunpackedFloat\x12+\x0a\x0funpacked_double\x18d \x03(\x01B\x02\x10\x00R\x0eunp",
    "ackedDouble\x12'\x0a\x0dunpacked_bool\x18e \x03(\x08B\x02\x10\x00R\x0cunpacked",
    "Bool\x12r\x0a\x14unpacked_nested_enum\x18f \x03(\x0e2<.protobuf_te",
    "st_messages.proto3.TestAllTypesProto3.NestedEnum",
    "B\x02\x10\x00R\x12unpackedNestedEnum\x12l\x0a\x0fmap_int32_int32\x188 \x03(",
    "\x0b2D.protobuf_test_messages.proto3.TestAllTypesPr",
    "oto3.MapInt32Int32EntryR\x0dmapInt32Int32\x12l\x0a\x0fmap_in",
    "t64_int64\x189 \x03(\x0b2D.protobuf_test_messages.proto3.",
    "TestAllTypesProto3.MapInt64Int64EntryR\x0dmapInt64I",
    "nt64\x12r\x0a\x11map_uint32_uint32\x18: \x03(\x0b2F.protobuf_test_",
    "messages.proto3.TestAllTypesProto3.MapUint32Uint",
    "32EntryR\x0fmapUint32Uint32\x12r\x0a\x11map_uint64_uint64\x18; ",
    "\x03(\x0b2F.protobuf_test_messages.proto3.TestAllTypes",
    "Proto3.MapUint64Uint64EntryR\x0fmapUint64Uint64\x12r\x0a\x11",
    "map_sint32_sint32\x18< \x03(\x0b2F.protobuf_test_messages",
    ".proto3.TestAllTypesProto3.MapSint32Sint32EntryR",
    "\x0fmapSint32Sint32\x12r\x0a\x11map_sint64_sint64\x18= \x03(\x0b2F.pr",
    "otobuf_test_messages.proto3.TestAllTypesProto3.M",
    "apSint64Sint64EntryR\x0fmapSint64Sint64\x12x\x0a\x13map_fixe",
    "d32_fixed32\x18> \x03(\x0b2H.protobuf_test_messages.proto",
    "3.TestAllTypesProto3.MapFixed32Fixed32EntryR\x11map",
    "Fixed32Fixed32\x12x\x0a\x13map_fixed64_fixed64\x18? \x03(\x0b2H.pr",
    "otobuf_test_messages.proto3.TestAllTypesProto3.M",
    "apFixed64Fixed64EntryR\x11mapFixed64Fixed64\x12~\x0a\x15map_",
    "sfixed32_sfixed32\x18@ \x03(\x0b2J.protobuf_test_messages",
    ".proto3.TestAllTypesProto3.MapSfixed32Sfixed32En",
    "tryR\x13mapSfixed32Sfixed32\x12~\x0a\x15map_sfixed64_sfixed6",
    "4\x18A \x03(\x0b2J.protobuf_test_messages.proto3.TestAllT",
    "ypesProto3.MapSfixed64Sfixed64EntryR\x13mapSfixed64",
    "Sfixed64\x12l\x0a\x0fmap_int32_float\x18B \x03(\x0b2D.protobuf_tes",
    "t_messages.proto3.TestAllTypesProto3.MapInt32Flo",
    "atEntryR\x0dmapInt32Float\x12o\x0a\x10map_int32_double\x18C \x03(\x0b",
    "2E.protobuf_test_messages.proto3.TestAllTypesPro",
    "to3.MapInt32DoubleEntryR\x0emapInt32Double\x12f\x0a\x0dmap_b",
    "ool_bool\x18D \x03(\x0b2B.protobuf_test_messages.proto3.T",
    "estAllTypesProto3.MapBoolBoolEntryR\x0bmapBoolBool\x12",
    "r\x0a\x11map_string_string\x18E \x03(\x0b2F.protobuf_test_messa",
    "ges.proto3.TestAllTypesProto3.MapStringStringEnt",
    "ryR\x0fmapStringString\x12o\x0a\x10map_string_bytes\x18F \x03(\x0b2E.",
    "protobuf_test_messages.proto3.TestAllTypesProto3",
    ".MapStringBytesEntryR\x0emapStringBytes\x12\x88\x01\x0a\x19map_str",
    "ing_nested_message\x18G \x03(\x0b2M.protobuf_test_message",
    "s.proto3.TestAllTypesProto3.MapStringNestedMessa",
    "geEntryR\x16mapStringNestedMessage\x12\x8b\x01\x0a\x1amap_string_f",
    "oreign_message\x18H \x03(\x0b2N.protobuf_test_messages.pr",
    "oto3.TestAllTypesProto3.MapStringForeignMessageE",
    "ntryR\x17mapStringForeignMessage\x12\x7f\x0a\x16map_string_nest",
    "ed_enum\x18I \x03(\x0b2J.protobuf_test_messages.proto3.Te",
    "stAllTypesProto3.MapStringNestedEnumEntryR\x13mapSt",
    "ringNestedEnum\x12\x82\x01\x0a\x17map_string_foreign_enum\x18J \x03(\x0b",
    "2K.protobuf_test_messages.proto3.TestAllTypesPro",
    "to3.MapStringForeignEnumEntryR\x14mapStringForeignE",
    "num\x12#\x0a\x0coneof_uint32\x18o \x01(\x0dH\x00R\x0boneofUint32\x12s\x0a\x14oneo",
    "f_nested_message\x18p \x01(\x0b2?.protobuf_test_messages.",
    "proto3.TestAllTypesProto3.NestedMessageH\x00R\x12oneof",
    "NestedMessage\x12#\x0a\x0coneof_string\x18q \x01(\x09H\x00R\x0boneofStri",
    "ng\x12!\x0a\x0boneof_bytes\x18r \x01(\x0cH\x00R\x0aoneofBytes\x12\x1f\x0a\x0aoneof_b",
    "ool\x18s \x01(\x08H\x00R\x09oneofBool\x12#\x0a\x0coneof_uint64\x18t \x01(\x04H\x00R\x0b",
    "oneofUint64\x12!\x0a\x0boneof_float\x18u \x01(\x02H\x00R\x0aoneofFloat\x12#",
    "\x0a\x0coneof_double\x18v \x01(\x01H\x00R\x0boneofDouble\x12]\x0a\x0aoneof_enu",
    "m\x18w \x01(\x0e2<.protobuf_test_messages.proto3.TestAllT",
    "ypesProto3.NestedEnumH\x00R\x09oneofEnum\x12F\x0a\x10oneof_null",
    "_value\x18x \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x0eoneo",
    "fNullValue\x12O\x0a\x15optional_bool_wrapper\x18\xc9\x01 \x01(\x0b2\x1a.goo",
    "gle.protobuf.BoolValueR\x13optionalBoolWrapper\x12R\x0a\x16o",
    "ptional_int32_wrapper\x18\xca\x01 \x01(\x0b2\x1b.google.protobuf.I",
    "nt32ValueR\x14optionalInt32Wrapper\x12R\x0a\x16optional_int6",
    "4_wrapper\x18\xcb\x01 \x01(\x0b2\x1b.google.protobuf.Int64ValueR\x14o",
    "ptionalInt64Wrapper\x12U\x0a\x17optional_uint32_wrapper\x18\xcc",
    "\x01 \x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x15optionalUin",
    "t32Wrapper\x12U\x0a\x17optional_uint64_wrapper\x18\xcd\x01 \x01(\x0b2\x1c.g",
    "oogle.protobuf.UInt64ValueR\x15optionalUint64Wrappe",
    "r\x12R\x0a\x16optional_float_wrapper\x18\xce\x01 \x01(\x0b2\x1b.google.prot",
    "obuf.FloatValueR\x14optionalFloatWrapper\x12U\x0a\x17optiona",
    "l_double_wrapper\x18\xcf\x01 \x01(\x0b2\x1c.google.protobuf.Double",
    "ValueR\x15optionalDoubleWrapper\x12U\x0a\x17optional_string_",
    "wrapper\x18\xd0\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x15op",
    "tionalStringWrapper\x12R\x0a\x16optional_bytes_wrapper\x18\xd1\x01",
    " \x01(\x0b2\x1b.google.protobuf.BytesValueR\x14optionalBytes",
    "Wrapper\x12O\x0a\x15repeated_bool_wrapper\x18\xd3\x01 \x03(\x0b2\x1a.google",
    ".protobuf.BoolValueR\x13repeatedBoolWrapper\x12R\x0a\x16repe",
    "ated_int32_wrapper\x18\xd4\x01 \x03(\x0b2\x1b.google.protobuf.Int3",
    "2ValueR\x14repeatedInt32Wrapper\x12R\x0a\x16repeated_int64_w",
    "rapper\x18\xd5\x01 \x03(\x0b2\x1b.google.protobuf.Int64ValueR\x14repe",
    "atedInt64Wrapper\x12U\x0a\x17repeated_uint32_wrapper\x18\xd6\x01 \x03",
    "(\x0b2\x1c.google.protobuf.UInt32ValueR\x15repeatedUint32",
    "Wrapper\x12U\x0a\x17repeated_uint64_wrapper\x18\xd7\x01 \x03(\x0b2\x1c.goog",
    "le.protobuf.UInt64ValueR\x15repeatedUint64Wrapper\x12R",
    "\x0a\x16repeated_float_wrapper\x18\xd8\x01 \x03(\x0b2\x1b.google.protobu",
    "f.FloatValueR\x14repeatedFloatWrapper\x12U\x0a\x17repeated_d",
    "ouble_wrapper\x18\xd9\x01 \x03(\x0b2\x1c.google.protobuf.DoubleVal",
    "ueR\x15repeatedDoubleWrapper\x12U\x0a\x17repeated_string_wra",
    "pper\x18\xda\x01 \x03(\x0b2\x1c.google.protobuf.StringValueR\x15repea",
    "tedStringWrapper\x12R\x0a\x16repeated_bytes_wrapper\x18\xdb\x01 \x03(",
    "\x0b2\x1b.google.protobuf.BytesValueR\x14repeatedBytesWra",
    "pper\x12G\x0a\x11optional_duration\x18\xad\x02 \x01(\x0b2\x19.google.protob",
    "uf.DurationR\x10optionalDuration\x12J\x0a\x12optional_timest",
    "amp\x18\xae\x02 \x01(\x0b2\x1a.google.protobuf.TimestampR\x11optional",
    "Timestamp\x12K\x0a\x13optional_field_mask\x18\xaf\x02 \x01(\x0b2\x1a.google",
    ".protobuf.FieldMaskR\x11optionalFieldMask\x12A\x0a\x0foption",
    "al_struct\x18\xb0\x02 \x01(\x0b2\x17.google.protobuf.StructR\x0eoptio",
    "nalStruct\x128\x0a\x0coptional_any\x18\xb1\x02 \x01(\x0b2\x14.google.protob",
    "uf.AnyR\x0boptionalAny\x12>\x0a\x0eoptional_value\x18\xb2\x02 \x01(\x0b2\x16.g",
    "oogle.protobuf.ValueR\x0doptionalValue\x12K\x0a\x13optional_",
    "null_value\x18\xb3\x02 \x01(\x0e2\x1a.google.protobuf.NullValueR\x11o",
    "ptionalNullValue\x12>\x0a\x0eoptional_empty\x18\xb4\x02 \x01(\x0b2\x16.goog",
    "le.protobuf.EmptyR\x0doptionalEmpty\x12G\x0a\x11repeated_dur",
    "ation\x18\xb7\x02 \x03(\x0b2\x19.google.protobuf.DurationR\x10repeate",
    "dDuration\x12J\x0a\x12repeated_timestamp\x18\xb8\x02 \x03(\x0b2\x1a.google.",
    "protobuf.TimestampR\x11repeatedTimestamp\x12J\x0a\x12repeate",
    "d_fieldmask\x18\xb9\x02 \x03(\x0b2\x1a.google.protobuf.FieldMaskR\x11",
    "repeatedFieldmask\x12A\x0a\x0frepeated_struct\x18\xc4\x02 \x03(\x0b2\x17.go",
    "ogle.protobuf.StructR\x0erepeatedStruct\x128\x0a\x0crepeated",
    "_any\x18\xbb\x02 \x03(\x0b2\x14.google.protobuf.AnyR\x0brepeatedAny\x12>",
    "\x0a\x0erepeated_value\x18\xbc\x02 \x03(\x0b2\x16.google.protobuf.ValueR",
    "\x0drepeatedValue\x12K\x0a\x13repeated_list_value\x18\xbd\x02 \x03(\x0b2\x1a.g",
    "oogle.protobuf.ListValueR\x11repeatedListValue\x12>\x0a\x0er",
    "epeated_empty\x18\xbe\x02 \x03(\x0b2\x16.google.protobuf.EmptyR\x0dre",
    "peatedEmpty\x12\x1f\x0a\x0afieldname1\x18\x91\x03 \x01(\x05R\x0afieldname1\x12 \x0a\x0b",
    "field_name2\x18\x92\x03 \x01(\x05R\x0afieldName2\x12!\x0a\x0c_field_name3\x18\x93",
    "\x03 \x01(\x05R\x0aFieldName3\x12\"\x0a\x0dfield__name4_\x18\x94\x03 \x01(\x05R\x0afield",
    "Name4\x12!\x0a\x0bfield0name5\x18\x95\x03 \x01(\x05R\x0bfield0name5\x12#\x0a\x0dfiel",
    "d_0_name6\x18\x96\x03 \x01(\x05R\x0bfield0Name6\x12\x1f\x0a\x0afieldName7\x18\x97\x03 \x01",
    "(\x05R\x0afieldName7\x12\x1f\x0a\x0aFieldName8\x18\x98\x03 \x01(\x05R\x0aFieldName8\x12",
    " \x0a\x0bfield_Name9\x18\x99\x03 \x01(\x05R\x0afieldName9\x12\"\x0a\x0cField_Name1",
    "0\x18\x9a\x03 \x01(\x05R\x0bFieldName10\x12\"\x0a\x0cFIELD_NAME11\x18\x9b\x03 \x01(\x05R\x0bFI",
    "ELDNAME11\x12\"\x0a\x0cFIELD_name12\x18\x9c\x03 \x01(\x05R\x0bFIELDName12\x12$\x0a",
    "\x0e__field_name13\x18\x9d\x03 \x01(\x05R\x0bFieldName13\x12$\x0a\x0e__Field_n",
    "ame14\x18\x9e\x03 \x01(\x05R\x0bFieldName14\x12#\x0a\x0dfield__name15\x18\x9f\x03 \x01(",
    "\x05R\x0bfieldName15\x12#\x0a\x0dfield__Name16\x18\xa0\x03 \x01(\x05R\x0bfieldNam",
    "e16\x12$\x0a\x0efield_name17__\x18\xa1\x03 \x01(\x05R\x0bfieldName17\x12$\x0a\x0eFie",
    "ld_name18__\x18\xa2\x03 \x01(\x05R\x0bFieldName18\x1ar\x0a\x0dNestedMessage",
    "\x12\x0c\x0a\x01a\x18\x01 \x01(\x05R\x01a\x12S\x0a\x0bcorecursive\x18\x02 \x01(\x0b21.protobuf_t",
    "est_messages.proto3.TestAllTypesProto3R\x0bcorecurs",
    "ive\x1a@\x0a\x12MapInt32Int32Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\x0a\x05v",
    "alue\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\x0a\x12MapInt64Int64Entry\x12\x10\x0a\x03k",
    "ey\x18\x01 \x01(\x03R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\x0a\x14MapUi",
    "nt32Uint32Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x0dR\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x0d",
    "R\x05value:\x028\x01\x1aB\x0a\x14MapUint64Uint64Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x04",
    "R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\x0a\x14MapSint32Sint",
    "32Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x11R\x05value:",
    "\x028\x01\x1aB\x0a\x14MapSint64Sint64Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\x0a",
    "\x05value\x18\x02 \x01(\x12R\x05value:\x028\x01\x1aD\x0a\x16MapFixed32Fixed32Entr",
    "y\x12\x10\x0a\x03key\x18\x01 \x01(\x07R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x07R\x05value:\x028\x01\x1aD\x0a",
    "\x16MapFixed64Fixed64Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\x0a\x05val",
    "ue\x18\x02 \x01(\x06R\x05value:\x028\x01\x1aF\x0a\x18MapSfixed32Sfixed32Entry\x12",
    "\x10\x0a\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x0fR\x05value:\x028\x01\x1aF\x0a\x18M",
    "apSfixed64Sfixed64Entry\x12\x10\x0a\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\x0a\x05val",
    "ue\x18\x02 \x01(\x10R\x05value:\x028\x01\x1a@\x0a\x12MapInt32FloatEntry\x12\x10\x0a\x03key",
    "\x18\x01 \x01(\x05R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aA\x0a\x13MapInt3",
    "2DoubleEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x01R\x05v",
    "alue:\x028\x01\x1a>\x0a\x10MapBoolBoolEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x08R\x03key\x12\x14",
    "\x0a\x05value\x18\x02 \x01(\x08R\x05value:\x028\x01\x1aB\x0a\x14MapStringStringEntry",
    "\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x09R\x05value:\x028\x01\x1aA\x0a\x13",
    "MapStringBytesEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0a\x05value\x18\x02",
    " \x01(\x0cR\x05value:\x028\x01\x1a\x8a\x01\x0a\x1bMapStringNestedMessageEntry\x12",
    "\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12U\x0a\x05value\x18\x02 \x01(\x0b2?.protobuf_test",
    "_messages.proto3.TestAllTypesProto3.NestedMessag",
    "eR\x05value:\x028\x01\x1ay\x0a\x1cMapStringForeignMessageEntry\x12\x10\x0a\x03",
    "key\x18\x01 \x01(\x09R\x03key\x12C\x0a\x05value\x18\x02 \x01(\x0b2-.protobuf_test_me",
    "ssages.proto3.ForeignMessageR\x05value:\x028\x01\x1a\x84\x01\x0a\x18MapS",
    "tringNestedEnumEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12R\x0a\x05value\x18",
    "\x02 \x01(\x0e2<.protobuf_test_messages.proto3.TestAllTyp",
    "esProto3.NestedEnumR\x05value:\x028\x01\x1as\x0a\x19MapStringForei",
    "gnEnumEntry\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12@\x0a\x05value\x18\x02 \x01(\x0e2*.p",
    "rotobuf_test_messages.proto3.ForeignEnumR\x05value:",
    "\x028\x01\"9\x0a\x0aNestedEnum\x12\x07\x0a\x03FOO\x10\x00\x12\x07\x0a\x03BAR\x10\x01\x12\x07\x0a\x03BAZ\x10\x02\x12\x10\x0a\x03",
    "NEG\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\"Y\x0a\x0bAliasedEnum\x12\x0d\x0a\x09ALIAS_FOO\x10\x00\x12\x0d\x0a\x09",
    "ALIAS_BAR\x10\x01\x12\x0d\x0a\x09ALIAS_BAZ\x10\x02\x12\x07\x0a\x03MOO\x10\x02\x12\x07\x0a\x03moo\x10\x02\x12\x07\x0a\x03",
    "bAz\x10\x02\x1a\x02\x10\x01B\x0d\x0a\x0boneof_fieldJ\x06\x08\xf5\x03\x10\xff\x03J\x08\x08\xbf\x84=\x10\xc0\x84=R\x0erese",
    "rved_field\"\x1e\x0a\x0eForeignMessage\x12\x0c\x0a\x01c\x18\x01 \x01(\x05R\x01c\"\x16\x0a\x14Nu",
    "llHypothesisProto3\"/\x0a\x0eEnumOnlyProto3\"\x1d\x0a\x04Bool\x12\x0a\x0a\x06",
    "kFalse\x10\x00\x12\x09\x0a\x05kTrue\x10\x01*@\x0a\x0bForeignEnum\x12\x0f\x0a\x0bFOREIGN_FO",
    "O\x10\x00\x12\x0f\x0a\x0bFOREIGN_BAR\x10\x01\x12\x0f\x0a\x0bFOREIGN_BAZ\x10\x02B8\x0a(com.goo",
    "gle.protobuf_test_messages.proto3H\x01\xf8\x01\x01\xa2\x02\x06Proto3b",
    "\x06proto3",
})
pb.descriptors.register(M._file_descriptor)

return M
