-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: test_messages_proto3.proto
-- syntax: proto3
-- package: protobuf_test_messages.proto3

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {cc_enable_arenas = true, go_package = "tarantoolpb_synthetic/test_messages_proto3", java_package = "com.google.protobuf_test_messages.proto3", objc_class_prefix = "Proto3", optimize_for = "SPEED"}

-- Enum: protobuf_test_messages.proto3.ForeignEnum
M.ForeignEnum_descriptor = pb.enum("protobuf_test_messages.proto3.ForeignEnum", {
    FOREIGN_FOO = 0,
    FOREIGN_BAR = 1,
    FOREIGN_BAZ = 2,
})
M.ForeignEnum = M.ForeignEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
M.TestAllTypesProto3_NestedEnum_descriptor = pb.enum("protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum", {
    FOO = 0,
    BAR = 1,
    BAZ = 2,
    NEG = -1,
})
M.TestAllTypesProto3_NestedEnum = M.TestAllTypesProto3_NestedEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum
M.TestAllTypesProto3_AliasedEnum_descriptor = pb.enum("protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum", {
    ALIAS_FOO = 0,
    ALIAS_BAR = 1,
    ALIAS_BAZ = 2,
    MOO = 2,
    moo = 2,
    bAz = 2,
})
M.TestAllTypesProto3_AliasedEnum_descriptor.options = {allow_alias = true}
M.TestAllTypesProto3_AliasedEnum = M.TestAllTypesProto3_AliasedEnum_descriptor.by_name

-- Enum: protobuf_test_messages.proto3.EnumOnlyProto3.Bool
M.EnumOnlyProto3_Bool_descriptor = pb.enum("protobuf_test_messages.proto3.EnumOnlyProto3.Bool", {
    kFalse = 0,
    kTrue = 1,
})
M.EnumOnlyProto3_Bool = M.EnumOnlyProto3_Bool_descriptor.by_name

-- Pre-declare message descriptors so cross-references resolve.
M.TestAllTypesProto3_descriptor = {name = "protobuf_test_messages.proto3.TestAllTypesProto3"}
M.TestAllTypesProto3_NestedMessage_descriptor = {name = "protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage"}
M.ForeignMessage_descriptor = {name = "protobuf_test_messages.proto3.ForeignMessage"}
M.NullHypothesisProto3_descriptor = {name = "protobuf_test_messages.proto3.NullHypothesisProto3"}
M.EnumOnlyProto3_descriptor = {name = "protobuf_test_messages.proto3.EnumOnlyProto3"}

-- Message: protobuf_test_messages.proto3.TestAllTypesProto3
M.TestAllTypesProto3_descriptor.fields = {
    {name="optional_int32", id=1, kind='scalar', proto_type="int32"},
    {name="optional_int64", id=2, kind='scalar', proto_type="int64"},
    {name="optional_uint32", id=3, kind='scalar', proto_type="uint32"},
    {name="optional_uint64", id=4, kind='scalar', proto_type="uint64"},
    {name="optional_sint32", id=5, kind='scalar', proto_type="sint32"},
    {name="optional_sint64", id=6, kind='scalar', proto_type="sint64"},
    {name="optional_fixed32", id=7, kind='scalar', proto_type="fixed32"},
    {name="optional_fixed64", id=8, kind='scalar', proto_type="fixed64"},
    {name="optional_sfixed32", id=9, kind='scalar', proto_type="sfixed32"},
    {name="optional_sfixed64", id=10, kind='scalar', proto_type="sfixed64"},
    {name="optional_float", id=11, kind='scalar', proto_type="float"},
    {name="optional_double", id=12, kind='scalar', proto_type="double"},
    {name="optional_bool", id=13, kind='scalar', proto_type="bool"},
    {name="optional_string", id=14, kind='scalar', proto_type="string"},
    {name="optional_bytes", id=15, kind='scalar', proto_type="bytes"},
    {name="optional_nested_message", id=18, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor},
    {name="optional_foreign_message", id=19, kind='message', message=M.ForeignMessage_descriptor},
    {name="optional_nested_enum", id=21, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor},
    {name="optional_foreign_enum", id=22, kind='enum', enum=M.ForeignEnum_descriptor},
    {name="optional_aliased_enum", id=23, kind='enum', enum=M.TestAllTypesProto3_AliasedEnum_descriptor},
    {name="optional_string_piece", id=24, kind='scalar', proto_type="string", options={ctype = "STRING_PIECE"}},
    {name="optional_cord", id=25, kind='scalar', proto_type="string", options={ctype = "CORD"}},
    {name="recursive_message", id=27, kind='message', message=M.TestAllTypesProto3_descriptor},
    {name="repeated_int32", id=31, kind='scalar', proto_type="int32", repeated=true, packed=true},
    {name="repeated_int64", id=32, kind='scalar', proto_type="int64", repeated=true, packed=true},
    {name="repeated_uint32", id=33, kind='scalar', proto_type="uint32", repeated=true, packed=true},
    {name="repeated_uint64", id=34, kind='scalar', proto_type="uint64", repeated=true, packed=true},
    {name="repeated_sint32", id=35, kind='scalar', proto_type="sint32", repeated=true, packed=true},
    {name="repeated_sint64", id=36, kind='scalar', proto_type="sint64", repeated=true, packed=true},
    {name="repeated_fixed32", id=37, kind='scalar', proto_type="fixed32", repeated=true, packed=true},
    {name="repeated_fixed64", id=38, kind='scalar', proto_type="fixed64", repeated=true, packed=true},
    {name="repeated_sfixed32", id=39, kind='scalar', proto_type="sfixed32", repeated=true, packed=true},
    {name="repeated_sfixed64", id=40, kind='scalar', proto_type="sfixed64", repeated=true, packed=true},
    {name="repeated_float", id=41, kind='scalar', proto_type="float", repeated=true, packed=true},
    {name="repeated_double", id=42, kind='scalar', proto_type="double", repeated=true, packed=true},
    {name="repeated_bool", id=43, kind='scalar', proto_type="bool", repeated=true, packed=true},
    {name="repeated_string", id=44, kind='scalar', proto_type="string", repeated=true},
    {name="repeated_bytes", id=45, kind='scalar', proto_type="bytes", repeated=true},
    {name="repeated_nested_message", id=48, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor, repeated=true},
    {name="repeated_foreign_message", id=49, kind='message', message=M.ForeignMessage_descriptor, repeated=true},
    {name="repeated_nested_enum", id=51, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=true},
    {name="repeated_foreign_enum", id=52, kind='enum', enum=M.ForeignEnum_descriptor, repeated=true, packed=true},
    {name="repeated_string_piece", id=54, kind='scalar', proto_type="string", repeated=true, options={ctype = "STRING_PIECE"}},
    {name="repeated_cord", id=55, kind='scalar', proto_type="string", repeated=true, options={ctype = "CORD"}},
    {name="packed_int32", id=75, kind='scalar', proto_type="int32", repeated=true, packed=true, options={packed = true}},
    {name="packed_int64", id=76, kind='scalar', proto_type="int64", repeated=true, packed=true, options={packed = true}},
    {name="packed_uint32", id=77, kind='scalar', proto_type="uint32", repeated=true, packed=true, options={packed = true}},
    {name="packed_uint64", id=78, kind='scalar', proto_type="uint64", repeated=true, packed=true, options={packed = true}},
    {name="packed_sint32", id=79, kind='scalar', proto_type="sint32", repeated=true, packed=true, options={packed = true}},
    {name="packed_sint64", id=80, kind='scalar', proto_type="sint64", repeated=true, packed=true, options={packed = true}},
    {name="packed_fixed32", id=81, kind='scalar', proto_type="fixed32", repeated=true, packed=true, options={packed = true}},
    {name="packed_fixed64", id=82, kind='scalar', proto_type="fixed64", repeated=true, packed=true, options={packed = true}},
    {name="packed_sfixed32", id=83, kind='scalar', proto_type="sfixed32", repeated=true, packed=true, options={packed = true}},
    {name="packed_sfixed64", id=84, kind='scalar', proto_type="sfixed64", repeated=true, packed=true, options={packed = true}},
    {name="packed_float", id=85, kind='scalar', proto_type="float", repeated=true, packed=true, options={packed = true}},
    {name="packed_double", id=86, kind='scalar', proto_type="double", repeated=true, packed=true, options={packed = true}},
    {name="packed_bool", id=87, kind='scalar', proto_type="bool", repeated=true, packed=true, options={packed = true}},
    {name="packed_nested_enum", id=88, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=true, options={packed = true}},
    {name="unpacked_int32", id=89, kind='scalar', proto_type="int32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_int64", id=90, kind='scalar', proto_type="int64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_uint32", id=91, kind='scalar', proto_type="uint32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_uint64", id=92, kind='scalar', proto_type="uint64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sint32", id=93, kind='scalar', proto_type="sint32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sint64", id=94, kind='scalar', proto_type="sint64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_fixed32", id=95, kind='scalar', proto_type="fixed32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_fixed64", id=96, kind='scalar', proto_type="fixed64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sfixed32", id=97, kind='scalar', proto_type="sfixed32", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_sfixed64", id=98, kind='scalar', proto_type="sfixed64", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_float", id=99, kind='scalar', proto_type="float", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_double", id=100, kind='scalar', proto_type="double", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_bool", id=101, kind='scalar', proto_type="bool", repeated=true, packed=false, options={packed = false}},
    {name="unpacked_nested_enum", id=102, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, repeated=true, packed=false, options={packed = false}},
    {name="map_int32_int32", id=56, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="int32"}},
    {name="map_int64_int64", id=57, kind='map', key={kind='scalar', proto_type="int64"}, value={kind='scalar', proto_type="int64"}},
    {name="map_uint32_uint32", id=58, kind='map', key={kind='scalar', proto_type="uint32"}, value={kind='scalar', proto_type="uint32"}},
    {name="map_uint64_uint64", id=59, kind='map', key={kind='scalar', proto_type="uint64"}, value={kind='scalar', proto_type="uint64"}},
    {name="map_sint32_sint32", id=60, kind='map', key={kind='scalar', proto_type="sint32"}, value={kind='scalar', proto_type="sint32"}},
    {name="map_sint64_sint64", id=61, kind='map', key={kind='scalar', proto_type="sint64"}, value={kind='scalar', proto_type="sint64"}},
    {name="map_fixed32_fixed32", id=62, kind='map', key={kind='scalar', proto_type="fixed32"}, value={kind='scalar', proto_type="fixed32"}},
    {name="map_fixed64_fixed64", id=63, kind='map', key={kind='scalar', proto_type="fixed64"}, value={kind='scalar', proto_type="fixed64"}},
    {name="map_sfixed32_sfixed32", id=64, kind='map', key={kind='scalar', proto_type="sfixed32"}, value={kind='scalar', proto_type="sfixed32"}},
    {name="map_sfixed64_sfixed64", id=65, kind='map', key={kind='scalar', proto_type="sfixed64"}, value={kind='scalar', proto_type="sfixed64"}},
    {name="map_int32_float", id=66, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="float"}},
    {name="map_int32_double", id=67, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='scalar', proto_type="double"}},
    {name="map_bool_bool", id=68, kind='map', key={kind='scalar', proto_type="bool"}, value={kind='scalar', proto_type="bool"}},
    {name="map_string_string", id=69, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="string"}},
    {name="map_string_bytes", id=70, kind='map', key={kind='scalar', proto_type="string"}, value={kind='scalar', proto_type="bytes"}},
    {name="map_string_nested_message", id=71, kind='map', key={kind='scalar', proto_type="string"}, value={kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor}},
    {name="map_string_foreign_message", id=72, kind='map', key={kind='scalar', proto_type="string"}, value={kind='message', message=M.ForeignMessage_descriptor}},
    {name="map_string_nested_enum", id=73, kind='map', key={kind='scalar', proto_type="string"}, value={kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor}},
    {name="map_string_foreign_enum", id=74, kind='map', key={kind='scalar', proto_type="string"}, value={kind='enum', enum=M.ForeignEnum_descriptor}},
    {name="oneof_uint32", id=111, kind='scalar', proto_type="uint32", oneof="oneof_field"},
    {name="oneof_nested_message", id=112, kind='message', message=M.TestAllTypesProto3_NestedMessage_descriptor, oneof="oneof_field"},
    {name="oneof_string", id=113, kind='scalar', proto_type="string", oneof="oneof_field"},
    {name="oneof_bytes", id=114, kind='scalar', proto_type="bytes", oneof="oneof_field"},
    {name="oneof_bool", id=115, kind='scalar', proto_type="bool", oneof="oneof_field"},
    {name="oneof_uint64", id=116, kind='scalar', proto_type="uint64", oneof="oneof_field"},
    {name="oneof_float", id=117, kind='scalar', proto_type="float", oneof="oneof_field"},
    {name="oneof_double", id=118, kind='scalar', proto_type="double", oneof="oneof_field"},
    {name="oneof_enum", id=119, kind='enum', enum=M.TestAllTypesProto3_NestedEnum_descriptor, oneof="oneof_field"},
    {name="oneof_null_value", id=120, kind='enum', enum=pb.wkt.NullValue_descriptor, oneof="oneof_field"},
    {name="optional_bool_wrapper", id=201, kind='message', message=pb.wkt.BoolValue_descriptor},
    {name="optional_int32_wrapper", id=202, kind='message', message=pb.wkt.Int32Value_descriptor},
    {name="optional_int64_wrapper", id=203, kind='message', message=pb.wkt.Int64Value_descriptor},
    {name="optional_uint32_wrapper", id=204, kind='message', message=pb.wkt.UInt32Value_descriptor},
    {name="optional_uint64_wrapper", id=205, kind='message', message=pb.wkt.UInt64Value_descriptor},
    {name="optional_float_wrapper", id=206, kind='message', message=pb.wkt.FloatValue_descriptor},
    {name="optional_double_wrapper", id=207, kind='message', message=pb.wkt.DoubleValue_descriptor},
    {name="optional_string_wrapper", id=208, kind='message', message=pb.wkt.StringValue_descriptor},
    {name="optional_bytes_wrapper", id=209, kind='message', message=pb.wkt.BytesValue_descriptor},
    {name="repeated_bool_wrapper", id=211, kind='message', message=pb.wkt.BoolValue_descriptor, repeated=true},
    {name="repeated_int32_wrapper", id=212, kind='message', message=pb.wkt.Int32Value_descriptor, repeated=true},
    {name="repeated_int64_wrapper", id=213, kind='message', message=pb.wkt.Int64Value_descriptor, repeated=true},
    {name="repeated_uint32_wrapper", id=214, kind='message', message=pb.wkt.UInt32Value_descriptor, repeated=true},
    {name="repeated_uint64_wrapper", id=215, kind='message', message=pb.wkt.UInt64Value_descriptor, repeated=true},
    {name="repeated_float_wrapper", id=216, kind='message', message=pb.wkt.FloatValue_descriptor, repeated=true},
    {name="repeated_double_wrapper", id=217, kind='message', message=pb.wkt.DoubleValue_descriptor, repeated=true},
    {name="repeated_string_wrapper", id=218, kind='message', message=pb.wkt.StringValue_descriptor, repeated=true},
    {name="repeated_bytes_wrapper", id=219, kind='message', message=pb.wkt.BytesValue_descriptor, repeated=true},
    {name="optional_duration", id=301, kind='message', message=pb.wkt.Duration_descriptor},
    {name="optional_timestamp", id=302, kind='message', message=pb.wkt.Timestamp_descriptor},
    {name="optional_field_mask", id=303, kind='message', message=pb.wkt.FieldMask_descriptor},
    {name="optional_struct", id=304, kind='message', message=pb.wkt.Struct_descriptor},
    {name="optional_any", id=305, kind='message', message=pb.wkt.Any_descriptor},
    {name="optional_value", id=306, kind='message', message=pb.wkt.Value_descriptor},
    {name="optional_null_value", id=307, kind='enum', enum=pb.wkt.NullValue_descriptor},
    {name="optional_empty", id=308, kind='message', message=pb.wkt.Empty_descriptor},
    {name="repeated_duration", id=311, kind='message', message=pb.wkt.Duration_descriptor, repeated=true},
    {name="repeated_timestamp", id=312, kind='message', message=pb.wkt.Timestamp_descriptor, repeated=true},
    {name="repeated_fieldmask", id=313, kind='message', message=pb.wkt.FieldMask_descriptor, repeated=true},
    {name="repeated_struct", id=324, kind='message', message=pb.wkt.Struct_descriptor, repeated=true},
    {name="repeated_any", id=315, kind='message', message=pb.wkt.Any_descriptor, repeated=true},
    {name="repeated_value", id=316, kind='message', message=pb.wkt.Value_descriptor, repeated=true},
    {name="repeated_list_value", id=317, kind='message', message=pb.wkt.ListValue_descriptor, repeated=true},
    {name="repeated_empty", id=318, kind='message', message=pb.wkt.Empty_descriptor, repeated=true},
    {name="fieldname1", id=401, kind='scalar', proto_type="int32"},
    {name="field_name2", id=402, kind='scalar', proto_type="int32"},
    {name="_field_name3", id=403, kind='scalar', proto_type="int32"},
    {name="field__name4_", id=404, kind='scalar', proto_type="int32"},
    {name="field0name5", id=405, kind='scalar', proto_type="int32"},
    {name="field_0_name6", id=406, kind='scalar', proto_type="int32"},
    {name="fieldName7", id=407, kind='scalar', proto_type="int32"},
    {name="FieldName8", id=408, kind='scalar', proto_type="int32"},
    {name="field_Name9", id=409, kind='scalar', proto_type="int32"},
    {name="Field_Name10", id=410, kind='scalar', proto_type="int32"},
    {name="FIELD_NAME11", id=411, kind='scalar', proto_type="int32"},
    {name="FIELD_name12", id=412, kind='scalar', proto_type="int32"},
    {name="__field_name13", id=413, kind='scalar', proto_type="int32"},
    {name="__Field_name14", id=414, kind='scalar', proto_type="int32"},
    {name="field__name15", id=415, kind='scalar', proto_type="int32"},
    {name="field__Name16", id=416, kind='scalar', proto_type="int32"},
    {name="field_name17__", id=417, kind='scalar', proto_type="int32"},
    {name="Field_name18__", id=418, kind='scalar', proto_type="int32"},
}
M.TestAllTypesProto3_descriptor.oneofs = {
    oneof_field = {"oneof_uint32", "oneof_nested_message", "oneof_string", "oneof_bytes", "oneof_bool", "oneof_uint64", "oneof_float", "oneof_double", "oneof_enum", "oneof_null_value"},
}
M.TestAllTypesProto3_descriptor.reserved_names = {
    ["reserved_field"] = true,
}
pb.finalize_message(M.TestAllTypesProto3_descriptor)
M.TestAllTypesProto3_fields = pb.field_names({
    optional_int32 = "optional_int32",
    optional_int64 = "optional_int64",
    optional_uint32 = "optional_uint32",
    optional_uint64 = "optional_uint64",
    optional_sint32 = "optional_sint32",
    optional_sint64 = "optional_sint64",
    optional_fixed32 = "optional_fixed32",
    optional_fixed64 = "optional_fixed64",
    optional_sfixed32 = "optional_sfixed32",
    optional_sfixed64 = "optional_sfixed64",
    optional_float = "optional_float",
    optional_double = "optional_double",
    optional_bool = "optional_bool",
    optional_string = "optional_string",
    optional_bytes = "optional_bytes",
    optional_nested_message = "optional_nested_message",
    optional_foreign_message = "optional_foreign_message",
    optional_nested_enum = "optional_nested_enum",
    optional_foreign_enum = "optional_foreign_enum",
    optional_aliased_enum = "optional_aliased_enum",
    optional_string_piece = "optional_string_piece",
    optional_cord = "optional_cord",
    recursive_message = "recursive_message",
    repeated_int32 = "repeated_int32",
    repeated_int64 = "repeated_int64",
    repeated_uint32 = "repeated_uint32",
    repeated_uint64 = "repeated_uint64",
    repeated_sint32 = "repeated_sint32",
    repeated_sint64 = "repeated_sint64",
    repeated_fixed32 = "repeated_fixed32",
    repeated_fixed64 = "repeated_fixed64",
    repeated_sfixed32 = "repeated_sfixed32",
    repeated_sfixed64 = "repeated_sfixed64",
    repeated_float = "repeated_float",
    repeated_double = "repeated_double",
    repeated_bool = "repeated_bool",
    repeated_string = "repeated_string",
    repeated_bytes = "repeated_bytes",
    repeated_nested_message = "repeated_nested_message",
    repeated_foreign_message = "repeated_foreign_message",
    repeated_nested_enum = "repeated_nested_enum",
    repeated_foreign_enum = "repeated_foreign_enum",
    repeated_string_piece = "repeated_string_piece",
    repeated_cord = "repeated_cord",
    packed_int32 = "packed_int32",
    packed_int64 = "packed_int64",
    packed_uint32 = "packed_uint32",
    packed_uint64 = "packed_uint64",
    packed_sint32 = "packed_sint32",
    packed_sint64 = "packed_sint64",
    packed_fixed32 = "packed_fixed32",
    packed_fixed64 = "packed_fixed64",
    packed_sfixed32 = "packed_sfixed32",
    packed_sfixed64 = "packed_sfixed64",
    packed_float = "packed_float",
    packed_double = "packed_double",
    packed_bool = "packed_bool",
    packed_nested_enum = "packed_nested_enum",
    unpacked_int32 = "unpacked_int32",
    unpacked_int64 = "unpacked_int64",
    unpacked_uint32 = "unpacked_uint32",
    unpacked_uint64 = "unpacked_uint64",
    unpacked_sint32 = "unpacked_sint32",
    unpacked_sint64 = "unpacked_sint64",
    unpacked_fixed32 = "unpacked_fixed32",
    unpacked_fixed64 = "unpacked_fixed64",
    unpacked_sfixed32 = "unpacked_sfixed32",
    unpacked_sfixed64 = "unpacked_sfixed64",
    unpacked_float = "unpacked_float",
    unpacked_double = "unpacked_double",
    unpacked_bool = "unpacked_bool",
    unpacked_nested_enum = "unpacked_nested_enum",
    map_int32_int32 = "map_int32_int32",
    map_int64_int64 = "map_int64_int64",
    map_uint32_uint32 = "map_uint32_uint32",
    map_uint64_uint64 = "map_uint64_uint64",
    map_sint32_sint32 = "map_sint32_sint32",
    map_sint64_sint64 = "map_sint64_sint64",
    map_fixed32_fixed32 = "map_fixed32_fixed32",
    map_fixed64_fixed64 = "map_fixed64_fixed64",
    map_sfixed32_sfixed32 = "map_sfixed32_sfixed32",
    map_sfixed64_sfixed64 = "map_sfixed64_sfixed64",
    map_int32_float = "map_int32_float",
    map_int32_double = "map_int32_double",
    map_bool_bool = "map_bool_bool",
    map_string_string = "map_string_string",
    map_string_bytes = "map_string_bytes",
    map_string_nested_message = "map_string_nested_message",
    map_string_foreign_message = "map_string_foreign_message",
    map_string_nested_enum = "map_string_nested_enum",
    map_string_foreign_enum = "map_string_foreign_enum",
    oneof_uint32 = "oneof_uint32",
    oneof_nested_message = "oneof_nested_message",
    oneof_string = "oneof_string",
    oneof_bytes = "oneof_bytes",
    oneof_bool = "oneof_bool",
    oneof_uint64 = "oneof_uint64",
    oneof_float = "oneof_float",
    oneof_double = "oneof_double",
    oneof_enum = "oneof_enum",
    oneof_null_value = "oneof_null_value",
    optional_bool_wrapper = "optional_bool_wrapper",
    optional_int32_wrapper = "optional_int32_wrapper",
    optional_int64_wrapper = "optional_int64_wrapper",
    optional_uint32_wrapper = "optional_uint32_wrapper",
    optional_uint64_wrapper = "optional_uint64_wrapper",
    optional_float_wrapper = "optional_float_wrapper",
    optional_double_wrapper = "optional_double_wrapper",
    optional_string_wrapper = "optional_string_wrapper",
    optional_bytes_wrapper = "optional_bytes_wrapper",
    repeated_bool_wrapper = "repeated_bool_wrapper",
    repeated_int32_wrapper = "repeated_int32_wrapper",
    repeated_int64_wrapper = "repeated_int64_wrapper",
    repeated_uint32_wrapper = "repeated_uint32_wrapper",
    repeated_uint64_wrapper = "repeated_uint64_wrapper",
    repeated_float_wrapper = "repeated_float_wrapper",
    repeated_double_wrapper = "repeated_double_wrapper",
    repeated_string_wrapper = "repeated_string_wrapper",
    repeated_bytes_wrapper = "repeated_bytes_wrapper",
    optional_duration = "optional_duration",
    optional_timestamp = "optional_timestamp",
    optional_field_mask = "optional_field_mask",
    optional_struct = "optional_struct",
    optional_any = "optional_any",
    optional_value = "optional_value",
    optional_null_value = "optional_null_value",
    optional_empty = "optional_empty",
    repeated_duration = "repeated_duration",
    repeated_timestamp = "repeated_timestamp",
    repeated_fieldmask = "repeated_fieldmask",
    repeated_struct = "repeated_struct",
    repeated_any = "repeated_any",
    repeated_value = "repeated_value",
    repeated_list_value = "repeated_list_value",
    repeated_empty = "repeated_empty",
    fieldname1 = "fieldname1",
    field_name2 = "field_name2",
    _field_name3 = "_field_name3",
    field__name4_ = "field__name4_",
    field0name5 = "field0name5",
    field_0_name6 = "field_0_name6",
    fieldName7 = "fieldName7",
    FieldName8 = "FieldName8",
    field_Name9 = "field_Name9",
    Field_Name10 = "Field_Name10",
    FIELD_NAME11 = "FIELD_NAME11",
    FIELD_name12 = "FIELD_name12",
    __field_name13 = "__field_name13",
    __Field_name14 = "__Field_name14",
    field__name15 = "field__name15",
    field__Name16 = "field__Name16",
    field_name17__ = "field_name17__",
    Field_name18__ = "Field_name18__",
})
M.TestAllTypesProto3_oneofs = pb.field_names({
    oneof_field = "oneof_field",
})

-- Message: protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
M.TestAllTypesProto3_NestedMessage_descriptor.fields = {
    {name="a", id=1, kind='scalar', proto_type="int32"},
    {name="corecursive", id=2, kind='message', message=M.TestAllTypesProto3_descriptor},
}
pb.finalize_message(M.TestAllTypesProto3_NestedMessage_descriptor)
M.TestAllTypesProto3_NestedMessage_fields = pb.field_names({
    a = "a",
    corecursive = "corecursive",
})

-- Message: protobuf_test_messages.proto3.ForeignMessage
M.ForeignMessage_descriptor.fields = {
    {name="c", id=1, kind='scalar', proto_type="int32"},
}
pb.finalize_message(M.ForeignMessage_descriptor)
M.ForeignMessage_fields = pb.field_names({
    c = "c",
})

-- Message: protobuf_test_messages.proto3.NullHypothesisProto3
M.NullHypothesisProto3_descriptor.fields = {
}
pb.finalize_message(M.NullHypothesisProto3_descriptor)

-- Message: protobuf_test_messages.proto3.EnumOnlyProto3
M.EnumOnlyProto3_descriptor.fields = {
}
pb.finalize_message(M.EnumOnlyProto3_descriptor)

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@alias protobuf_test_messages.proto3.ForeignEnum integer
---@alias protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum integer
---@alias protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum integer
---@alias protobuf_test_messages.proto3.EnumOnlyProto3.Bool integer

--- This proto includes every type of field in both singular and repeated
--- forms.
---
--- Also, crucially, all messages and enums in this file are eventually
--- submessages of this message.  So for example, a fuzz test of TestAllTypes
--- could trigger bugs that occur in any message type in this file.  We verify
--- this stays true in a unit test.
---@class protobuf_test_messages.proto3.TestAllTypesProto3
---@field optional_int32 integer @ Singular test [kotlin] comment
---@field optional_int64 integer
---@field optional_uint32 integer
---@field optional_uint64 integer
---@field optional_sint32 integer
---@field optional_sint64 integer
---@field optional_fixed32 integer
---@field optional_fixed64 integer
---@field optional_sfixed32 integer
---@field optional_sfixed64 integer
---@field optional_float number
---@field optional_double number
---@field optional_bool boolean
---@field optional_string string
---@field optional_bytes string
---@field optional_nested_message protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field optional_foreign_message protobuf_test_messages.proto3.ForeignMessage
---@field optional_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
---@field optional_foreign_enum protobuf_test_messages.proto3.ForeignEnum
---@field optional_aliased_enum protobuf_test_messages.proto3.TestAllTypesProto3.AliasedEnum
---@field optional_string_piece string
---@field optional_cord string
---@field recursive_message protobuf_test_messages.proto3.TestAllTypesProto3
---@field repeated_int32 integer[] @ Repeated
---@field repeated_int64 integer[]
---@field repeated_uint32 integer[]
---@field repeated_uint64 integer[]
---@field repeated_sint32 integer[]
---@field repeated_sint64 integer[]
---@field repeated_fixed32 integer[]
---@field repeated_fixed64 integer[]
---@field repeated_sfixed32 integer[]
---@field repeated_sfixed64 integer[]
---@field repeated_float number[]
---@field repeated_double number[]
---@field repeated_bool boolean[]
---@field repeated_string string[]
---@field repeated_bytes string[]
---@field repeated_nested_message protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage[]
---@field repeated_foreign_message protobuf_test_messages.proto3.ForeignMessage[]
---@field repeated_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field repeated_foreign_enum protobuf_test_messages.proto3.ForeignEnum[]
---@field repeated_string_piece string[]
---@field repeated_cord string[]
---@field packed_int32 integer[] @ Packed
---@field packed_int64 integer[]
---@field packed_uint32 integer[]
---@field packed_uint64 integer[]
---@field packed_sint32 integer[]
---@field packed_sint64 integer[]
---@field packed_fixed32 integer[]
---@field packed_fixed64 integer[]
---@field packed_sfixed32 integer[]
---@field packed_sfixed64 integer[]
---@field packed_float number[]
---@field packed_double number[]
---@field packed_bool boolean[]
---@field packed_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field unpacked_int32 integer[] @ Unpacked
---@field unpacked_int64 integer[]
---@field unpacked_uint32 integer[]
---@field unpacked_uint64 integer[]
---@field unpacked_sint32 integer[]
---@field unpacked_sint64 integer[]
---@field unpacked_fixed32 integer[]
---@field unpacked_fixed64 integer[]
---@field unpacked_sfixed32 integer[]
---@field unpacked_sfixed64 integer[]
---@field unpacked_float number[]
---@field unpacked_double number[]
---@field unpacked_bool boolean[]
---@field unpacked_nested_enum protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum[]
---@field map_int32_int32 table<integer, integer> @ Map
---@field map_int64_int64 table<integer, integer>
---@field map_uint32_uint32 table<integer, integer>
---@field map_uint64_uint64 table<integer, integer>
---@field map_sint32_sint32 table<integer, integer>
---@field map_sint64_sint64 table<integer, integer>
---@field map_fixed32_fixed32 table<integer, integer>
---@field map_fixed64_fixed64 table<integer, integer>
---@field map_sfixed32_sfixed32 table<integer, integer>
---@field map_sfixed64_sfixed64 table<integer, integer>
---@field map_int32_float table<integer, number>
---@field map_int32_double table<integer, number>
---@field map_bool_bool table<boolean, boolean>
---@field map_string_string table<string, string>
---@field map_string_bytes table<string, string>
---@field map_string_nested_message table<string, protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage>
---@field map_string_foreign_message table<string, protobuf_test_messages.proto3.ForeignMessage>
---@field map_string_nested_enum table<string, protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum>
---@field map_string_foreign_enum table<string, protobuf_test_messages.proto3.ForeignEnum>
---@field oneof_uint32? integer
---@field oneof_nested_message? protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field oneof_string? string
---@field oneof_bytes? string
---@field oneof_bool? boolean
---@field oneof_uint64? integer
---@field oneof_float? number
---@field oneof_double? number
---@field oneof_enum? protobuf_test_messages.proto3.TestAllTypesProto3.NestedEnum
---@field oneof_null_value? google.protobuf.NullValue
---@field optional_bool_wrapper google.protobuf.BoolValue @ Well-known types
---@field optional_int32_wrapper google.protobuf.Int32Value
---@field optional_int64_wrapper google.protobuf.Int64Value
---@field optional_uint32_wrapper google.protobuf.UInt32Value
---@field optional_uint64_wrapper google.protobuf.UInt64Value
---@field optional_float_wrapper google.protobuf.FloatValue
---@field optional_double_wrapper google.protobuf.DoubleValue
---@field optional_string_wrapper google.protobuf.StringValue
---@field optional_bytes_wrapper google.protobuf.BytesValue
---@field repeated_bool_wrapper google.protobuf.BoolValue[]
---@field repeated_int32_wrapper google.protobuf.Int32Value[]
---@field repeated_int64_wrapper google.protobuf.Int64Value[]
---@field repeated_uint32_wrapper google.protobuf.UInt32Value[]
---@field repeated_uint64_wrapper google.protobuf.UInt64Value[]
---@field repeated_float_wrapper google.protobuf.FloatValue[]
---@field repeated_double_wrapper google.protobuf.DoubleValue[]
---@field repeated_string_wrapper google.protobuf.StringValue[]
---@field repeated_bytes_wrapper google.protobuf.BytesValue[]
---@field optional_duration google.protobuf.Duration
---@field optional_timestamp google.protobuf.Timestamp
---@field optional_field_mask google.protobuf.FieldMask
---@field optional_struct google.protobuf.Struct
---@field optional_any google.protobuf.Any
---@field optional_value google.protobuf.Value
---@field optional_null_value google.protobuf.NullValue
---@field optional_empty google.protobuf.Empty
---@field repeated_duration google.protobuf.Duration[]
---@field repeated_timestamp google.protobuf.Timestamp[]
---@field repeated_fieldmask google.protobuf.FieldMask[]
---@field repeated_struct google.protobuf.Struct[]
---@field repeated_any google.protobuf.Any[]
---@field repeated_value google.protobuf.Value[]
---@field repeated_list_value google.protobuf.ListValue[]
---@field repeated_empty google.protobuf.Empty[]
---@field fieldname1 integer @ Test field-name-to-JSON-name convention. (protobuf says names can be any valid C/C++ identifier.)
---@field field_name2 integer
---@field _field_name3 integer
---@field field__name4_ integer
---@field field0name5 integer
---@field field_0_name6 integer
---@field fieldName7 integer
---@field FieldName8 integer
---@field field_Name9 integer
---@field Field_Name10 integer
---@field FIELD_NAME11 integer
---@field FIELD_name12 integer
---@field __field_name13 integer
---@field __Field_name14 integer
---@field field__name15 integer
---@field field__Name16 integer
---@field field_name17__ integer
---@field Field_name18__ integer

---@class protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@field a integer
---@field corecursive protobuf_test_messages.proto3.TestAllTypesProto3

---@class protobuf_test_messages.proto3.ForeignMessage
---@field c integer

---@class protobuf_test_messages.proto3.NullHypothesisProto3

---@class protobuf_test_messages.proto3.EnumOnlyProto3

---@param t? protobuf_test_messages.proto3.TestAllTypesProto3
---@return protobuf_test_messages.proto3.TestAllTypesProto3
function M.TestAllTypesProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3
---@return string
function M.TestAllTypesProto3_encode(t) return pb.encode(M.TestAllTypesProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.TestAllTypesProto3
function M.TestAllTypesProto3_decode(b) return pb.decode(M.TestAllTypesProto3_descriptor, b) end
function M.TestAllTypesProto3_decode_unsafe(b) return pb.decode_unsafe(M.TestAllTypesProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.TestAllTypesProto3_decode_lazy(b) return pb.decode_lazy(M.TestAllTypesProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.TestAllTypesProto3_text(t, opts) return pb.text.encode(M.TestAllTypesProto3_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@return protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
function M.TestAllTypesProto3_NestedMessage_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@return string
function M.TestAllTypesProto3_NestedMessage_encode(t) return pb.encode(M.TestAllTypesProto3_NestedMessage_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
function M.TestAllTypesProto3_NestedMessage_decode(b) return pb.decode(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
function M.TestAllTypesProto3_NestedMessage_decode_unsafe(b) return pb.decode_unsafe(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.TestAllTypesProto3_NestedMessage_decode_lazy(b) return pb.decode_lazy(M.TestAllTypesProto3_NestedMessage_descriptor, b) end
---@param t protobuf_test_messages.proto3.TestAllTypesProto3.NestedMessage
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.TestAllTypesProto3_NestedMessage_text(t, opts) return pb.text.encode(M.TestAllTypesProto3_NestedMessage_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.ForeignMessage
---@return protobuf_test_messages.proto3.ForeignMessage
function M.ForeignMessage_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.ForeignMessage
---@return string
function M.ForeignMessage_encode(t) return pb.encode(M.ForeignMessage_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.ForeignMessage
function M.ForeignMessage_decode(b) return pb.decode(M.ForeignMessage_descriptor, b) end
function M.ForeignMessage_decode_unsafe(b) return pb.decode_unsafe(M.ForeignMessage_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.ForeignMessage_decode_lazy(b) return pb.decode_lazy(M.ForeignMessage_descriptor, b) end
---@param t protobuf_test_messages.proto3.ForeignMessage
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.ForeignMessage_text(t, opts) return pb.text.encode(M.ForeignMessage_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.NullHypothesisProto3
---@return protobuf_test_messages.proto3.NullHypothesisProto3
function M.NullHypothesisProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.NullHypothesisProto3
---@return string
function M.NullHypothesisProto3_encode(t) return pb.encode(M.NullHypothesisProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.NullHypothesisProto3
function M.NullHypothesisProto3_decode(b) return pb.decode(M.NullHypothesisProto3_descriptor, b) end
function M.NullHypothesisProto3_decode_unsafe(b) return pb.decode_unsafe(M.NullHypothesisProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.NullHypothesisProto3_decode_lazy(b) return pb.decode_lazy(M.NullHypothesisProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.NullHypothesisProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.NullHypothesisProto3_text(t, opts) return pb.text.encode(M.NullHypothesisProto3_descriptor, t, opts) end

---@param t? protobuf_test_messages.proto3.EnumOnlyProto3
---@return protobuf_test_messages.proto3.EnumOnlyProto3
function M.EnumOnlyProto3_new(t) return t or {} end
---@param t protobuf_test_messages.proto3.EnumOnlyProto3
---@return string
function M.EnumOnlyProto3_encode(t) return pb.encode(M.EnumOnlyProto3_descriptor, t) end
---@param b string
---@return protobuf_test_messages.proto3.EnumOnlyProto3
function M.EnumOnlyProto3_decode(b) return pb.decode(M.EnumOnlyProto3_descriptor, b) end
function M.EnumOnlyProto3_decode_unsafe(b) return pb.decode_unsafe(M.EnumOnlyProto3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.EnumOnlyProto3_decode_lazy(b) return pb.decode_lazy(M.EnumOnlyProto3_descriptor, b) end
---@param t protobuf_test_messages.proto3.EnumOnlyProto3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.EnumOnlyProto3_text(t, opts) return pb.text.encode(M.EnumOnlyProto3_descriptor, t, opts) end

return M
