-- Code generated by protoc-gen-tarantool. DO NOT EDIT.
-- source: c_grow.proto
-- syntax: proto3
-- package: c_grow

local pb = require("pb")
local wire = pb.wire
local string_byte = string.byte
local utf8_len = require('utf8').len
local band = bit.band
local rshift = bit.rshift
local CHARS = wire.CHARS
local table_new = require('table.new')
local ffi = require('ffi')
local INT64  = ffi.typeof('int64_t')
local UINT64 = ffi.typeof('uint64_t')

local M = {}

M.options = {go_package = "tarantoolpb_synthetic/c_grow"}

-- Pre-declare message descriptors so cross-references resolve.
M.KV_descriptor = {name = "c_grow.KV"}
M.Header_descriptor = {name = "c_grow.Header"}
M.Before_descriptor = {name = "c_grow.Before"}
M.After_descriptor = {name = "c_grow.After"}
M.Between_descriptor = {name = "c_grow.Between"}
M.BigFirst_descriptor = {name = "c_grow.BigFirst"}
M.Level3_descriptor = {name = "c_grow.Level3"}
M.Level2_descriptor = {name = "c_grow.Level2"}
M.Level1_descriptor = {name = "c_grow.Level1"}
M.WithMap_descriptor = {name = "c_grow.WithMap"}
M.WithPacked_descriptor = {name = "c_grow.WithPacked"}

-- Message: c_grow.KV
M.KV_descriptor.fields = {
    {name="key", id=1, kind='scalar', proto_type="bytes"},
    {name="value", id=5, kind='scalar', proto_type="bytes"},
}
pb.finalize_message(M.KV_descriptor)
M.KV_fields = pb.field_names({
    key = "key",
    value = "value",
})

-- Message: c_grow.Header
M.Header_descriptor.fields = {
    {name="a", id=1, kind='scalar', proto_type="uint64"},
}
pb.finalize_message(M.Header_descriptor)
M.Header_fields = pb.field_names({
    a = "a",
})

-- Message: c_grow.Before
M.Before_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="kvs", id=2, kind='message', message=M.KV_descriptor, repeated=true},
}
pb.finalize_message(M.Before_descriptor)
M.Before_fields = pb.field_names({
    header = "header",
    kvs = "kvs",
})

-- Message: c_grow.After
M.After_descriptor.fields = {
    {name="kvs", id=1, kind='message', message=M.KV_descriptor, repeated=true},
    {name="header", id=2, kind='message', message=M.Header_descriptor},
}
pb.finalize_message(M.After_descriptor)
M.After_fields = pb.field_names({
    kvs = "kvs",
    header = "header",
})

-- Message: c_grow.Between
M.Between_descriptor.fields = {
    {name="head", id=1, kind='message', message=M.KV_descriptor, repeated=true},
    {name="header", id=2, kind='message', message=M.Header_descriptor},
    {name="tail", id=3, kind='message', message=M.KV_descriptor, repeated=true},
}
pb.finalize_message(M.Between_descriptor)
M.Between_fields = pb.field_names({
    head = "head",
    header = "header",
    tail = "tail",
})

-- Message: c_grow.BigFirst
M.BigFirst_descriptor.fields = {
    {name="big", id=1, kind='scalar', proto_type="bytes"},
    {name="kvs", id=2, kind='message', message=M.KV_descriptor, repeated=true},
    {name="name", id=3, kind='scalar', proto_type="string"},
}
pb.finalize_message(M.BigFirst_descriptor)
M.BigFirst_fields = pb.field_names({
    big = "big",
    kvs = "kvs",
    name = "name",
})

-- Message: c_grow.Level3
M.Level3_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="kvs", id=2, kind='message', message=M.KV_descriptor, repeated=true},
}
pb.finalize_message(M.Level3_descriptor)
M.Level3_fields = pb.field_names({
    header = "header",
    kvs = "kvs",
})

-- Message: c_grow.Level2
M.Level2_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="items", id=2, kind='message', message=M.Level3_descriptor, repeated=true},
    {name="kvs", id=3, kind='message', message=M.KV_descriptor, repeated=true},
    {name="trailer", id=4, kind='message', message=M.Header_descriptor},
}
pb.finalize_message(M.Level2_descriptor)
M.Level2_fields = pb.field_names({
    header = "header",
    items = "items",
    kvs = "kvs",
    trailer = "trailer",
})

-- Message: c_grow.Level1
M.Level1_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="items", id=2, kind='message', message=M.Level2_descriptor, repeated=true},
    {name="kvs", id=3, kind='message', message=M.KV_descriptor, repeated=true},
    {name="trailer", id=4, kind='message', message=M.Header_descriptor},
}
pb.finalize_message(M.Level1_descriptor)
M.Level1_fields = pb.field_names({
    header = "header",
    items = "items",
    kvs = "kvs",
    trailer = "trailer",
})

-- Message: c_grow.WithMap
M.WithMap_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="by_key", id=2, kind='map', key={kind='scalar', proto_type="string"}, value={kind='message', message=M.KV_descriptor}},
    {name="nested", id=3, kind='map', key={kind='scalar', proto_type="int32"}, value={kind='message', message=M.Level3_descriptor}},
    {name="trailer", id=4, kind='message', message=M.Header_descriptor},
}
pb.finalize_message(M.WithMap_descriptor)
M.WithMap_fields = pb.field_names({
    header = "header",
    by_key = "by_key",
    nested = "nested",
    trailer = "trailer",
})

-- Message: c_grow.WithPacked
M.WithPacked_descriptor.fields = {
    {name="header", id=1, kind='message', message=M.Header_descriptor},
    {name="nums", id=2, kind='scalar', proto_type="uint64", repeated=true, packed=true},
    {name="kvs", id=3, kind='message', message=M.KV_descriptor, repeated=true},
    {name="more", id=4, kind='scalar', proto_type="sint32", repeated=true, packed=true},
    {name="trailer", id=5, kind='message', message=M.Header_descriptor},
}
pb.finalize_message(M.WithPacked_descriptor)
M.WithPacked_fields = pb.field_names({
    header = "header",
    nums = "nums",
    kvs = "kvs",
    more = "more",
    trailer = "trailer",
})

-- EmmyLua / lua-language-server type annotations.
-- These are comments — no runtime effect. They give editors
-- autocomplete and type-checking for the generated wrappers.
---@class c_grow.KV
---@field key string
---@field value string

---@class c_grow.Header
---@field a integer

--- The singular message field before, after, and between large repeated
--- fields.
---@class c_grow.Before
---@field header c_grow.Header
---@field kvs c_grow.KV[]

---@class c_grow.After
---@field kvs c_grow.KV[]
---@field header c_grow.Header

---@class c_grow.Between
---@field head c_grow.KV[]
---@field header c_grow.Header
---@field tail c_grow.KV[]

--- A large scalar ahead of a repeated message field: the first growth
--- happens in a scalar encode rather than in a sub-message.
---@class c_grow.BigFirst
---@field big string
---@field kvs c_grow.KV[]
---@field name string

--- Three levels, each with a singular message and a large repeated field.
---@class c_grow.Level3
---@field header c_grow.Header
---@field kvs c_grow.KV[]

---@class c_grow.Level2
---@field header c_grow.Header
---@field items c_grow.Level3[]
---@field kvs c_grow.KV[]
---@field trailer c_grow.Header

---@class c_grow.Level1
---@field header c_grow.Header
---@field items c_grow.Level2[]
---@field kvs c_grow.KV[]
---@field trailer c_grow.Header

--- Maps with message values next to singular message fields.
---@class c_grow.WithMap
---@field header c_grow.Header
---@field by_key table<string, c_grow.KV>
---@field nested table<integer, c_grow.Level3>
---@field trailer c_grow.Header

--- Packed scalars between sub-messages.
---@class c_grow.WithPacked
---@field header c_grow.Header
---@field nums integer[]
---@field kvs c_grow.KV[]
---@field more integer[]
---@field trailer c_grow.Header

---@param t? c_grow.KV
---@return c_grow.KV
function M.KV_new(t) return t or {} end
---@param t c_grow.KV
---@return string
function M.KV_encode(t) return pb.encode(M.KV_descriptor, t) end
---@param b string
---@return c_grow.KV
function M.KV_decode(b) return pb.decode(M.KV_descriptor, b) end
function M.KV_decode_unsafe(b) return pb.decode_unsafe(M.KV_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.KV_decode_lazy(b) return pb.decode_lazy(M.KV_descriptor, b) end
---@param t c_grow.KV
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.KV_text(t, opts) return pb.text.encode(M.KV_descriptor, t, opts) end

---@param t? c_grow.Header
---@return c_grow.Header
function M.Header_new(t) return t or {} end
---@param t c_grow.Header
---@return string
function M.Header_encode(t) return pb.encode(M.Header_descriptor, t) end
---@param b string
---@return c_grow.Header
function M.Header_decode(b) return pb.decode(M.Header_descriptor, b) end
function M.Header_decode_unsafe(b) return pb.decode_unsafe(M.Header_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Header_decode_lazy(b) return pb.decode_lazy(M.Header_descriptor, b) end
---@param t c_grow.Header
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Header_text(t, opts) return pb.text.encode(M.Header_descriptor, t, opts) end

---@param t? c_grow.Before
---@return c_grow.Before
function M.Before_new(t) return t or {} end
---@param t c_grow.Before
---@return string
function M.Before_encode(t) return pb.encode(M.Before_descriptor, t) end
---@param b string
---@return c_grow.Before
function M.Before_decode(b) return pb.decode(M.Before_descriptor, b) end
function M.Before_decode_unsafe(b) return pb.decode_unsafe(M.Before_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Before_decode_lazy(b) return pb.decode_lazy(M.Before_descriptor, b) end
---@param t c_grow.Before
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Before_text(t, opts) return pb.text.encode(M.Before_descriptor, t, opts) end

---@param t? c_grow.After
---@return c_grow.After
function M.After_new(t) return t or {} end
---@param t c_grow.After
---@return string
function M.After_encode(t) return pb.encode(M.After_descriptor, t) end
---@param b string
---@return c_grow.After
function M.After_decode(b) return pb.decode(M.After_descriptor, b) end
function M.After_decode_unsafe(b) return pb.decode_unsafe(M.After_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.After_decode_lazy(b) return pb.decode_lazy(M.After_descriptor, b) end
---@param t c_grow.After
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.After_text(t, opts) return pb.text.encode(M.After_descriptor, t, opts) end

---@param t? c_grow.Between
---@return c_grow.Between
function M.Between_new(t) return t or {} end
---@param t c_grow.Between
---@return string
function M.Between_encode(t) return pb.encode(M.Between_descriptor, t) end
---@param b string
---@return c_grow.Between
function M.Between_decode(b) return pb.decode(M.Between_descriptor, b) end
function M.Between_decode_unsafe(b) return pb.decode_unsafe(M.Between_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Between_decode_lazy(b) return pb.decode_lazy(M.Between_descriptor, b) end
---@param t c_grow.Between
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Between_text(t, opts) return pb.text.encode(M.Between_descriptor, t, opts) end

---@param t? c_grow.BigFirst
---@return c_grow.BigFirst
function M.BigFirst_new(t) return t or {} end
---@param t c_grow.BigFirst
---@return string
function M.BigFirst_encode(t) return pb.encode(M.BigFirst_descriptor, t) end
---@param b string
---@return c_grow.BigFirst
function M.BigFirst_decode(b) return pb.decode(M.BigFirst_descriptor, b) end
function M.BigFirst_decode_unsafe(b) return pb.decode_unsafe(M.BigFirst_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.BigFirst_decode_lazy(b) return pb.decode_lazy(M.BigFirst_descriptor, b) end
---@param t c_grow.BigFirst
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.BigFirst_text(t, opts) return pb.text.encode(M.BigFirst_descriptor, t, opts) end

---@param t? c_grow.Level3
---@return c_grow.Level3
function M.Level3_new(t) return t or {} end
---@param t c_grow.Level3
---@return string
function M.Level3_encode(t) return pb.encode(M.Level3_descriptor, t) end
---@param b string
---@return c_grow.Level3
function M.Level3_decode(b) return pb.decode(M.Level3_descriptor, b) end
function M.Level3_decode_unsafe(b) return pb.decode_unsafe(M.Level3_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Level3_decode_lazy(b) return pb.decode_lazy(M.Level3_descriptor, b) end
---@param t c_grow.Level3
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Level3_text(t, opts) return pb.text.encode(M.Level3_descriptor, t, opts) end

---@param t? c_grow.Level2
---@return c_grow.Level2
function M.Level2_new(t) return t or {} end
---@param t c_grow.Level2
---@return string
function M.Level2_encode(t) return pb.encode(M.Level2_descriptor, t) end
---@param b string
---@return c_grow.Level2
function M.Level2_decode(b) return pb.decode(M.Level2_descriptor, b) end
function M.Level2_decode_unsafe(b) return pb.decode_unsafe(M.Level2_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Level2_decode_lazy(b) return pb.decode_lazy(M.Level2_descriptor, b) end
---@param t c_grow.Level2
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Level2_text(t, opts) return pb.text.encode(M.Level2_descriptor, t, opts) end

---@param t? c_grow.Level1
---@return c_grow.Level1
function M.Level1_new(t) return t or {} end
---@param t c_grow.Level1
---@return string
function M.Level1_encode(t) return pb.encode(M.Level1_descriptor, t) end
---@param b string
---@return c_grow.Level1
function M.Level1_decode(b) return pb.decode(M.Level1_descriptor, b) end
function M.Level1_decode_unsafe(b) return pb.decode_unsafe(M.Level1_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.Level1_decode_lazy(b) return pb.decode_lazy(M.Level1_descriptor, b) end
---@param t c_grow.Level1
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.Level1_text(t, opts) return pb.text.encode(M.Level1_descriptor, t, opts) end

---@param t? c_grow.WithMap
---@return c_grow.WithMap
function M.WithMap_new(t) return t or {} end
---@param t c_grow.WithMap
---@return string
function M.WithMap_encode(t) return pb.encode(M.WithMap_descriptor, t) end
---@param b string
---@return c_grow.WithMap
function M.WithMap_decode(b) return pb.decode(M.WithMap_descriptor, b) end
function M.WithMap_decode_unsafe(b) return pb.decode_unsafe(M.WithMap_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.WithMap_decode_lazy(b) return pb.decode_lazy(M.WithMap_descriptor, b) end
---@param t c_grow.WithMap
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.WithMap_text(t, opts) return pb.text.encode(M.WithMap_descriptor, t, opts) end

---@param t? c_grow.WithPacked
---@return c_grow.WithPacked
function M.WithPacked_new(t) return t or {} end
---@param t c_grow.WithPacked
---@return string
function M.WithPacked_encode(t) return pb.encode(M.WithPacked_descriptor, t) end
---@param b string
---@return c_grow.WithPacked
function M.WithPacked_decode(b) return pb.decode(M.WithPacked_descriptor, b) end
function M.WithPacked_decode_unsafe(b) return pb.decode_unsafe(M.WithPacked_descriptor, b) end
---@param b string
---@return pb.MessageView
function M.WithPacked_decode_lazy(b) return pb.decode_lazy(M.WithPacked_descriptor, b) end
---@param t c_grow.WithPacked
---@param opts? {single_line: boolean?, indent: string?}
---@return string
function M.WithPacked_text(t, opts) return pb.text.encode(M.WithPacked_descriptor, t, opts) end

return M
